/*
 * Copyright (c) 2006-2015 Triductor Technology, Inc.
 *           All Rights Reserved Worldwide
 *
 * Filename: lightelf_mc_reg.h
 * Author  : $Author: Pmeng $
 * Date    : Jun/01/2015
 * Version : $Revision: 1589 $
 * Purpose : Describe all the available registers for MC of LIGHTELF.
             This file is automatically generated by Register Parser.
 */

#ifndef __LIGHTELF_MC_REG_H__
#define __LIGHTELF_MC_REG_H__

#ifndef REG32
    #define REG32(x)                    (*(volatile unsigned int *)(x))
#endif

#ifndef _REG_FLD_OP_
    #define _REG_FLD_OP_

    // Register Field Mask
    #define FLD_MASK(s,e)              ((0xffffffff >> (31-(e)+(s))) << (s))

    // Register Field Mask Write-Data
    // s -- Start of Bit  e -- End   of Bit
    // v -- Value
    #define FLD_MWD(s,e,v)              (((v) << (s)) & FLD_MASK((s),(e)))

    // Register Field Mask Read-Data
    // s -- Start of Bit  e -- End   of Bit
    // v -- Value
    #define FLD_MRD(s,e,v)              (((v) & FLD_MASK((s),(e))) >> (s))

    // Register Field Write operation
    // a -- Address   s -- Start of Bit
    // v -- Value     e -- End   of Bit
    #define OP_FLD_WR(a,s,e,v)          (REG32((a)) = (((v) << (s)) & FLD_MASK((s),(e))) | (REG32((a)) & ~FLD_MASK((s),(e))))
    #define OP_FLD_WR_EXC(a,s,e,v)      (REG32((a)) = (((v) << (s)) & FLD_MASK((s),(e))))

    // Register Field Read operation
    #define OP_FLD_RD(a,s,e)            ((REG32((a)) & FLD_MASK((s),(e))) >> (s))

#endif

//Address Offset for multi-instance mode only
#ifndef  REG_OFFSET_MC
    #define  REG_OFFSET_MC  (0x0)
#endif

// Base address
#ifndef REG_BASE_MC
    #define  REG_BASE_MC    (0xf0200000)
#endif



//------------------------------------
// Basic Registers
//------------------------------------
#define  REG_MC_CSR                                               (REG_BASE_MC + 0x00)
    //Read/Write-Register Using Address
    #define  RD_MC_CSR()                                          (REG32(REG_MC_CSR))
    #define  WR_MC_CSR(v)                                         (REG32(REG_MC_CSR) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_MC_CSR()                                   (0xFFFFFF00)  
    #define  REG_WMASK_MC_CSR()                                   (0xFFFFEF00)

    //Field: MC_REF_INT
    #define  FLD_LSB_MC_REF_INT()                                 (8)
    #define  FLD_MSB_MC_REF_INT()                                 (10)
    #define  FLD_MASK_MC_REF_INT()                                (FLD_MASK(8, 10))
    #define  FLD_MWD_MC_REF_INT(v)                                (FLD_MWD(8, 10, v))
    #define  FLD_MRD_MC_REF_INT(v)                                (FLD_MRD(8, 10, v))
    #define  SET_MC_REF_INT(v)                                    OP_FLD_WR(REG_MC_CSR, 8, 10, v)
    #define  GET_MC_REF_INT()                                     OP_FLD_RD(REG_MC_CSR, 8, 10)
    #define  RST_MC_REF_INT()                                     OP_FLD_WR(REG_MC_CSR, 8, 10, 0x0)

    //Field: MC_DLL_RST_REQ
    #define  FLD_LSB_MC_DLL_RST_REQ()                             (11)
    #define  FLD_MSB_MC_DLL_RST_REQ()                             (11)
    #define  FLD_MASK_MC_DLL_RST_REQ()                            (FLD_MASK(11, 11))
    #define  FLD_MWD_MC_DLL_RST_REQ(v)                            (FLD_MWD(11, 11, v))
    #define  FLD_MRD_MC_DLL_RST_REQ(v)                            (FLD_MRD(11, 11, v))
    #define  SET_MC_DLL_RST_REQ(v)                                OP_FLD_WR(REG_MC_CSR, 11, 11, v)
    #define  GET_MC_DLL_RST_REQ()                                 OP_FLD_RD(REG_MC_CSR, 11, 11)
    #define  RST_MC_DLL_RST_REQ()                                 OP_FLD_WR(REG_MC_CSR, 11, 11, 0x0)

    //Field: MC_SUSPEND
    #define  FLD_LSB_MC_SUSPEND()                                 (12)
    #define  FLD_MSB_MC_SUSPEND()                                 (12)
    #define  FLD_MASK_MC_SUSPEND()                                (FLD_MASK(12, 12))
    #define  FLD_MWD_MC_SUSPEND(v)                                (FLD_MWD(12, 12, v))
    #define  FLD_MRD_MC_SUSPEND(v)                                (FLD_MRD(12, 12, v))
    #define  GET_MC_SUSPEND()                                     OP_FLD_RD(REG_MC_CSR, 12, 12)

    //Field: MC_RESUME_REQ
    #define  FLD_LSB_MC_RESUME_REQ()                              (13)
    #define  FLD_MSB_MC_RESUME_REQ()                              (13)
    #define  FLD_MASK_MC_RESUME_REQ()                             (FLD_MASK(13, 13))
    #define  FLD_MWD_MC_RESUME_REQ(v)                             (FLD_MWD(13, 13, v))
    #define  FLD_MRD_MC_RESUME_REQ(v)                             (FLD_MRD(13, 13, v))
    #define  SET_MC_RESUME_REQ(v)                                 OP_FLD_WR(REG_MC_CSR, 13, 13, v)
    #define  GET_MC_RESUME_REQ()                                  OP_FLD_RD(REG_MC_CSR, 13, 13)
    #define  RST_MC_RESUME_REQ()                                  OP_FLD_WR(REG_MC_CSR, 13, 13, 0x0)

    //Field: MC_SUSP_REQ
    #define  FLD_LSB_MC_SUSP_REQ()                                (14)
    #define  FLD_MSB_MC_SUSP_REQ()                                (14)
    #define  FLD_MASK_MC_SUSP_REQ()                               (FLD_MASK(14, 14))
    #define  FLD_MWD_MC_SUSP_REQ(v)                               (FLD_MWD(14, 14, v))
    #define  FLD_MRD_MC_SUSP_REQ(v)                               (FLD_MRD(14, 14, v))
    #define  SET_MC_SUSP_REQ(v)                                   OP_FLD_WR(REG_MC_CSR, 14, 14, v)
    #define  GET_MC_SUSP_REQ()                                    OP_FLD_RD(REG_MC_CSR, 14, 14)
    #define  RST_MC_SUSP_REQ()                                    OP_FLD_WR(REG_MC_CSR, 14, 14, 0x0)

    //Field: MC_SLOW_MODE
    #define  FLD_LSB_MC_SLOW_MODE()                               (15)
    #define  FLD_MSB_MC_SLOW_MODE()                               (15)
    #define  FLD_MASK_MC_SLOW_MODE()                              (FLD_MASK(15, 15))
    #define  FLD_MWD_MC_SLOW_MODE(v)                              (FLD_MWD(15, 15, v))
    #define  FLD_MRD_MC_SLOW_MODE(v)                              (FLD_MRD(15, 15, v))
    #define  SET_MC_SLOW_MODE(v)                                  OP_FLD_WR(REG_MC_CSR, 15, 15, v)
    #define  GET_MC_SLOW_MODE()                                   OP_FLD_RD(REG_MC_CSR, 15, 15)
    #define  RST_MC_SLOW_MODE()                                   OP_FLD_WR(REG_MC_CSR, 15, 15, 0x0)

    //Field: MC_DC_SEL
    #define  FLD_LSB_MC_DC_SEL()                                  (16)
    #define  FLD_MSB_MC_DC_SEL()                                  (21)
    #define  FLD_MASK_MC_DC_SEL()                                 (FLD_MASK(16, 21))
    #define  FLD_MWD_MC_DC_SEL(v)                                 (FLD_MWD(16, 21, v))
    #define  FLD_MRD_MC_DC_SEL(v)                                 (FLD_MRD(16, 21, v))
    #define  SET_MC_DC_SEL(v)                                     OP_FLD_WR(REG_MC_CSR, 16, 21, v)
    #define  GET_MC_DC_SEL()                                      OP_FLD_RD(REG_MC_CSR, 16, 21)
    #define  RST_MC_DC_SEL()                                      OP_FLD_WR(REG_MC_CSR, 16, 21, 0x0)

    //Field: MC_DC_EN
    #define  FLD_LSB_MC_DC_EN()                                   (22)
    #define  FLD_MSB_MC_DC_EN()                                   (22)
    #define  FLD_MASK_MC_DC_EN()                                  (FLD_MASK(22, 22))
    #define  FLD_MWD_MC_DC_EN(v)                                  (FLD_MWD(22, 22, v))
    #define  FLD_MRD_MC_DC_EN(v)                                  (FLD_MRD(22, 22, v))
    #define  SET_MC_DC_EN(v)                                      OP_FLD_WR(REG_MC_CSR, 22, 22, v)
    #define  GET_MC_DC_EN()                                       OP_FLD_RD(REG_MC_CSR, 22, 22)
    #define  RST_MC_DC_EN()                                       OP_FLD_WR(REG_MC_CSR, 22, 22, 0x0)

    //Field: MC_CLK_CS
    #define  FLD_LSB_MC_CLK_CS()                                  (23)
    #define  FLD_MSB_MC_CLK_CS()                                  (23)
    #define  FLD_MASK_MC_CLK_CS()                                 (FLD_MASK(23, 23))
    #define  FLD_MWD_MC_CLK_CS(v)                                 (FLD_MWD(23, 23, v))
    #define  FLD_MRD_MC_CLK_CS(v)                                 (FLD_MRD(23, 23, v))
    #define  SET_MC_CLK_CS(v)                                     OP_FLD_WR(REG_MC_CSR, 23, 23, v)
    #define  GET_MC_CLK_CS()                                      OP_FLD_RD(REG_MC_CSR, 23, 23)
    #define  RST_MC_CLK_CS()                                      OP_FLD_WR(REG_MC_CSR, 23, 23, 0x0)

    //Field: MC_REF_DIV
    #define  FLD_LSB_MC_REF_DIV()                                 (24)
    #define  FLD_MSB_MC_REF_DIV()                                 (31)
    #define  FLD_MASK_MC_REF_DIV()                                (FLD_MASK(24, 31))
    #define  FLD_MWD_MC_REF_DIV(v)                                (FLD_MWD(24, 31, v))
    #define  FLD_MRD_MC_REF_DIV(v)                                (FLD_MRD(24, 31, v))
    #define  SET_MC_REF_DIV(v)                                    OP_FLD_WR(REG_MC_CSR, 24, 31, v)
    #define  GET_MC_REF_DIV()                                     OP_FLD_RD(REG_MC_CSR, 24, 31)
    #define  RST_MC_REF_DIV()                                     OP_FLD_WR(REG_MC_CSR, 24, 31, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_MC_CSR(REF_INT,DLL_RST_REQ,SUSPEND,RESUME_REQ,SUSP_REQ,SLOW_MODE,DC_SEL,DC_EN,CLK_CS,REF_DIV) \
                (WR_MC_CSR( \
                  (FLD_MWD_MC_REF_INT(REF_INT))                                        | \
                  (FLD_MWD_MC_DLL_RST_REQ(DLL_RST_REQ))                                | \
                  (FLD_MWD_MC_RESUME_REQ(RESUME_REQ))                                  | \
                  (FLD_MWD_MC_SUSP_REQ(SUSP_REQ))                                      | \
                  (FLD_MWD_MC_SLOW_MODE(SLOW_MODE))                                    | \
                  (FLD_MWD_MC_DC_SEL(DC_SEL))                                          | \
                  (FLD_MWD_MC_DC_EN(DC_EN))                                            | \
                  (FLD_MWD_MC_CLK_CS(CLK_CS))                                          | \
                  (FLD_MWD_MC_REF_DIV(REF_DIV))                                          \
                ))


#define  REG_MC_BAMR                                              (REG_BASE_MC + 0x08)
    //Read/Write-Register Using Address
    #define  RD_MC_BAMR()                                         (REG32(REG_MC_BAMR))
    #define  WR_MC_BAMR(v)                                        (REG32(REG_MC_BAMR) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_MC_BAMR()                                  (0xFF)  
    #define  REG_WMASK_MC_BAMR()                                  (0xFF)

    //Field: MC_MASK
    #define  FLD_LSB_MC_MASK()                                    (0)
    #define  FLD_MSB_MC_MASK()                                    (7)
    #define  FLD_MASK_MC_MASK()                                   (FLD_MASK(0, 7))
    #define  FLD_MWD_MC_MASK(v)                                   (FLD_MWD(0, 7, v))
    #define  FLD_MRD_MC_MASK(v)                                   (FLD_MRD(0, 7, v))
    #define  SET_MC_MASK(v)                                       OP_FLD_WR_EXC(REG_MC_BAMR, 0, 7, v)
    #define  GET_MC_MASK()                                        OP_FLD_RD(REG_MC_BAMR, 0, 7)
    #define  RST_MC_MASK()                                        OP_FLD_WR_EXC(REG_MC_BAMR, 0, 7, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_MC_BAMR(MASK) \
                (WR_MC_BAMR( \
                  (FLD_MWD_MC_MASK(MASK))                                                \
                ))


#define  REG_MC_CSC0                                              (REG_BASE_MC + 0x10)
    //Read/Write-Register Using Address
    #define  RD_MC_CSC0()                                         (REG32(REG_MC_CSC0))
    #define  WR_MC_CSC0(v)                                        (REG32(REG_MC_CSC0) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_MC_CSC0()                                  (0xFF17FF)  
    #define  REG_WMASK_MC_CSC0()                                  (0xFF17FF)

    //Field: MC_EN0
    #define  FLD_LSB_MC_EN0()                                     (0)
    #define  FLD_MSB_MC_EN0()                                     (0)
    #define  FLD_MASK_MC_EN0()                                    (FLD_MASK(0, 0))
    #define  FLD_MWD_MC_EN0(v)                                    (FLD_MWD(0, 0, v))
    #define  FLD_MRD_MC_EN0(v)                                    (FLD_MRD(0, 0, v))
    #define  SET_MC_EN0(v)                                        OP_FLD_WR(REG_MC_CSC0, 0, 0, v)
    #define  GET_MC_EN0()                                         OP_FLD_RD(REG_MC_CSC0, 0, 0)
    #define  RST_MC_EN0()                                         OP_FLD_WR(REG_MC_CSC0, 0, 0, 0x0)

    //Field: MC_MEM_TYPE0
    #define  FLD_LSB_MC_MEM_TYPE0()                               (1)
    #define  FLD_MSB_MC_MEM_TYPE0()                               (3)
    #define  FLD_MASK_MC_MEM_TYPE0()                              (FLD_MASK(1, 3))
    #define  FLD_MWD_MC_MEM_TYPE0(v)                              (FLD_MWD(1, 3, v))
    #define  FLD_MRD_MC_MEM_TYPE0(v)                              (FLD_MRD(1, 3, v))
    #define  SET_MC_MEM_TYPE0(v)                                  OP_FLD_WR(REG_MC_CSC0, 1, 3, v)
    #define  GET_MC_MEM_TYPE0()                                   OP_FLD_RD(REG_MC_CSC0, 1, 3)
    #define  RST_MC_MEM_TYPE0()                                   OP_FLD_WR(REG_MC_CSC0, 1, 3, 0x0)

    //Field: MC_BW0
    #define  FLD_LSB_MC_BW0()                                     (4)
    #define  FLD_MSB_MC_BW0()                                     (5)
    #define  FLD_MASK_MC_BW0()                                    (FLD_MASK(4, 5))
    #define  FLD_MWD_MC_BW0(v)                                    (FLD_MWD(4, 5, v))
    #define  FLD_MRD_MC_BW0(v)                                    (FLD_MRD(4, 5, v))
    #define  SET_MC_BW0(v)                                        OP_FLD_WR(REG_MC_CSC0, 4, 5, v)
    #define  GET_MC_BW0()                                         OP_FLD_RD(REG_MC_CSC0, 4, 5)
    #define  RST_MC_BW0()                                         OP_FLD_WR(REG_MC_CSC0, 4, 5, 0x0)

    //Field: MC_MS0
    #define  FLD_LSB_MC_MS0()                                     (6)
    #define  FLD_MSB_MC_MS0()                                     (7)
    #define  FLD_MASK_MC_MS0()                                    (FLD_MASK(6, 7))
    #define  FLD_MWD_MC_MS0(v)                                    (FLD_MWD(6, 7, v))
    #define  FLD_MRD_MC_MS0(v)                                    (FLD_MRD(6, 7, v))
    #define  SET_MC_MS0(v)                                        OP_FLD_WR(REG_MC_CSC0, 6, 7, v)
    #define  GET_MC_MS0()                                         OP_FLD_RD(REG_MC_CSC0, 6, 7)
    #define  RST_MC_MS0()                                         OP_FLD_WR(REG_MC_CSC0, 6, 7, 0x0)

    //Field: MC_WP0
    #define  FLD_LSB_MC_WP0()                                     (8)
    #define  FLD_MSB_MC_WP0()                                     (8)
    #define  FLD_MASK_MC_WP0()                                    (FLD_MASK(8, 8))
    #define  FLD_MWD_MC_WP0(v)                                    (FLD_MWD(8, 8, v))
    #define  FLD_MRD_MC_WP0(v)                                    (FLD_MRD(8, 8, v))
    #define  SET_MC_WP0(v)                                        OP_FLD_WR(REG_MC_CSC0, 8, 8, v)
    #define  GET_MC_WP0()                                         OP_FLD_RD(REG_MC_CSC0, 8, 8)
    #define  RST_MC_WP0()                                         OP_FLD_WR(REG_MC_CSC0, 8, 8, 0x0)

    //Field: MC_BAS0
    #define  FLD_LSB_MC_BAS0()                                    (9)
    #define  FLD_MSB_MC_BAS0()                                    (9)
    #define  FLD_MASK_MC_BAS0()                                   (FLD_MASK(9, 9))
    #define  FLD_MWD_MC_BAS0(v)                                   (FLD_MWD(9, 9, v))
    #define  FLD_MRD_MC_BAS0(v)                                   (FLD_MRD(9, 9, v))
    #define  SET_MC_BAS0(v)                                       OP_FLD_WR(REG_MC_CSC0, 9, 9, v)
    #define  GET_MC_BAS0()                                        OP_FLD_RD(REG_MC_CSC0, 9, 9)
    #define  RST_MC_BAS0()                                        OP_FLD_WR(REG_MC_CSC0, 9, 9, 0x0)

    //Field: MC_KRO0
    #define  FLD_LSB_MC_KRO0()                                    (10)
    #define  FLD_MSB_MC_KRO0()                                    (10)
    #define  FLD_MASK_MC_KRO0()                                   (FLD_MASK(10, 10))
    #define  FLD_MWD_MC_KRO0(v)                                   (FLD_MWD(10, 10, v))
    #define  FLD_MRD_MC_KRO0(v)                                   (FLD_MRD(10, 10, v))
    #define  SET_MC_KRO0(v)                                       OP_FLD_WR(REG_MC_CSC0, 10, 10, v)
    #define  GET_MC_KRO0()                                        OP_FLD_RD(REG_MC_CSC0, 10, 10)
    #define  RST_MC_KRO0()                                        OP_FLD_WR(REG_MC_CSC0, 10, 10, 0x0)

    //Field: MC_BA_NUM0
    #define  FLD_LSB_MC_BA_NUM0()                                 (12)
    #define  FLD_MSB_MC_BA_NUM0()                                 (12)
    #define  FLD_MASK_MC_BA_NUM0()                                (FLD_MASK(12, 12))
    #define  FLD_MWD_MC_BA_NUM0(v)                                (FLD_MWD(12, 12, v))
    #define  FLD_MRD_MC_BA_NUM0(v)                                (FLD_MRD(12, 12, v))
    #define  SET_MC_BA_NUM0(v)                                    OP_FLD_WR(REG_MC_CSC0, 12, 12, v)
    #define  GET_MC_BA_NUM0()                                     OP_FLD_RD(REG_MC_CSC0, 12, 12)
    #define  RST_MC_BA_NUM0()                                     OP_FLD_WR(REG_MC_CSC0, 12, 12, 0x0)

    //Field: MC_SEL0
    #define  FLD_LSB_MC_SEL0()                                    (16)
    #define  FLD_MSB_MC_SEL0()                                    (23)
    #define  FLD_MASK_MC_SEL0()                                   (FLD_MASK(16, 23))
    #define  FLD_MWD_MC_SEL0(v)                                   (FLD_MWD(16, 23, v))
    #define  FLD_MRD_MC_SEL0(v)                                   (FLD_MRD(16, 23, v))
    #define  SET_MC_SEL0(v)                                       OP_FLD_WR(REG_MC_CSC0, 16, 23, v)
    #define  GET_MC_SEL0()                                        OP_FLD_RD(REG_MC_CSC0, 16, 23)
    #define  RST_MC_SEL0()                                        OP_FLD_WR(REG_MC_CSC0, 16, 23, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_MC_CSC0(EN0,MEM_TYPE0,BW0,MS0,WP0,BAS0,KRO0,BA_NUM0,SEL0) \
                (WR_MC_CSC0( \
                  (FLD_MWD_MC_EN0(EN0))                                                | \
                  (FLD_MWD_MC_MEM_TYPE0(MEM_TYPE0))                                    | \
                  (FLD_MWD_MC_BW0(BW0))                                                | \
                  (FLD_MWD_MC_MS0(MS0))                                                | \
                  (FLD_MWD_MC_WP0(WP0))                                                | \
                  (FLD_MWD_MC_BAS0(BAS0))                                              | \
                  (FLD_MWD_MC_KRO0(KRO0))                                              | \
                  (FLD_MWD_MC_BA_NUM0(BA_NUM0))                                        | \
                  (FLD_MWD_MC_SEL0(SEL0))                                                \
                ))


#define  REG_MC_TMS0                                              (REG_BASE_MC + 0x14)
    //Read/Write-Register Using Address
    #define  RD_MC_TMS0()                                         (REG32(REG_MC_TMS0))
    #define  WR_MC_TMS0(v)                                        (REG32(REG_MC_TMS0) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_MC_TMS0()                                  (0xFFF83FF)  
    #define  REG_WMASK_MC_TMS0()                                  (0xFFF83FF)

    //Field: MC_BL0
    #define  FLD_LSB_MC_BL0()                                     (0)
    #define  FLD_MSB_MC_BL0()                                     (2)
    #define  FLD_MASK_MC_BL0()                                    (FLD_MASK(0, 2))
    #define  FLD_MWD_MC_BL0(v)                                    (FLD_MWD(0, 2, v))
    #define  FLD_MRD_MC_BL0(v)                                    (FLD_MRD(0, 2, v))
    #define  SET_MC_BL0(v)                                        OP_FLD_WR(REG_MC_TMS0, 0, 2, v)
    #define  GET_MC_BL0()                                         OP_FLD_RD(REG_MC_TMS0, 0, 2)
    #define  RST_MC_BL0()                                         OP_FLD_WR(REG_MC_TMS0, 0, 2, 0x0)

    //Field: MC_BT0
    #define  FLD_LSB_MC_BT0()                                     (3)
    #define  FLD_MSB_MC_BT0()                                     (3)
    #define  FLD_MASK_MC_BT0()                                    (FLD_MASK(3, 3))
    #define  FLD_MWD_MC_BT0(v)                                    (FLD_MWD(3, 3, v))
    #define  FLD_MRD_MC_BT0(v)                                    (FLD_MRD(3, 3, v))
    #define  SET_MC_BT0(v)                                        OP_FLD_WR(REG_MC_TMS0, 3, 3, v)
    #define  GET_MC_BT0()                                         OP_FLD_RD(REG_MC_TMS0, 3, 3)
    #define  RST_MC_BT0()                                         OP_FLD_WR(REG_MC_TMS0, 3, 3, 0x0)

    //Field: MC_CL0
    #define  FLD_LSB_MC_CL0()                                     (4)
    #define  FLD_MSB_MC_CL0()                                     (6)
    #define  FLD_MASK_MC_CL0()                                    (FLD_MASK(4, 6))
    #define  FLD_MWD_MC_CL0(v)                                    (FLD_MWD(4, 6, v))
    #define  FLD_MRD_MC_CL0(v)                                    (FLD_MRD(4, 6, v))
    #define  SET_MC_CL0(v)                                        OP_FLD_WR(REG_MC_TMS0, 4, 6, v)
    #define  GET_MC_CL0()                                         OP_FLD_RD(REG_MC_TMS0, 4, 6)
    #define  RST_MC_CL0()                                         OP_FLD_WR(REG_MC_TMS0, 4, 6, 0x0)

    //Field: MC_OP_MODE0
    #define  FLD_LSB_MC_OP_MODE0()                                (7)
    #define  FLD_MSB_MC_OP_MODE0()                                (8)
    #define  FLD_MASK_MC_OP_MODE0()                               (FLD_MASK(7, 8))
    #define  FLD_MWD_MC_OP_MODE0(v)                               (FLD_MWD(7, 8, v))
    #define  FLD_MRD_MC_OP_MODE0(v)                               (FLD_MRD(7, 8, v))
    #define  SET_MC_OP_MODE0(v)                                   OP_FLD_WR(REG_MC_TMS0, 7, 8, v)
    #define  GET_MC_OP_MODE0()                                    OP_FLD_RD(REG_MC_TMS0, 7, 8)
    #define  RST_MC_OP_MODE0()                                    OP_FLD_WR(REG_MC_TMS0, 7, 8, 0x0)

    //Field: MC_WBL0
    #define  FLD_LSB_MC_WBL0()                                    (9)
    #define  FLD_MSB_MC_WBL0()                                    (9)
    #define  FLD_MASK_MC_WBL0()                                   (FLD_MASK(9, 9))
    #define  FLD_MWD_MC_WBL0(v)                                   (FLD_MWD(9, 9, v))
    #define  FLD_MRD_MC_WBL0(v)                                   (FLD_MRD(9, 9, v))
    #define  SET_MC_WBL0(v)                                       OP_FLD_WR(REG_MC_TMS0, 9, 9, v)
    #define  GET_MC_WBL0()                                        OP_FLD_RD(REG_MC_TMS0, 9, 9)
    #define  RST_MC_WBL0()                                        OP_FLD_WR(REG_MC_TMS0, 9, 9, 0x0)

    //Field: MC_T_WR0
    #define  FLD_LSB_MC_T_WR0()                                   (15)
    #define  FLD_MSB_MC_T_WR0()                                   (16)
    #define  FLD_MASK_MC_T_WR0()                                  (FLD_MASK(15, 16))
    #define  FLD_MWD_MC_T_WR0(v)                                  (FLD_MWD(15, 16, v))
    #define  FLD_MRD_MC_T_WR0(v)                                  (FLD_MRD(15, 16, v))
    #define  SET_MC_T_WR0(v)                                      OP_FLD_WR(REG_MC_TMS0, 15, 16, v)
    #define  GET_MC_T_WR0()                                       OP_FLD_RD(REG_MC_TMS0, 15, 16)
    #define  RST_MC_T_WR0()                                       OP_FLD_WR(REG_MC_TMS0, 15, 16, 0x0)

    //Field: MC_T_RCD0
    #define  FLD_LSB_MC_T_RCD0()                                  (17)
    #define  FLD_MSB_MC_T_RCD0()                                  (19)
    #define  FLD_MASK_MC_T_RCD0()                                 (FLD_MASK(17, 19))
    #define  FLD_MWD_MC_T_RCD0(v)                                 (FLD_MWD(17, 19, v))
    #define  FLD_MRD_MC_T_RCD0(v)                                 (FLD_MRD(17, 19, v))
    #define  SET_MC_T_RCD0(v)                                     OP_FLD_WR(REG_MC_TMS0, 17, 19, v)
    #define  GET_MC_T_RCD0()                                      OP_FLD_RD(REG_MC_TMS0, 17, 19)
    #define  RST_MC_T_RCD0()                                      OP_FLD_WR(REG_MC_TMS0, 17, 19, 0x0)

    //Field: MC_T_RP0
    #define  FLD_LSB_MC_T_RP0()                                   (20)
    #define  FLD_MSB_MC_T_RP0()                                   (23)
    #define  FLD_MASK_MC_T_RP0()                                  (FLD_MASK(20, 23))
    #define  FLD_MWD_MC_T_RP0(v)                                  (FLD_MWD(20, 23, v))
    #define  FLD_MRD_MC_T_RP0(v)                                  (FLD_MRD(20, 23, v))
    #define  SET_MC_T_RP0(v)                                      OP_FLD_WR(REG_MC_TMS0, 20, 23, v)
    #define  GET_MC_T_RP0()                                       OP_FLD_RD(REG_MC_TMS0, 20, 23)
    #define  RST_MC_T_RP0()                                       OP_FLD_WR(REG_MC_TMS0, 20, 23, 0x0)

    //Field: MC_T_RFC0
    #define  FLD_LSB_MC_T_RFC0()                                  (24)
    #define  FLD_MSB_MC_T_RFC0()                                  (27)
    #define  FLD_MASK_MC_T_RFC0()                                 (FLD_MASK(24, 27))
    #define  FLD_MWD_MC_T_RFC0(v)                                 (FLD_MWD(24, 27, v))
    #define  FLD_MRD_MC_T_RFC0(v)                                 (FLD_MRD(24, 27, v))
    #define  SET_MC_T_RFC0(v)                                     OP_FLD_WR(REG_MC_TMS0, 24, 27, v)
    #define  GET_MC_T_RFC0()                                      OP_FLD_RD(REG_MC_TMS0, 24, 27)
    #define  RST_MC_T_RFC0()                                      OP_FLD_WR(REG_MC_TMS0, 24, 27, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_MC_TMS0(BL0,BT0,CL0,OP_MODE0,WBL0,T_WR0,T_RCD0,T_RP0,T_RFC0) \
                (WR_MC_TMS0( \
                  (FLD_MWD_MC_BL0(BL0))                                                | \
                  (FLD_MWD_MC_BT0(BT0))                                                | \
                  (FLD_MWD_MC_CL0(CL0))                                                | \
                  (FLD_MWD_MC_OP_MODE0(OP_MODE0))                                      | \
                  (FLD_MWD_MC_WBL0(WBL0))                                              | \
                  (FLD_MWD_MC_T_WR0(T_WR0))                                            | \
                  (FLD_MWD_MC_T_RCD0(T_RCD0))                                          | \
                  (FLD_MWD_MC_T_RP0(T_RP0))                                            | \
                  (FLD_MWD_MC_T_RFC0(T_RFC0))                                            \
                ))


#define  REG_MC_CSC1                                              (REG_BASE_MC + 0x18)
    //Read/Write-Register Using Address
    #define  RD_MC_CSC1()                                         (REG32(REG_MC_CSC1))
    #define  WR_MC_CSC1(v)                                        (REG32(REG_MC_CSC1) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_MC_CSC1()                                  (0xFF37FF)  
    #define  REG_WMASK_MC_CSC1()                                  (0xFF37FF)

    //Field: MC_EN1
    #define  FLD_LSB_MC_EN1()                                     (0)
    #define  FLD_MSB_MC_EN1()                                     (0)
    #define  FLD_MASK_MC_EN1()                                    (FLD_MASK(0, 0))
    #define  FLD_MWD_MC_EN1(v)                                    (FLD_MWD(0, 0, v))
    #define  FLD_MRD_MC_EN1(v)                                    (FLD_MRD(0, 0, v))
    #define  SET_MC_EN1(v)                                        OP_FLD_WR(REG_MC_CSC1, 0, 0, v)
    #define  GET_MC_EN1()                                         OP_FLD_RD(REG_MC_CSC1, 0, 0)
    #define  RST_MC_EN1()                                         OP_FLD_WR(REG_MC_CSC1, 0, 0, 0x0)

    //Field: MC_MEM_TYPE1
    #define  FLD_LSB_MC_MEM_TYPE1()                               (1)
    #define  FLD_MSB_MC_MEM_TYPE1()                               (3)
    #define  FLD_MASK_MC_MEM_TYPE1()                              (FLD_MASK(1, 3))
    #define  FLD_MWD_MC_MEM_TYPE1(v)                              (FLD_MWD(1, 3, v))
    #define  FLD_MRD_MC_MEM_TYPE1(v)                              (FLD_MRD(1, 3, v))
    #define  SET_MC_MEM_TYPE1(v)                                  OP_FLD_WR(REG_MC_CSC1, 1, 3, v)
    #define  GET_MC_MEM_TYPE1()                                   OP_FLD_RD(REG_MC_CSC1, 1, 3)
    #define  RST_MC_MEM_TYPE1()                                   OP_FLD_WR(REG_MC_CSC1, 1, 3, 0x0)

    //Field: MC_BW1
    #define  FLD_LSB_MC_BW1()                                     (4)
    #define  FLD_MSB_MC_BW1()                                     (5)
    #define  FLD_MASK_MC_BW1()                                    (FLD_MASK(4, 5))
    #define  FLD_MWD_MC_BW1(v)                                    (FLD_MWD(4, 5, v))
    #define  FLD_MRD_MC_BW1(v)                                    (FLD_MRD(4, 5, v))
    #define  SET_MC_BW1(v)                                        OP_FLD_WR(REG_MC_CSC1, 4, 5, v)
    #define  GET_MC_BW1()                                         OP_FLD_RD(REG_MC_CSC1, 4, 5)
    #define  RST_MC_BW1()                                         OP_FLD_WR(REG_MC_CSC1, 4, 5, 0x0)

    //Field: MC_MS1
    #define  FLD_LSB_MC_MS1()                                     (6)
    #define  FLD_MSB_MC_MS1()                                     (7)
    #define  FLD_MASK_MC_MS1()                                    (FLD_MASK(6, 7))
    #define  FLD_MWD_MC_MS1(v)                                    (FLD_MWD(6, 7, v))
    #define  FLD_MRD_MC_MS1(v)                                    (FLD_MRD(6, 7, v))
    #define  SET_MC_MS1(v)                                        OP_FLD_WR(REG_MC_CSC1, 6, 7, v)
    #define  GET_MC_MS1()                                         OP_FLD_RD(REG_MC_CSC1, 6, 7)
    #define  RST_MC_MS1()                                         OP_FLD_WR(REG_MC_CSC1, 6, 7, 0x0)

    //Field: MC_WP1
    #define  FLD_LSB_MC_WP1()                                     (8)
    #define  FLD_MSB_MC_WP1()                                     (8)
    #define  FLD_MASK_MC_WP1()                                    (FLD_MASK(8, 8))
    #define  FLD_MWD_MC_WP1(v)                                    (FLD_MWD(8, 8, v))
    #define  FLD_MRD_MC_WP1(v)                                    (FLD_MRD(8, 8, v))
    #define  SET_MC_WP1(v)                                        OP_FLD_WR(REG_MC_CSC1, 8, 8, v)
    #define  GET_MC_WP1()                                         OP_FLD_RD(REG_MC_CSC1, 8, 8)
    #define  RST_MC_WP1()                                         OP_FLD_WR(REG_MC_CSC1, 8, 8, 0x0)

    //Field: MC_BAS1
    #define  FLD_LSB_MC_BAS1()                                    (9)
    #define  FLD_MSB_MC_BAS1()                                    (9)
    #define  FLD_MASK_MC_BAS1()                                   (FLD_MASK(9, 9))
    #define  FLD_MWD_MC_BAS1(v)                                   (FLD_MWD(9, 9, v))
    #define  FLD_MRD_MC_BAS1(v)                                   (FLD_MRD(9, 9, v))
    #define  SET_MC_BAS1(v)                                       OP_FLD_WR(REG_MC_CSC1, 9, 9, v)
    #define  GET_MC_BAS1()                                        OP_FLD_RD(REG_MC_CSC1, 9, 9)
    #define  RST_MC_BAS1()                                        OP_FLD_WR(REG_MC_CSC1, 9, 9, 0x0)

    //Field: MC_KRO1
    #define  FLD_LSB_MC_KRO1()                                    (10)
    #define  FLD_MSB_MC_KRO1()                                    (10)
    #define  FLD_MASK_MC_KRO1()                                   (FLD_MASK(10, 10))
    #define  FLD_MWD_MC_KRO1(v)                                   (FLD_MWD(10, 10, v))
    #define  FLD_MRD_MC_KRO1(v)                                   (FLD_MRD(10, 10, v))
    #define  SET_MC_KRO1(v)                                       OP_FLD_WR(REG_MC_CSC1, 10, 10, v)
    #define  GET_MC_KRO1()                                        OP_FLD_RD(REG_MC_CSC1, 10, 10)
    #define  RST_MC_KRO1()                                        OP_FLD_WR(REG_MC_CSC1, 10, 10, 0x0)

    //Field: MC_BA_NUM1
    #define  FLD_LSB_MC_BA_NUM1()                                 (12)
    #define  FLD_MSB_MC_BA_NUM1()                                 (12)
    #define  FLD_MASK_MC_BA_NUM1()                                (FLD_MASK(12, 12))
    #define  FLD_MWD_MC_BA_NUM1(v)                                (FLD_MWD(12, 12, v))
    #define  FLD_MRD_MC_BA_NUM1(v)                                (FLD_MRD(12, 12, v))
    #define  SET_MC_BA_NUM1(v)                                    OP_FLD_WR(REG_MC_CSC1, 12, 12, v)
    #define  GET_MC_BA_NUM1()                                     OP_FLD_RD(REG_MC_CSC1, 12, 12)
    #define  RST_MC_BA_NUM1()                                     OP_FLD_WR(REG_MC_CSC1, 12, 12, 0x0)

    //Field: MC_TBW
    #define  FLD_LSB_MC_TBW()                                     (13)
    #define  FLD_MSB_MC_TBW()                                     (13)
    #define  FLD_MASK_MC_TBW()                                    (FLD_MASK(13, 13))
    #define  FLD_MWD_MC_TBW(v)                                    (FLD_MWD(13, 13, v))
    #define  FLD_MRD_MC_TBW(v)                                    (FLD_MRD(13, 13, v))
    #define  SET_MC_TBW(v)                                        OP_FLD_WR(REG_MC_CSC1, 13, 13, v)
    #define  GET_MC_TBW()                                         OP_FLD_RD(REG_MC_CSC1, 13, 13)
    #define  RST_MC_TBW()                                         OP_FLD_WR(REG_MC_CSC1, 13, 13, 0x0)

    //Field: MC_SEL1
    #define  FLD_LSB_MC_SEL1()                                    (16)
    #define  FLD_MSB_MC_SEL1()                                    (23)
    #define  FLD_MASK_MC_SEL1()                                   (FLD_MASK(16, 23))
    #define  FLD_MWD_MC_SEL1(v)                                   (FLD_MWD(16, 23, v))
    #define  FLD_MRD_MC_SEL1(v)                                   (FLD_MRD(16, 23, v))
    #define  SET_MC_SEL1(v)                                       OP_FLD_WR(REG_MC_CSC1, 16, 23, v)
    #define  GET_MC_SEL1()                                        OP_FLD_RD(REG_MC_CSC1, 16, 23)
    #define  RST_MC_SEL1()                                        OP_FLD_WR(REG_MC_CSC1, 16, 23, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_MC_CSC1(EN1,MEM_TYPE1,BW1,MS1,WP1,BAS1,KRO1,BA_NUM1,TBW,SEL1) \
                (WR_MC_CSC1( \
                  (FLD_MWD_MC_EN1(EN1))                                                | \
                  (FLD_MWD_MC_MEM_TYPE1(MEM_TYPE1))                                    | \
                  (FLD_MWD_MC_BW1(BW1))                                                | \
                  (FLD_MWD_MC_MS1(MS1))                                                | \
                  (FLD_MWD_MC_WP1(WP1))                                                | \
                  (FLD_MWD_MC_BAS1(BAS1))                                              | \
                  (FLD_MWD_MC_KRO1(KRO1))                                              | \
                  (FLD_MWD_MC_BA_NUM1(BA_NUM1))                                        | \
                  (FLD_MWD_MC_TBW(TBW))                                                | \
                  (FLD_MWD_MC_SEL1(SEL1))                                                \
                ))


#define  REG_MC_TMS1                                              (REG_BASE_MC + 0x1c)
    //Read/Write-Register Using Address
    #define  RD_MC_TMS1()                                         (REG32(REG_MC_TMS1))
    #define  WR_MC_TMS1(v)                                        (REG32(REG_MC_TMS1) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_MC_TMS1()                                  (0xFFF83FF)  
    #define  REG_WMASK_MC_TMS1()                                  (0xFFF83FF)

    //Field: MC_BL1
    #define  FLD_LSB_MC_BL1()                                     (0)
    #define  FLD_MSB_MC_BL1()                                     (2)
    #define  FLD_MASK_MC_BL1()                                    (FLD_MASK(0, 2))
    #define  FLD_MWD_MC_BL1(v)                                    (FLD_MWD(0, 2, v))
    #define  FLD_MRD_MC_BL1(v)                                    (FLD_MRD(0, 2, v))
    #define  SET_MC_BL1(v)                                        OP_FLD_WR(REG_MC_TMS1, 0, 2, v)
    #define  GET_MC_BL1()                                         OP_FLD_RD(REG_MC_TMS1, 0, 2)
    #define  RST_MC_BL1()                                         OP_FLD_WR(REG_MC_TMS1, 0, 2, 0x0)

    //Field: MC_BT1
    #define  FLD_LSB_MC_BT1()                                     (3)
    #define  FLD_MSB_MC_BT1()                                     (3)
    #define  FLD_MASK_MC_BT1()                                    (FLD_MASK(3, 3))
    #define  FLD_MWD_MC_BT1(v)                                    (FLD_MWD(3, 3, v))
    #define  FLD_MRD_MC_BT1(v)                                    (FLD_MRD(3, 3, v))
    #define  SET_MC_BT1(v)                                        OP_FLD_WR(REG_MC_TMS1, 3, 3, v)
    #define  GET_MC_BT1()                                         OP_FLD_RD(REG_MC_TMS1, 3, 3)
    #define  RST_MC_BT1()                                         OP_FLD_WR(REG_MC_TMS1, 3, 3, 0x0)

    //Field: MC_CL1
    #define  FLD_LSB_MC_CL1()                                     (4)
    #define  FLD_MSB_MC_CL1()                                     (6)
    #define  FLD_MASK_MC_CL1()                                    (FLD_MASK(4, 6))
    #define  FLD_MWD_MC_CL1(v)                                    (FLD_MWD(4, 6, v))
    #define  FLD_MRD_MC_CL1(v)                                    (FLD_MRD(4, 6, v))
    #define  SET_MC_CL1(v)                                        OP_FLD_WR(REG_MC_TMS1, 4, 6, v)
    #define  GET_MC_CL1()                                         OP_FLD_RD(REG_MC_TMS1, 4, 6)
    #define  RST_MC_CL1()                                         OP_FLD_WR(REG_MC_TMS1, 4, 6, 0x0)

    //Field: MC_OP_MODE1
    #define  FLD_LSB_MC_OP_MODE1()                                (7)
    #define  FLD_MSB_MC_OP_MODE1()                                (8)
    #define  FLD_MASK_MC_OP_MODE1()                               (FLD_MASK(7, 8))
    #define  FLD_MWD_MC_OP_MODE1(v)                               (FLD_MWD(7, 8, v))
    #define  FLD_MRD_MC_OP_MODE1(v)                               (FLD_MRD(7, 8, v))
    #define  SET_MC_OP_MODE1(v)                                   OP_FLD_WR(REG_MC_TMS1, 7, 8, v)
    #define  GET_MC_OP_MODE1()                                    OP_FLD_RD(REG_MC_TMS1, 7, 8)
    #define  RST_MC_OP_MODE1()                                    OP_FLD_WR(REG_MC_TMS1, 7, 8, 0x0)

    //Field: MC_WBL1
    #define  FLD_LSB_MC_WBL1()                                    (9)
    #define  FLD_MSB_MC_WBL1()                                    (9)
    #define  FLD_MASK_MC_WBL1()                                   (FLD_MASK(9, 9))
    #define  FLD_MWD_MC_WBL1(v)                                   (FLD_MWD(9, 9, v))
    #define  FLD_MRD_MC_WBL1(v)                                   (FLD_MRD(9, 9, v))
    #define  SET_MC_WBL1(v)                                       OP_FLD_WR(REG_MC_TMS1, 9, 9, v)
    #define  GET_MC_WBL1()                                        OP_FLD_RD(REG_MC_TMS1, 9, 9)
    #define  RST_MC_WBL1()                                        OP_FLD_WR(REG_MC_TMS1, 9, 9, 0x0)

    //Field: MC_T_WR1
    #define  FLD_LSB_MC_T_WR1()                                   (15)
    #define  FLD_MSB_MC_T_WR1()                                   (16)
    #define  FLD_MASK_MC_T_WR1()                                  (FLD_MASK(15, 16))
    #define  FLD_MWD_MC_T_WR1(v)                                  (FLD_MWD(15, 16, v))
    #define  FLD_MRD_MC_T_WR1(v)                                  (FLD_MRD(15, 16, v))
    #define  SET_MC_T_WR1(v)                                      OP_FLD_WR(REG_MC_TMS1, 15, 16, v)
    #define  GET_MC_T_WR1()                                       OP_FLD_RD(REG_MC_TMS1, 15, 16)
    #define  RST_MC_T_WR1()                                       OP_FLD_WR(REG_MC_TMS1, 15, 16, 0x0)

    //Field: MC_T_RCD1
    #define  FLD_LSB_MC_T_RCD1()                                  (17)
    #define  FLD_MSB_MC_T_RCD1()                                  (19)
    #define  FLD_MASK_MC_T_RCD1()                                 (FLD_MASK(17, 19))
    #define  FLD_MWD_MC_T_RCD1(v)                                 (FLD_MWD(17, 19, v))
    #define  FLD_MRD_MC_T_RCD1(v)                                 (FLD_MRD(17, 19, v))
    #define  SET_MC_T_RCD1(v)                                     OP_FLD_WR(REG_MC_TMS1, 17, 19, v)
    #define  GET_MC_T_RCD1()                                      OP_FLD_RD(REG_MC_TMS1, 17, 19)
    #define  RST_MC_T_RCD1()                                      OP_FLD_WR(REG_MC_TMS1, 17, 19, 0x0)

    //Field: MC_T_RP1
    #define  FLD_LSB_MC_T_RP1()                                   (20)
    #define  FLD_MSB_MC_T_RP1()                                   (23)
    #define  FLD_MASK_MC_T_RP1()                                  (FLD_MASK(20, 23))
    #define  FLD_MWD_MC_T_RP1(v)                                  (FLD_MWD(20, 23, v))
    #define  FLD_MRD_MC_T_RP1(v)                                  (FLD_MRD(20, 23, v))
    #define  SET_MC_T_RP1(v)                                      OP_FLD_WR(REG_MC_TMS1, 20, 23, v)
    #define  GET_MC_T_RP1()                                       OP_FLD_RD(REG_MC_TMS1, 20, 23)
    #define  RST_MC_T_RP1()                                       OP_FLD_WR(REG_MC_TMS1, 20, 23, 0x0)

    //Field: MC_T_RFC1
    #define  FLD_LSB_MC_T_RFC1()                                  (24)
    #define  FLD_MSB_MC_T_RFC1()                                  (27)
    #define  FLD_MASK_MC_T_RFC1()                                 (FLD_MASK(24, 27))
    #define  FLD_MWD_MC_T_RFC1(v)                                 (FLD_MWD(24, 27, v))
    #define  FLD_MRD_MC_T_RFC1(v)                                 (FLD_MRD(24, 27, v))
    #define  SET_MC_T_RFC1(v)                                     OP_FLD_WR(REG_MC_TMS1, 24, 27, v)
    #define  GET_MC_T_RFC1()                                      OP_FLD_RD(REG_MC_TMS1, 24, 27)
    #define  RST_MC_T_RFC1()                                      OP_FLD_WR(REG_MC_TMS1, 24, 27, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_MC_TMS1(BL1,BT1,CL1,OP_MODE1,WBL1,T_WR1,T_RCD1,T_RP1,T_RFC1) \
                (WR_MC_TMS1( \
                  (FLD_MWD_MC_BL1(BL1))                                                | \
                  (FLD_MWD_MC_BT1(BT1))                                                | \
                  (FLD_MWD_MC_CL1(CL1))                                                | \
                  (FLD_MWD_MC_OP_MODE1(OP_MODE1))                                      | \
                  (FLD_MWD_MC_WBL1(WBL1))                                              | \
                  (FLD_MWD_MC_T_WR1(T_WR1))                                            | \
                  (FLD_MWD_MC_T_RCD1(T_RCD1))                                          | \
                  (FLD_MWD_MC_T_RP1(T_RP1))                                            | \
                  (FLD_MWD_MC_T_RFC1(T_RFC1))                                            \
                ))


#define  REG_MC_DLL_DBG_0                                         (REG_BASE_MC + 0x50)
    //Read/Write-Register Using Address
    #define  RD_MC_DLL_DBG_0()                                    (REG32(REG_MC_DLL_DBG_0))
    #define  WR_MC_DLL_DBG_0(v)                                   (REG32(REG_MC_DLL_DBG_0) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_MC_DLL_DBG_0()                             (0x3FFFF)  
    #define  REG_WMASK_MC_DLL_DBG_0()                             (0x3FFFF)

    //Field: MC_DLL_CFG_CCNT
    #define  FLD_LSB_MC_DLL_CFG_CCNT()                            (0)
    #define  FLD_MSB_MC_DLL_CFG_CCNT()                            (1)
    #define  FLD_MASK_MC_DLL_CFG_CCNT()                           (FLD_MASK(0, 1))
    #define  FLD_MWD_MC_DLL_CFG_CCNT(v)                           (FLD_MWD(0, 1, v))
    #define  FLD_MRD_MC_DLL_CFG_CCNT(v)                           (FLD_MRD(0, 1, v))
    #define  SET_MC_DLL_CFG_CCNT(v)                               OP_FLD_WR(REG_MC_DLL_DBG_0, 0, 1, v)
    #define  GET_MC_DLL_CFG_CCNT()                                OP_FLD_RD(REG_MC_DLL_DBG_0, 0, 1)
    #define  RST_MC_DLL_CFG_CCNT()                                OP_FLD_WR(REG_MC_DLL_DBG_0, 0, 1, 0x0)

    //Field: MC_DLL_CFG_FCNT
    #define  FLD_LSB_MC_DLL_CFG_FCNT()                            (2)
    #define  FLD_MSB_MC_DLL_CFG_FCNT()                            (9)
    #define  FLD_MASK_MC_DLL_CFG_FCNT()                           (FLD_MASK(2, 9))
    #define  FLD_MWD_MC_DLL_CFG_FCNT(v)                           (FLD_MWD(2, 9, v))
    #define  FLD_MRD_MC_DLL_CFG_FCNT(v)                           (FLD_MRD(2, 9, v))
    #define  SET_MC_DLL_CFG_FCNT(v)                               OP_FLD_WR(REG_MC_DLL_DBG_0, 2, 9, v)
    #define  GET_MC_DLL_CFG_FCNT()                                OP_FLD_RD(REG_MC_DLL_DBG_0, 2, 9)
    #define  RST_MC_DLL_CFG_FCNT()                                OP_FLD_WR(REG_MC_DLL_DBG_0, 2, 9, 0x0)

    //Field: MC_DLL_CFG_FCOMP_CNT
    #define  FLD_LSB_MC_DLL_CFG_FCOMP_CNT()                       (10)
    #define  FLD_MSB_MC_DLL_CFG_FCOMP_CNT()                       (13)
    #define  FLD_MASK_MC_DLL_CFG_FCOMP_CNT()                      (FLD_MASK(10, 13))
    #define  FLD_MWD_MC_DLL_CFG_FCOMP_CNT(v)                      (FLD_MWD(10, 13, v))
    #define  FLD_MRD_MC_DLL_CFG_FCOMP_CNT(v)                      (FLD_MRD(10, 13, v))
    #define  SET_MC_DLL_CFG_FCOMP_CNT(v)                          OP_FLD_WR(REG_MC_DLL_DBG_0, 10, 13, v)
    #define  GET_MC_DLL_CFG_FCOMP_CNT()                           OP_FLD_RD(REG_MC_DLL_DBG_0, 10, 13)
    #define  RST_MC_DLL_CFG_FCOMP_CNT()                           OP_FLD_WR(REG_MC_DLL_DBG_0, 10, 13, 0x0)

    //Field: MC_DLL_CFG_OCOMP_CNT
    #define  FLD_LSB_MC_DLL_CFG_OCOMP_CNT()                       (14)
    #define  FLD_MSB_MC_DLL_CFG_OCOMP_CNT()                       (17)
    #define  FLD_MASK_MC_DLL_CFG_OCOMP_CNT()                      (FLD_MASK(14, 17))
    #define  FLD_MWD_MC_DLL_CFG_OCOMP_CNT(v)                      (FLD_MWD(14, 17, v))
    #define  FLD_MRD_MC_DLL_CFG_OCOMP_CNT(v)                      (FLD_MRD(14, 17, v))
    #define  SET_MC_DLL_CFG_OCOMP_CNT(v)                          OP_FLD_WR(REG_MC_DLL_DBG_0, 14, 17, v)
    #define  GET_MC_DLL_CFG_OCOMP_CNT()                           OP_FLD_RD(REG_MC_DLL_DBG_0, 14, 17)
    #define  RST_MC_DLL_CFG_OCOMP_CNT()                           OP_FLD_WR(REG_MC_DLL_DBG_0, 14, 17, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_MC_DLL_DBG_0(DLL_CFG_CCNT,DLL_CFG_FCNT,DLL_CFG_FCOMP_CNT,DLL_CFG_OCOMP_CNT) \
                (WR_MC_DLL_DBG_0( \
                  (FLD_MWD_MC_DLL_CFG_CCNT(DLL_CFG_CCNT))                              | \
                  (FLD_MWD_MC_DLL_CFG_FCNT(DLL_CFG_FCNT))                              | \
                  (FLD_MWD_MC_DLL_CFG_FCOMP_CNT(DLL_CFG_FCOMP_CNT))                    | \
                  (FLD_MWD_MC_DLL_CFG_OCOMP_CNT(DLL_CFG_OCOMP_CNT))                      \
                ))


#define  REG_MC_DLL_DBG_1                                         (REG_BASE_MC + 0x54)
    //Read/Write-Register Using Address
    #define  RD_MC_DLL_DBG_1()                                    (REG32(REG_MC_DLL_DBG_1))
    #define  WR_MC_DLL_DBG_1(v)                                   (REG32(REG_MC_DLL_DBG_1) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_MC_DLL_DBG_1()                             (0x30003)  
    #define  REG_WMASK_MC_DLL_DBG_1()                             (0x3)

    //Field: MC_DLL_CFG_MODE
    #define  FLD_LSB_MC_DLL_CFG_MODE()                            (0)
    #define  FLD_MSB_MC_DLL_CFG_MODE()                            (0)
    #define  FLD_MASK_MC_DLL_CFG_MODE()                           (FLD_MASK(0, 0))
    #define  FLD_MWD_MC_DLL_CFG_MODE(v)                           (FLD_MWD(0, 0, v))
    #define  FLD_MRD_MC_DLL_CFG_MODE(v)                           (FLD_MRD(0, 0, v))
    #define  SET_MC_DLL_CFG_MODE(v)                               OP_FLD_WR(REG_MC_DLL_DBG_1, 0, 0, v)
    #define  GET_MC_DLL_CFG_MODE()                                OP_FLD_RD(REG_MC_DLL_DBG_1, 0, 0)
    #define  RST_MC_DLL_CFG_MODE()                                OP_FLD_WR(REG_MC_DLL_DBG_1, 0, 0, 0x0)

    //Field: MC_DLL_DIG_MODE
    #define  FLD_LSB_MC_DLL_DIG_MODE()                            (1)
    #define  FLD_MSB_MC_DLL_DIG_MODE()                            (1)
    #define  FLD_MASK_MC_DLL_DIG_MODE()                           (FLD_MASK(1, 1))
    #define  FLD_MWD_MC_DLL_DIG_MODE(v)                           (FLD_MWD(1, 1, v))
    #define  FLD_MRD_MC_DLL_DIG_MODE(v)                           (FLD_MRD(1, 1, v))
    #define  SET_MC_DLL_DIG_MODE(v)                               OP_FLD_WR(REG_MC_DLL_DBG_1, 1, 1, v)
    #define  GET_MC_DLL_DIG_MODE()                                OP_FLD_RD(REG_MC_DLL_DBG_1, 1, 1)
    #define  RST_MC_DLL_DIG_MODE()                                OP_FLD_WR(REG_MC_DLL_DBG_1, 1, 1, 0x0)

    //Field: MC_DLL_CFG_ST
    #define  FLD_LSB_MC_DLL_CFG_ST()                              (16)
    #define  FLD_MSB_MC_DLL_CFG_ST()                              (17)
    #define  FLD_MASK_MC_DLL_CFG_ST()                             (FLD_MASK(16, 17))
    #define  FLD_MWD_MC_DLL_CFG_ST(v)                             (FLD_MWD(16, 17, v))
    #define  FLD_MRD_MC_DLL_CFG_ST(v)                             (FLD_MRD(16, 17, v))
    #define  GET_MC_DLL_CFG_ST()                                  OP_FLD_RD(REG_MC_DLL_DBG_1, 16, 17)

    //Write-Register Using Field-Name
    #define  WRF_MC_DLL_DBG_1(DLL_CFG_MODE,DLL_DIG_MODE,DLL_CFG_ST) \
                (WR_MC_DLL_DBG_1( \
                  (FLD_MWD_MC_DLL_CFG_MODE(DLL_CFG_MODE))                              | \
                  (FLD_MWD_MC_DLL_DIG_MODE(DLL_DIG_MODE))                                \
                ))


#define  REG_MC_REG_BUS_CLK_CFG                                   (REG_BASE_MC + 0x58)
    //Read/Write-Register Using Address
    #define  RD_MC_REG_BUS_CLK_CFG()                              (REG32(REG_MC_REG_BUS_CLK_CFG))
    #define  WR_MC_REG_BUS_CLK_CFG(v)                             (REG32(REG_MC_REG_BUS_CLK_CFG) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_MC_REG_BUS_CLK_CFG()                       (0x1)  
    #define  REG_WMASK_MC_REG_BUS_CLK_CFG()                       (0x1)

    //Field: MC_REG_BUS_CLK_GATE_MODE
    #define  FLD_LSB_MC_REG_BUS_CLK_GATE_MODE()                   (0)
    #define  FLD_MSB_MC_REG_BUS_CLK_GATE_MODE()                   (0)
    #define  FLD_MASK_MC_REG_BUS_CLK_GATE_MODE()                  (FLD_MASK(0, 0))
    #define  FLD_MWD_MC_REG_BUS_CLK_GATE_MODE(v)                  (FLD_MWD(0, 0, v))
    #define  FLD_MRD_MC_REG_BUS_CLK_GATE_MODE(v)                  (FLD_MRD(0, 0, v))
    #define  SET_MC_REG_BUS_CLK_GATE_MODE(v)                      OP_FLD_WR_EXC(REG_MC_REG_BUS_CLK_CFG, 0, 0, v)
    #define  GET_MC_REG_BUS_CLK_GATE_MODE()                       OP_FLD_RD(REG_MC_REG_BUS_CLK_CFG, 0, 0)
    #define  RST_MC_REG_BUS_CLK_GATE_MODE()                       OP_FLD_WR_EXC(REG_MC_REG_BUS_CLK_CFG, 0, 0, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_MC_REG_BUS_CLK_CFG(REG_BUS_CLK_GATE_MODE) \
                (WR_MC_REG_BUS_CLK_CFG( \
                  (FLD_MWD_MC_REG_BUS_CLK_GATE_MODE(REG_BUS_CLK_GATE_MODE))              \
                ))



#endif /*__LIGHTELF_MC_REG_H__*/
// vim:ft=c:nowrap:noma
