/*
 * Copyright (c) 2006-2015 Triductor Technology, Inc.
 *           All Rights Reserved Worldwide
 *
 * Filename: lightelf_sdma_reg.h
 * Author  : $Author: Gqzhang $
 * Date    : Jun/01/2015
 * Version : $Revision: 3179 $
 * Purpose : Describe all the available registers for SDMA of LIGHTELF.
             This file is automatically generated by Register Parser.
 */

#ifndef __LIGHTELF_SDMA_REG_H__
#define __LIGHTELF_SDMA_REG_H__

#ifndef REG32
    #define REG32(x)                    (*(volatile unsigned int *)(x))
#endif

#ifndef _REG_FLD_OP_
    #define _REG_FLD_OP_

    // Register Field Mask
    #define FLD_MASK(s,e)              ((0xffffffff >> (31-(e)+(s))) << (s))

    // Register Field Mask Write-Data
    // s -- Start of Bit  e -- End   of Bit
    // v -- Value
    #define FLD_MWD(s,e,v)              (((v) << (s)) & FLD_MASK((s),(e)))

    // Register Field Mask Read-Data
    // s -- Start of Bit  e -- End   of Bit
    // v -- Value
    #define FLD_MRD(s,e,v)              (((v) & FLD_MASK((s),(e))) >> (s))

    // Register Field Write operation
    // a -- Address   s -- Start of Bit
    // v -- Value     e -- End   of Bit
    #define OP_FLD_WR(a,s,e,v)          (REG32((a)) = (((v) << (s)) & FLD_MASK((s),(e))) | (REG32((a)) & ~FLD_MASK((s),(e))))
    #define OP_FLD_WR_EXC(a,s,e,v)      (REG32((a)) = (((v) << (s)) & FLD_MASK((s),(e))))

    // Register Field Read operation
    #define OP_FLD_RD(a,s,e)            ((REG32((a)) & FLD_MASK((s),(e))) >> (s))

#endif

//Address Offset for multi-instance mode only
#ifndef  REG_OFFSET_SDMA
    #define  REG_OFFSET_SDMA  (0x100)
#endif

// Base address
#ifndef REG_BASE_SDMA
    #define  REG_BASE_SDMA(idx)    (0xf0100000 + idx * REG_OFFSET_SDMA)
#endif



//------------------------------------
// Channel Address Registers
//------------------------------------
#define  REG_SDMA_SA(idx)                                         (REG_BASE_SDMA(idx) + 0x000)
    //Read/Write-Register Using Address
    #define  RD_SDMA_SA(idx)                                      (REG32(REG_SDMA_SA(idx)))
    #define  WR_SDMA_SA(v, idx)                                   (REG32(REG_SDMA_SA(idx)) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_SDMA_SA()                                  (0xFFFFFFFF)  
    #define  REG_WMASK_SDMA_SA()                                  (0xFFFFFFFF)

    //Field: SDMA_SA
    #define  FLD_LSB_SDMA_SA()                                    (0)
    #define  FLD_MSB_SDMA_SA()                                    (31)
    #define  FLD_MASK_SDMA_SA()                                   (FLD_MASK(0, 31))
    #define  FLD_MWD_SDMA_SA(v)                                   (FLD_MWD(0, 31, v))
    #define  FLD_MRD_SDMA_SA(v)                                   (FLD_MRD(0, 31, v))
    #define  SET_SDMA_SA(v, idx)                                  OP_FLD_WR_EXC(REG_SDMA_SA(idx), 0, 31, v)
    #define  GET_SDMA_SA(idx)                                     OP_FLD_RD(REG_SDMA_SA(idx), 0, 31)
    #define  GET_SDMA_SA_CUR(idx)                                 OP_FLD_RD(REG_SDMA_SA(idx), 0, 31)
    #define  RST_SDMA_SA(idx)                                     OP_FLD_WR_EXC(REG_SDMA_SA(idx), 0, 31, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_SDMA_SA(SA,idx) \
                (WR_SDMA_SA( \
                  (FLD_MWD_SDMA_SA(SA))                                                  \
                 ,idx \
                ))


#define  REG_SDMA_DA(idx)                                         (REG_BASE_SDMA(idx) + 0x004)
    //Read/Write-Register Using Address
    #define  RD_SDMA_DA(idx)                                      (REG32(REG_SDMA_DA(idx)))
    #define  WR_SDMA_DA(v, idx)                                   (REG32(REG_SDMA_DA(idx)) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_SDMA_DA()                                  (0xFFFFFFFF)  
    #define  REG_WMASK_SDMA_DA()                                  (0xFFFFFFFF)

    //Field: SDMA_DA
    #define  FLD_LSB_SDMA_DA()                                    (0)
    #define  FLD_MSB_SDMA_DA()                                    (31)
    #define  FLD_MASK_SDMA_DA()                                   (FLD_MASK(0, 31))
    #define  FLD_MWD_SDMA_DA(v)                                   (FLD_MWD(0, 31, v))
    #define  FLD_MRD_SDMA_DA(v)                                   (FLD_MRD(0, 31, v))
    #define  SET_SDMA_DA(v, idx)                                  OP_FLD_WR_EXC(REG_SDMA_DA(idx), 0, 31, v)
    #define  GET_SDMA_DA(idx)                                     OP_FLD_RD(REG_SDMA_DA(idx), 0, 31)
    #define  GET_SDMA_DA_CUR(idx)                                 OP_FLD_RD(REG_SDMA_DA(idx), 0, 31)
    #define  RST_SDMA_DA(idx)                                     OP_FLD_WR_EXC(REG_SDMA_DA(idx), 0, 31, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_SDMA_DA(DA,idx) \
                (WR_SDMA_DA( \
                  (FLD_MWD_SDMA_DA(DA))                                                  \
                 ,idx \
                ))


#define  REG_SDMA_SOA(idx)                                        (REG_BASE_SDMA(idx) + 0x008)
    //Read/Write-Register Using Address
    #define  RD_SDMA_SOA(idx)                                     (REG32(REG_SDMA_SOA(idx)))
    #define  WR_SDMA_SOA(v, idx)                                  (REG32(REG_SDMA_SOA(idx)) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_SDMA_SOA()                                 (0xFFFFFFFF)  
    #define  REG_WMASK_SDMA_SOA()                                 (0xFFFFFFFF)

    //Field: SDMA_SOA
    #define  FLD_LSB_SDMA_SOA()                                   (0)
    #define  FLD_MSB_SDMA_SOA()                                   (31)
    #define  FLD_MASK_SDMA_SOA()                                  (FLD_MASK(0, 31))
    #define  FLD_MWD_SDMA_SOA(v)                                  (FLD_MWD(0, 31, v))
    #define  FLD_MRD_SDMA_SOA(v)                                  (FLD_MRD(0, 31, v))
    #define  SET_SDMA_SOA(v, idx)                                 OP_FLD_WR_EXC(REG_SDMA_SOA(idx), 0, 31, v)
    #define  GET_SDMA_SOA(idx)                                    OP_FLD_RD(REG_SDMA_SOA(idx), 0, 31)
    #define  RST_SDMA_SOA(idx)                                    OP_FLD_WR_EXC(REG_SDMA_SOA(idx), 0, 31, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_SDMA_SOA(SOA,idx) \
                (WR_SDMA_SOA( \
                  (FLD_MWD_SDMA_SOA(SOA))                                                \
                 ,idx \
                ))


#define  REG_SDMA_DOA(idx)                                        (REG_BASE_SDMA(idx) + 0x00c)
    //Read/Write-Register Using Address
    #define  RD_SDMA_DOA(idx)                                     (REG32(REG_SDMA_DOA(idx)))
    #define  WR_SDMA_DOA(v, idx)                                  (REG32(REG_SDMA_DOA(idx)) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_SDMA_DOA()                                 (0xFFFFFFFF)  
    #define  REG_WMASK_SDMA_DOA()                                 (0xFFFFFFFF)

    //Field: SDMA_DOA
    #define  FLD_LSB_SDMA_DOA()                                   (0)
    #define  FLD_MSB_SDMA_DOA()                                   (31)
    #define  FLD_MASK_SDMA_DOA()                                  (FLD_MASK(0, 31))
    #define  FLD_MWD_SDMA_DOA(v)                                  (FLD_MWD(0, 31, v))
    #define  FLD_MRD_SDMA_DOA(v)                                  (FLD_MRD(0, 31, v))
    #define  SET_SDMA_DOA(v, idx)                                 OP_FLD_WR_EXC(REG_SDMA_DOA(idx), 0, 31, v)
    #define  GET_SDMA_DOA(idx)                                    OP_FLD_RD(REG_SDMA_DOA(idx), 0, 31)
    #define  RST_SDMA_DOA(idx)                                    OP_FLD_WR_EXC(REG_SDMA_DOA(idx), 0, 31, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_SDMA_DOA(DOA,idx) \
                (WR_SDMA_DOA( \
                  (FLD_MWD_SDMA_DOA(DOA))                                                \
                 ,idx \
                ))


#define  REG_SDMA_REG_BUS_CLK_CFG(idx)                            (REG_BASE_SDMA(idx) + 0x010)
    //Read/Write-Register Using Address
    #define  RD_SDMA_REG_BUS_CLK_CFG(idx)                         (REG32(REG_SDMA_REG_BUS_CLK_CFG(idx)))
    #define  WR_SDMA_REG_BUS_CLK_CFG(v, idx)                      (REG32(REG_SDMA_REG_BUS_CLK_CFG(idx)) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_SDMA_REG_BUS_CLK_CFG()                     (0x1)  
    #define  REG_WMASK_SDMA_REG_BUS_CLK_CFG()                     (0x1)

    //Field: SDMA_REG_BUS_CLK_GATE_MODE
    #define  FLD_LSB_SDMA_REG_BUS_CLK_GATE_MODE()                 (0)
    #define  FLD_MSB_SDMA_REG_BUS_CLK_GATE_MODE()                 (0)
    #define  FLD_MASK_SDMA_REG_BUS_CLK_GATE_MODE()                (FLD_MASK(0, 0))
    #define  FLD_MWD_SDMA_REG_BUS_CLK_GATE_MODE(v)                (FLD_MWD(0, 0, v))
    #define  FLD_MRD_SDMA_REG_BUS_CLK_GATE_MODE(v)                (FLD_MRD(0, 0, v))
    #define  SET_SDMA_REG_BUS_CLK_GATE_MODE(v, idx)               OP_FLD_WR_EXC(REG_SDMA_REG_BUS_CLK_CFG(idx), 0, 0, v)
    #define  GET_SDMA_REG_BUS_CLK_GATE_MODE(idx)                  OP_FLD_RD(REG_SDMA_REG_BUS_CLK_CFG(idx), 0, 0)
    #define  RST_SDMA_REG_BUS_CLK_GATE_MODE(idx)                  OP_FLD_WR_EXC(REG_SDMA_REG_BUS_CLK_CFG(idx), 0, 0, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_SDMA_REG_BUS_CLK_CFG(REG_BUS_CLK_GATE_MODE,idx) \
                (WR_SDMA_REG_BUS_CLK_CFG( \
                  (FLD_MWD_SDMA_REG_BUS_CLK_GATE_MODE(REG_BUS_CLK_GATE_MODE))            \
                 ,idx \
                ))


//------------------------------------
// Channel Control and Status Registers
//------------------------------------
#define  REG_SDMA_LEN(idx)                                        (REG_BASE_SDMA(idx) + 0x020)
    //Read/Write-Register Using Address
    #define  RD_SDMA_LEN(idx)                                     (REG32(REG_SDMA_LEN(idx)))
    #define  WR_SDMA_LEN(v, idx)                                  (REG32(REG_SDMA_LEN(idx)) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_SDMA_LEN()                                 (0xFFFF)  
    #define  REG_WMASK_SDMA_LEN()                                 (0xFFFF)

    //Field: SDMA_LEN
    #define  FLD_LSB_SDMA_LEN()                                   (0)
    #define  FLD_MSB_SDMA_LEN()                                   (15)
    #define  FLD_MASK_SDMA_LEN()                                  (FLD_MASK(0, 15))
    #define  FLD_MWD_SDMA_LEN(v)                                  (FLD_MWD(0, 15, v))
    #define  FLD_MRD_SDMA_LEN(v)                                  (FLD_MRD(0, 15, v))
    #define  SET_SDMA_LEN(v, idx)                                 OP_FLD_WR_EXC(REG_SDMA_LEN(idx), 0, 15, v)
    #define  GET_SDMA_LEN(idx)                                    OP_FLD_RD(REG_SDMA_LEN(idx), 0, 15)
    #define  GET_SDMA_LEN_CUR(idx)                                OP_FLD_RD(REG_SDMA_LEN(idx), 0, 15)
    #define  RST_SDMA_LEN(idx)                                    OP_FLD_WR_EXC(REG_SDMA_LEN(idx), 0, 15, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_SDMA_LEN(LEN,idx) \
                (WR_SDMA_LEN( \
                  (FLD_MWD_SDMA_LEN(LEN))                                                \
                 ,idx \
                ))


#define  REG_SDMA_CTRL(idx)                                       (REG_BASE_SDMA(idx) + 0x024)
    //Read/Write-Register Using Address
    #define  RD_SDMA_CTRL(idx)                                    (REG32(REG_SDMA_CTRL(idx)))
    #define  WR_SDMA_CTRL(v, idx)                                 (REG32(REG_SDMA_CTRL(idx)) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_SDMA_CTRL()                                (0x370FFFFD)  
    #define  REG_WMASK_SDMA_CTRL()                                (0x37FFFFFF)

    //Field: SDMA_CH_EN
    #define  FLD_LSB_SDMA_CH_EN()                                 (0)
    #define  FLD_MSB_SDMA_CH_EN()                                 (0)
    #define  FLD_MASK_SDMA_CH_EN()                                (FLD_MASK(0, 0))
    #define  FLD_MWD_SDMA_CH_EN(v)                                (FLD_MWD(0, 0, v))
    #define  FLD_MRD_SDMA_CH_EN(v)                                (FLD_MRD(0, 0, v))
    #define  SET_SDMA_CH_EN(v, idx)                               OP_FLD_WR(REG_SDMA_CTRL(idx), 0, 0, v)
    #define  GET_SDMA_CH_EN(idx)                                  OP_FLD_RD(REG_SDMA_CTRL(idx), 0, 0)
    #define  RST_SDMA_CH_EN(idx)                                  OP_FLD_WR(REG_SDMA_CTRL(idx), 0, 0, 0x0)

    //Field: SDMA_CH_RST
    #define  FLD_LSB_SDMA_CH_RST()                                (1)
    #define  FLD_MSB_SDMA_CH_RST()                                (1)
    #define  FLD_MASK_SDMA_CH_RST()                               (FLD_MASK(1, 1))
    #define  FLD_MWD_SDMA_CH_RST(v)                               (FLD_MWD(1, 1, v))
    #define  FLD_MRD_SDMA_CH_RST(v)                               (FLD_MRD(1, 1, v))
    #define  SET_SDMA_CH_RST(v, idx)                              OP_FLD_WR(REG_SDMA_CTRL(idx), 1, 1, v)
    #define  RST_SDMA_CH_RST(idx)                                 OP_FLD_WR(REG_SDMA_CTRL(idx), 1, 1, 0x0)

    //Field: SDMA_PT_CFG
    #define  FLD_LSB_SDMA_PT_CFG()                                (2)
    #define  FLD_MSB_SDMA_PT_CFG()                                (3)
    #define  FLD_MASK_SDMA_PT_CFG()                               (FLD_MASK(2, 3))
    #define  FLD_MWD_SDMA_PT_CFG(v)                               (FLD_MWD(2, 3, v))
    #define  FLD_MRD_SDMA_PT_CFG(v)                               (FLD_MRD(2, 3, v))
    #define  SET_SDMA_PT_CFG(v, idx)                              OP_FLD_WR(REG_SDMA_CTRL(idx), 2, 3, v)
    #define  GET_SDMA_PT_CFG(idx)                                 OP_FLD_RD(REG_SDMA_CTRL(idx), 2, 3)
    #define  RST_SDMA_PT_CFG(idx)                                 OP_FLD_WR(REG_SDMA_CTRL(idx), 2, 3, 0x0)

    //Field: SDMA_CHAIN_TO
    #define  FLD_LSB_SDMA_CHAIN_TO()                              (4)
    #define  FLD_MSB_SDMA_CHAIN_TO()                              (6)
    #define  FLD_MASK_SDMA_CHAIN_TO()                             (FLD_MASK(4, 6))
    #define  FLD_MWD_SDMA_CHAIN_TO(v)                             (FLD_MWD(4, 6, v))
    #define  FLD_MRD_SDMA_CHAIN_TO(v)                             (FLD_MRD(4, 6, v))
    #define  SET_SDMA_CHAIN_TO(v, idx)                            OP_FLD_WR(REG_SDMA_CTRL(idx), 4, 6, v)
    #define  GET_SDMA_CHAIN_TO(idx)                               OP_FLD_RD(REG_SDMA_CTRL(idx), 4, 6)
    #define  RST_SDMA_CHAIN_TO(idx)                               OP_FLD_WR(REG_SDMA_CTRL(idx), 4, 6, 0x0)

    //Field: SDMA_CHAIN_EN
    #define  FLD_LSB_SDMA_CHAIN_EN()                              (7)
    #define  FLD_MSB_SDMA_CHAIN_EN()                              (7)
    #define  FLD_MASK_SDMA_CHAIN_EN()                             (FLD_MASK(7, 7))
    #define  FLD_MWD_SDMA_CHAIN_EN(v)                             (FLD_MWD(7, 7, v))
    #define  FLD_MRD_SDMA_CHAIN_EN(v)                             (FLD_MRD(7, 7, v))
    #define  SET_SDMA_CHAIN_EN(v, idx)                            OP_FLD_WR(REG_SDMA_CTRL(idx), 7, 7, v)
    #define  GET_SDMA_CHAIN_EN(idx)                               OP_FLD_RD(REG_SDMA_CTRL(idx), 7, 7)
    #define  RST_SDMA_CHAIN_EN(idx)                               OP_FLD_WR(REG_SDMA_CTRL(idx), 7, 7, 0x0)

    //Field: SDMA_SA_MODE
    #define  FLD_LSB_SDMA_SA_MODE()                               (8)
    #define  FLD_MSB_SDMA_SA_MODE()                               (11)
    #define  FLD_MASK_SDMA_SA_MODE()                              (FLD_MASK(8, 11))
    #define  FLD_MWD_SDMA_SA_MODE(v)                              (FLD_MWD(8, 11, v))
    #define  FLD_MRD_SDMA_SA_MODE(v)                              (FLD_MRD(8, 11, v))
    #define  SET_SDMA_SA_MODE(v, idx)                             OP_FLD_WR(REG_SDMA_CTRL(idx), 8, 11, v)
    #define  GET_SDMA_SA_MODE(idx)                                OP_FLD_RD(REG_SDMA_CTRL(idx), 8, 11)
    #define  RST_SDMA_SA_MODE(idx)                                OP_FLD_WR(REG_SDMA_CTRL(idx), 8, 11, 0x0)

    //Field: SDMA_DA_MODE
    #define  FLD_LSB_SDMA_DA_MODE()                               (12)
    #define  FLD_MSB_SDMA_DA_MODE()                               (15)
    #define  FLD_MASK_SDMA_DA_MODE()                              (FLD_MASK(12, 15))
    #define  FLD_MWD_SDMA_DA_MODE(v)                              (FLD_MWD(12, 15, v))
    #define  FLD_MRD_SDMA_DA_MODE(v)                              (FLD_MRD(12, 15, v))
    #define  SET_SDMA_DA_MODE(v, idx)                             OP_FLD_WR(REG_SDMA_CTRL(idx), 12, 15, v)
    #define  GET_SDMA_DA_MODE(idx)                                OP_FLD_RD(REG_SDMA_CTRL(idx), 12, 15)
    #define  RST_SDMA_DA_MODE(idx)                                OP_FLD_WR(REG_SDMA_CTRL(idx), 12, 15, 0x0)

    //Field: SDMA_HS_MODE
    #define  FLD_LSB_SDMA_HS_MODE()                               (16)
    #define  FLD_MSB_SDMA_HS_MODE()                               (17)
    #define  FLD_MASK_SDMA_HS_MODE()                              (FLD_MASK(16, 17))
    #define  FLD_MWD_SDMA_HS_MODE(v)                              (FLD_MWD(16, 17, v))
    #define  FLD_MRD_SDMA_HS_MODE(v)                              (FLD_MRD(16, 17, v))
    #define  SET_SDMA_HS_MODE(v, idx)                             OP_FLD_WR(REG_SDMA_CTRL(idx), 16, 17, v)
    #define  GET_SDMA_HS_MODE(idx)                                OP_FLD_RD(REG_SDMA_CTRL(idx), 16, 17)
    #define  RST_SDMA_HS_MODE(idx)                                OP_FLD_WR(REG_SDMA_CTRL(idx), 16, 17, 0x0)

    //Field: SDMA_STOPPER
    #define  FLD_LSB_SDMA_STOPPER()                               (18)
    #define  FLD_MSB_SDMA_STOPPER()                               (18)
    #define  FLD_MASK_SDMA_STOPPER()                              (FLD_MASK(18, 18))
    #define  FLD_MWD_SDMA_STOPPER(v)                              (FLD_MWD(18, 18, v))
    #define  FLD_MRD_SDMA_STOPPER(v)                              (FLD_MRD(18, 18, v))
    #define  SET_SDMA_STOPPER(v, idx)                             OP_FLD_WR(REG_SDMA_CTRL(idx), 18, 18, v)
    #define  GET_SDMA_STOPPER(idx)                                OP_FLD_RD(REG_SDMA_CTRL(idx), 18, 18)
    #define  RST_SDMA_STOPPER(idx)                                OP_FLD_WR(REG_SDMA_CTRL(idx), 18, 18, 0x0)

    //Field: SDMA_PAUSER
    #define  FLD_LSB_SDMA_PAUSER()                                (19)
    #define  FLD_MSB_SDMA_PAUSER()                                (19)
    #define  FLD_MASK_SDMA_PAUSER()                               (FLD_MASK(19, 19))
    #define  FLD_MWD_SDMA_PAUSER(v)                               (FLD_MWD(19, 19, v))
    #define  FLD_MRD_SDMA_PAUSER(v)                               (FLD_MRD(19, 19, v))
    #define  SET_SDMA_PAUSER(v, idx)                              OP_FLD_WR(REG_SDMA_CTRL(idx), 19, 19, v)
    #define  GET_SDMA_PAUSER(idx)                                 OP_FLD_RD(REG_SDMA_CTRL(idx), 19, 19)
    #define  RST_SDMA_PAUSER(idx)                                 OP_FLD_WR(REG_SDMA_CTRL(idx), 19, 19, 0x0)

    //Field: SDMA_SW_HS
    #define  FLD_LSB_SDMA_SW_HS()                                 (20)
    #define  FLD_MSB_SDMA_SW_HS()                                 (23)
    #define  FLD_MASK_SDMA_SW_HS()                                (FLD_MASK(20, 23))
    #define  FLD_MWD_SDMA_SW_HS(v)                                (FLD_MWD(20, 23, v))
    #define  FLD_MRD_SDMA_SW_HS(v)                                (FLD_MRD(20, 23, v))
    #define  SET_SDMA_SW_HS(v, idx)                               OP_FLD_WR(REG_SDMA_CTRL(idx), 20, 23, v)
    #define  RST_SDMA_SW_HS(idx)                                  OP_FLD_WR(REG_SDMA_CTRL(idx), 20, 23, 0x0)

    //Field: SDMA_RELOAD_SA
    #define  FLD_LSB_SDMA_RELOAD_SA()                             (24)
    #define  FLD_MSB_SDMA_RELOAD_SA()                             (24)
    #define  FLD_MASK_SDMA_RELOAD_SA()                            (FLD_MASK(24, 24))
    #define  FLD_MWD_SDMA_RELOAD_SA(v)                            (FLD_MWD(24, 24, v))
    #define  FLD_MRD_SDMA_RELOAD_SA(v)                            (FLD_MRD(24, 24, v))
    #define  SET_SDMA_RELOAD_SA(v, idx)                           OP_FLD_WR(REG_SDMA_CTRL(idx), 24, 24, v)
    #define  GET_SDMA_RELOAD_SA(idx)                              OP_FLD_RD(REG_SDMA_CTRL(idx), 24, 24)
    #define  RST_SDMA_RELOAD_SA(idx)                              OP_FLD_WR(REG_SDMA_CTRL(idx), 24, 24, 0x0)

    //Field: SDMA_RELOAD_DA
    #define  FLD_LSB_SDMA_RELOAD_DA()                             (25)
    #define  FLD_MSB_SDMA_RELOAD_DA()                             (25)
    #define  FLD_MASK_SDMA_RELOAD_DA()                            (FLD_MASK(25, 25))
    #define  FLD_MWD_SDMA_RELOAD_DA(v)                            (FLD_MWD(25, 25, v))
    #define  FLD_MRD_SDMA_RELOAD_DA(v)                            (FLD_MRD(25, 25, v))
    #define  SET_SDMA_RELOAD_DA(v, idx)                           OP_FLD_WR(REG_SDMA_CTRL(idx), 25, 25, v)
    #define  GET_SDMA_RELOAD_DA(idx)                              OP_FLD_RD(REG_SDMA_CTRL(idx), 25, 25)
    #define  RST_SDMA_RELOAD_DA(idx)                              OP_FLD_WR(REG_SDMA_CTRL(idx), 25, 25, 0x0)

    //Field: SDMA_RELOAD_LEN
    #define  FLD_LSB_SDMA_RELOAD_LEN()                            (26)
    #define  FLD_MSB_SDMA_RELOAD_LEN()                            (26)
    #define  FLD_MASK_SDMA_RELOAD_LEN()                           (FLD_MASK(26, 26))
    #define  FLD_MWD_SDMA_RELOAD_LEN(v)                           (FLD_MWD(26, 26, v))
    #define  FLD_MRD_SDMA_RELOAD_LEN(v)                           (FLD_MRD(26, 26, v))
    #define  SET_SDMA_RELOAD_LEN(v, idx)                          OP_FLD_WR(REG_SDMA_CTRL(idx), 26, 26, v)
    #define  GET_SDMA_RELOAD_LEN(idx)                             OP_FLD_RD(REG_SDMA_CTRL(idx), 26, 26)
    #define  RST_SDMA_RELOAD_LEN(idx)                             OP_FLD_WR(REG_SDMA_CTRL(idx), 26, 26, 0x0)

    //Field: SDMA_SFC_EN
    #define  FLD_LSB_SDMA_SFC_EN()                                (28)
    #define  FLD_MSB_SDMA_SFC_EN()                                (28)
    #define  FLD_MASK_SDMA_SFC_EN()                               (FLD_MASK(28, 28))
    #define  FLD_MWD_SDMA_SFC_EN(v)                               (FLD_MWD(28, 28, v))
    #define  FLD_MRD_SDMA_SFC_EN(v)                               (FLD_MRD(28, 28, v))
    #define  SET_SDMA_SFC_EN(v, idx)                              OP_FLD_WR(REG_SDMA_CTRL(idx), 28, 28, v)
    #define  GET_SDMA_SFC_EN(idx)                                 OP_FLD_RD(REG_SDMA_CTRL(idx), 28, 28)
    #define  RST_SDMA_SFC_EN(idx)                                 OP_FLD_WR(REG_SDMA_CTRL(idx), 28, 28, 0x0)

    //Field: SDMA_DFC_EN
    #define  FLD_LSB_SDMA_DFC_EN()                                (29)
    #define  FLD_MSB_SDMA_DFC_EN()                                (29)
    #define  FLD_MASK_SDMA_DFC_EN()                               (FLD_MASK(29, 29))
    #define  FLD_MWD_SDMA_DFC_EN(v)                               (FLD_MWD(29, 29, v))
    #define  FLD_MRD_SDMA_DFC_EN(v)                               (FLD_MRD(29, 29, v))
    #define  SET_SDMA_DFC_EN(v, idx)                              OP_FLD_WR(REG_SDMA_CTRL(idx), 29, 29, v)
    #define  GET_SDMA_DFC_EN(idx)                                 OP_FLD_RD(REG_SDMA_CTRL(idx), 29, 29)
    #define  RST_SDMA_DFC_EN(idx)                                 OP_FLD_WR(REG_SDMA_CTRL(idx), 29, 29, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_SDMA_CTRL(CH_EN,CH_RST,PT_CFG,CHAIN_TO,CHAIN_EN,SA_MODE,DA_MODE,HS_MODE,STOPPER,PAUSER,SW_HS,RELOAD_SA,RELOAD_DA,RELOAD_LEN,SFC_EN,DFC_EN,idx) \
                (WR_SDMA_CTRL( \
                  (FLD_MWD_SDMA_CH_EN(CH_EN))                                          | \
                  (FLD_MWD_SDMA_CH_RST(CH_RST))                                        | \
                  (FLD_MWD_SDMA_PT_CFG(PT_CFG))                                        | \
                  (FLD_MWD_SDMA_CHAIN_TO(CHAIN_TO))                                    | \
                  (FLD_MWD_SDMA_CHAIN_EN(CHAIN_EN))                                    | \
                  (FLD_MWD_SDMA_SA_MODE(SA_MODE))                                      | \
                  (FLD_MWD_SDMA_DA_MODE(DA_MODE))                                      | \
                  (FLD_MWD_SDMA_HS_MODE(HS_MODE))                                      | \
                  (FLD_MWD_SDMA_STOPPER(STOPPER))                                      | \
                  (FLD_MWD_SDMA_PAUSER(PAUSER))                                        | \
                  (FLD_MWD_SDMA_SW_HS(SW_HS))                                          | \
                  (FLD_MWD_SDMA_RELOAD_SA(RELOAD_SA))                                  | \
                  (FLD_MWD_SDMA_RELOAD_DA(RELOAD_DA))                                  | \
                  (FLD_MWD_SDMA_RELOAD_LEN(RELOAD_LEN))                                | \
                  (FLD_MWD_SDMA_SFC_EN(SFC_EN))                                        | \
                  (FLD_MWD_SDMA_DFC_EN(DFC_EN))                                          \
                 ,idx \
                ))


#define  REG_SDMA_STA(idx)                                        (REG_BASE_SDMA(idx) + 0x028)
    //Read/Write-Register Using Address
    #define  RD_SDMA_STA(idx)                                     (REG32(REG_SDMA_STA(idx)))
    #define  WR_SDMA_STA(v, idx)                                  (REG32(REG_SDMA_STA(idx)) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_SDMA_STA()                                 (0xFF0F)  
    #define  REG_WMASK_SDMA_STA()                                 (0x0)

    //Field: SDMA_CH_STA
    #define  FLD_LSB_SDMA_CH_STA()                                (0)
    #define  FLD_MSB_SDMA_CH_STA()                                (3)
    #define  FLD_MASK_SDMA_CH_STA()                               (FLD_MASK(0, 3))
    #define  FLD_MWD_SDMA_CH_STA(v)                               (FLD_MWD(0, 3, v))
    #define  FLD_MRD_SDMA_CH_STA(v)                               (FLD_MRD(0, 3, v))
    #define  GET_SDMA_CH_STA(idx)                                 OP_FLD_RD(REG_SDMA_STA(idx), 0, 3)

    //Field: SDMA_ERR_STA
    #define  FLD_LSB_SDMA_ERR_STA()                               (8)
    #define  FLD_MSB_SDMA_ERR_STA()                               (15)
    #define  FLD_MASK_SDMA_ERR_STA()                              (FLD_MASK(8, 15))
    #define  FLD_MWD_SDMA_ERR_STA(v)                              (FLD_MWD(8, 15, v))
    #define  FLD_MRD_SDMA_ERR_STA(v)                              (FLD_MRD(8, 15, v))
    #define  GET_SDMA_ERR_STA(idx)                                OP_FLD_RD(REG_SDMA_STA(idx), 8, 15)

    //Write-Register Using Field-Name
    #define  WRF_SDMA_STA(CH_STA,ERR_STA,idx) \
                (WR_SDMA_STA( \
   \
                 ,idx \
                ))


//------------------------------------
// Channel Interrupt Registers
//------------------------------------
#define  REG_SDMA_IE(idx)                                         (REG_BASE_SDMA(idx) + 0x040)
    //Read/Write-Register Using Address
    #define  RD_SDMA_IE(idx)                                      (REG32(REG_SDMA_IE(idx)))
    #define  WR_SDMA_IE(v, idx)                                   (REG32(REG_SDMA_IE(idx)) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_SDMA_IE()                                  (0x11F)  
    #define  REG_WMASK_SDMA_IE()                                  (0x11F)

    //Field: SDMA_IE_START
    #define  FLD_LSB_SDMA_IE_START()                              (0)
    #define  FLD_MSB_SDMA_IE_START()                              (0)
    #define  FLD_MASK_SDMA_IE_START()                             (FLD_MASK(0, 0))
    #define  FLD_MWD_SDMA_IE_START(v)                             (FLD_MWD(0, 0, v))
    #define  FLD_MRD_SDMA_IE_START(v)                             (FLD_MRD(0, 0, v))
    #define  SET_SDMA_IE_START(v, idx)                            OP_FLD_WR(REG_SDMA_IE(idx), 0, 0, v)
    #define  GET_SDMA_IE_START(idx)                               OP_FLD_RD(REG_SDMA_IE(idx), 0, 0)
    #define  RST_SDMA_IE_START(idx)                               OP_FLD_WR(REG_SDMA_IE(idx), 0, 0, 0x0)

    //Field: SDMA_IE_PAUSE
    #define  FLD_LSB_SDMA_IE_PAUSE()                              (1)
    #define  FLD_MSB_SDMA_IE_PAUSE()                              (1)
    #define  FLD_MASK_SDMA_IE_PAUSE()                             (FLD_MASK(1, 1))
    #define  FLD_MWD_SDMA_IE_PAUSE(v)                             (FLD_MWD(1, 1, v))
    #define  FLD_MRD_SDMA_IE_PAUSE(v)                             (FLD_MRD(1, 1, v))
    #define  SET_SDMA_IE_PAUSE(v, idx)                            OP_FLD_WR(REG_SDMA_IE(idx), 1, 1, v)
    #define  GET_SDMA_IE_PAUSE(idx)                               OP_FLD_RD(REG_SDMA_IE(idx), 1, 1)
    #define  RST_SDMA_IE_PAUSE(idx)                               OP_FLD_WR(REG_SDMA_IE(idx), 1, 1, 0x0)

    //Field: SDMA_IE_STOP
    #define  FLD_LSB_SDMA_IE_STOP()                               (2)
    #define  FLD_MSB_SDMA_IE_STOP()                               (2)
    #define  FLD_MASK_SDMA_IE_STOP()                              (FLD_MASK(2, 2))
    #define  FLD_MWD_SDMA_IE_STOP(v)                              (FLD_MWD(2, 2, v))
    #define  FLD_MRD_SDMA_IE_STOP(v)                              (FLD_MRD(2, 2, v))
    #define  SET_SDMA_IE_STOP(v, idx)                             OP_FLD_WR(REG_SDMA_IE(idx), 2, 2, v)
    #define  GET_SDMA_IE_STOP(idx)                                OP_FLD_RD(REG_SDMA_IE(idx), 2, 2)
    #define  RST_SDMA_IE_STOP(idx)                                OP_FLD_WR(REG_SDMA_IE(idx), 2, 2, 0x0)

    //Field: SDMA_IE_BLK_DONE
    #define  FLD_LSB_SDMA_IE_BLK_DONE()                           (3)
    #define  FLD_MSB_SDMA_IE_BLK_DONE()                           (3)
    #define  FLD_MASK_SDMA_IE_BLK_DONE()                          (FLD_MASK(3, 3))
    #define  FLD_MWD_SDMA_IE_BLK_DONE(v)                          (FLD_MWD(3, 3, v))
    #define  FLD_MRD_SDMA_IE_BLK_DONE(v)                          (FLD_MRD(3, 3, v))
    #define  SET_SDMA_IE_BLK_DONE(v, idx)                         OP_FLD_WR(REG_SDMA_IE(idx), 3, 3, v)
    #define  GET_SDMA_IE_BLK_DONE(idx)                            OP_FLD_RD(REG_SDMA_IE(idx), 3, 3)
    #define  RST_SDMA_IE_BLK_DONE(idx)                            OP_FLD_WR(REG_SDMA_IE(idx), 3, 3, 0x0)

    //Field: SDMA_IE_TRANS_DONE
    #define  FLD_LSB_SDMA_IE_TRANS_DONE()                         (4)
    #define  FLD_MSB_SDMA_IE_TRANS_DONE()                         (4)
    #define  FLD_MASK_SDMA_IE_TRANS_DONE()                        (FLD_MASK(4, 4))
    #define  FLD_MWD_SDMA_IE_TRANS_DONE(v)                        (FLD_MWD(4, 4, v))
    #define  FLD_MRD_SDMA_IE_TRANS_DONE(v)                        (FLD_MRD(4, 4, v))
    #define  SET_SDMA_IE_TRANS_DONE(v, idx)                       OP_FLD_WR(REG_SDMA_IE(idx), 4, 4, v)
    #define  GET_SDMA_IE_TRANS_DONE(idx)                          OP_FLD_RD(REG_SDMA_IE(idx), 4, 4)
    #define  RST_SDMA_IE_TRANS_DONE(idx)                          OP_FLD_WR(REG_SDMA_IE(idx), 4, 4, 0x0)

    //Field: SDMA_IE_TRANS_ERR
    #define  FLD_LSB_SDMA_IE_TRANS_ERR()                          (8)
    #define  FLD_MSB_SDMA_IE_TRANS_ERR()                          (8)
    #define  FLD_MASK_SDMA_IE_TRANS_ERR()                         (FLD_MASK(8, 8))
    #define  FLD_MWD_SDMA_IE_TRANS_ERR(v)                         (FLD_MWD(8, 8, v))
    #define  FLD_MRD_SDMA_IE_TRANS_ERR(v)                         (FLD_MRD(8, 8, v))
    #define  SET_SDMA_IE_TRANS_ERR(v, idx)                        OP_FLD_WR(REG_SDMA_IE(idx), 8, 8, v)
    #define  GET_SDMA_IE_TRANS_ERR(idx)                           OP_FLD_RD(REG_SDMA_IE(idx), 8, 8)
    #define  RST_SDMA_IE_TRANS_ERR(idx)                           OP_FLD_WR(REG_SDMA_IE(idx), 8, 8, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_SDMA_IE(IE_START,IE_PAUSE,IE_STOP,IE_BLK_DONE,IE_TRANS_DONE,IE_TRANS_ERR,idx) \
                (WR_SDMA_IE( \
                  (FLD_MWD_SDMA_IE_START(IE_START))                                    | \
                  (FLD_MWD_SDMA_IE_PAUSE(IE_PAUSE))                                    | \
                  (FLD_MWD_SDMA_IE_STOP(IE_STOP))                                      | \
                  (FLD_MWD_SDMA_IE_BLK_DONE(IE_BLK_DONE))                              | \
                  (FLD_MWD_SDMA_IE_TRANS_DONE(IE_TRANS_DONE))                          | \
                  (FLD_MWD_SDMA_IE_TRANS_ERR(IE_TRANS_ERR))                              \
                 ,idx \
                ))


#define  REG_SDMA_IS(idx)                                         (REG_BASE_SDMA(idx) + 0x044)
    //Read/Write-Register Using Address
    #define  RD_SDMA_IS(idx)                                      (REG32(REG_SDMA_IS(idx)))
    #define  WR_SDMA_IS(v, idx)                                   (REG32(REG_SDMA_IS(idx)) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_SDMA_IS()                                  (0x11F)  
    #define  REG_WMASK_SDMA_IS()                                  (0x0)

    //Field: SDMA_IS_START
    #define  FLD_LSB_SDMA_IS_START()                              (0)
    #define  FLD_MSB_SDMA_IS_START()                              (0)
    #define  FLD_MASK_SDMA_IS_START()                             (FLD_MASK(0, 0))
    #define  FLD_MWD_SDMA_IS_START(v)                             (FLD_MWD(0, 0, v))
    #define  FLD_MRD_SDMA_IS_START(v)                             (FLD_MRD(0, 0, v))
    #define  GET_SDMA_IS_START(idx)                               OP_FLD_RD(REG_SDMA_IS(idx), 0, 0)
    #define  RST_SDMA_IS_START(idx)                               OP_FLD_RD(REG_SDMA_IS(idx), 0, 0)

    //Field: SDMA_IS_PAUSE
    #define  FLD_LSB_SDMA_IS_PAUSE()                              (1)
    #define  FLD_MSB_SDMA_IS_PAUSE()                              (1)
    #define  FLD_MASK_SDMA_IS_PAUSE()                             (FLD_MASK(1, 1))
    #define  FLD_MWD_SDMA_IS_PAUSE(v)                             (FLD_MWD(1, 1, v))
    #define  FLD_MRD_SDMA_IS_PAUSE(v)                             (FLD_MRD(1, 1, v))
    #define  GET_SDMA_IS_PAUSE(idx)                               OP_FLD_RD(REG_SDMA_IS(idx), 1, 1)
    #define  RST_SDMA_IS_PAUSE(idx)                               OP_FLD_RD(REG_SDMA_IS(idx), 1, 1)

    //Field: SDMA_IS_STOP
    #define  FLD_LSB_SDMA_IS_STOP()                               (2)
    #define  FLD_MSB_SDMA_IS_STOP()                               (2)
    #define  FLD_MASK_SDMA_IS_STOP()                              (FLD_MASK(2, 2))
    #define  FLD_MWD_SDMA_IS_STOP(v)                              (FLD_MWD(2, 2, v))
    #define  FLD_MRD_SDMA_IS_STOP(v)                              (FLD_MRD(2, 2, v))
    #define  GET_SDMA_IS_STOP(idx)                                OP_FLD_RD(REG_SDMA_IS(idx), 2, 2)
    #define  RST_SDMA_IS_STOP(idx)                                OP_FLD_RD(REG_SDMA_IS(idx), 2, 2)

    //Field: SDMA_IS_BLK_DONE
    #define  FLD_LSB_SDMA_IS_BLK_DONE()                           (3)
    #define  FLD_MSB_SDMA_IS_BLK_DONE()                           (3)
    #define  FLD_MASK_SDMA_IS_BLK_DONE()                          (FLD_MASK(3, 3))
    #define  FLD_MWD_SDMA_IS_BLK_DONE(v)                          (FLD_MWD(3, 3, v))
    #define  FLD_MRD_SDMA_IS_BLK_DONE(v)                          (FLD_MRD(3, 3, v))
    #define  GET_SDMA_IS_BLK_DONE(idx)                            OP_FLD_RD(REG_SDMA_IS(idx), 3, 3)
    #define  RST_SDMA_IS_BLK_DONE(idx)                            OP_FLD_RD(REG_SDMA_IS(idx), 3, 3)

    //Field: SDMA_IS_TRANS_DONE
    #define  FLD_LSB_SDMA_IS_TRANS_DONE()                         (4)
    #define  FLD_MSB_SDMA_IS_TRANS_DONE()                         (4)
    #define  FLD_MASK_SDMA_IS_TRANS_DONE()                        (FLD_MASK(4, 4))
    #define  FLD_MWD_SDMA_IS_TRANS_DONE(v)                        (FLD_MWD(4, 4, v))
    #define  FLD_MRD_SDMA_IS_TRANS_DONE(v)                        (FLD_MRD(4, 4, v))
    #define  GET_SDMA_IS_TRANS_DONE(idx)                          OP_FLD_RD(REG_SDMA_IS(idx), 4, 4)
    #define  RST_SDMA_IS_TRANS_DONE(idx)                          OP_FLD_RD(REG_SDMA_IS(idx), 4, 4)

    //Field: SDMA_IS_TRANS_ERR
    #define  FLD_LSB_SDMA_IS_TRANS_ERR()                          (8)
    #define  FLD_MSB_SDMA_IS_TRANS_ERR()                          (8)
    #define  FLD_MASK_SDMA_IS_TRANS_ERR()                         (FLD_MASK(8, 8))
    #define  FLD_MWD_SDMA_IS_TRANS_ERR(v)                         (FLD_MWD(8, 8, v))
    #define  FLD_MRD_SDMA_IS_TRANS_ERR(v)                         (FLD_MRD(8, 8, v))
    #define  GET_SDMA_IS_TRANS_ERR(idx)                           OP_FLD_RD(REG_SDMA_IS(idx), 8, 8)
    #define  RST_SDMA_IS_TRANS_ERR(idx)                           OP_FLD_RD(REG_SDMA_IS(idx), 8, 8)

    //Write-Register Using Field-Name
    #define  WRF_SDMA_IS(IS_START,IS_PAUSE,IS_STOP,IS_BLK_DONE,IS_TRANS_DONE,IS_TRANS_ERR,idx) \
                (WR_SDMA_IS( \
   \
                 ,idx \
                ))


//------------------------------------
// Channel Configuration Registers
//------------------------------------
#define  REG_SDMA_ARB(idx)                                        (REG_BASE_SDMA(idx) + 0x060)
    //Read/Write-Register Using Address
    #define  RD_SDMA_ARB(idx)                                     (REG32(REG_SDMA_ARB(idx)))
    #define  WR_SDMA_ARB(v, idx)                                  (REG32(REG_SDMA_ARB(idx)) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_SDMA_ARB()                                 (0x8703)  
    #define  REG_WMASK_SDMA_ARB()                                 (0x8703)

    //Field: SDMA_BLK_ARB
    #define  FLD_LSB_SDMA_BLK_ARB()                               (0)
    #define  FLD_MSB_SDMA_BLK_ARB()                               (0)
    #define  FLD_MASK_SDMA_BLK_ARB()                              (FLD_MASK(0, 0))
    #define  FLD_MWD_SDMA_BLK_ARB(v)                              (FLD_MWD(0, 0, v))
    #define  FLD_MRD_SDMA_BLK_ARB(v)                              (FLD_MRD(0, 0, v))
    #define  SET_SDMA_BLK_ARB(v, idx)                             OP_FLD_WR(REG_SDMA_ARB(idx), 0, 0, v)
    #define  GET_SDMA_BLK_ARB(idx)                                OP_FLD_RD(REG_SDMA_ARB(idx), 0, 0)
    #define  RST_SDMA_BLK_ARB(idx)                                OP_FLD_WR(REG_SDMA_ARB(idx), 0, 0, 0x0)

    //Field: SDMA_CH_ARB
    #define  FLD_LSB_SDMA_CH_ARB()                                (1)
    #define  FLD_MSB_SDMA_CH_ARB()                                (1)
    #define  FLD_MASK_SDMA_CH_ARB()                               (FLD_MASK(1, 1))
    #define  FLD_MWD_SDMA_CH_ARB(v)                               (FLD_MWD(1, 1, v))
    #define  FLD_MRD_SDMA_CH_ARB(v)                               (FLD_MRD(1, 1, v))
    #define  SET_SDMA_CH_ARB(v, idx)                              OP_FLD_WR(REG_SDMA_ARB(idx), 1, 1, v)
    #define  GET_SDMA_CH_ARB(idx)                                 OP_FLD_RD(REG_SDMA_ARB(idx), 1, 1)
    #define  RST_SDMA_CH_ARB(idx)                                 OP_FLD_WR(REG_SDMA_ARB(idx), 1, 1, 0x0)

    //Field: SDMA_PRI
    #define  FLD_LSB_SDMA_PRI()                                   (8)
    #define  FLD_MSB_SDMA_PRI()                                   (10)
    #define  FLD_MASK_SDMA_PRI()                                  (FLD_MASK(8, 10))
    #define  FLD_MWD_SDMA_PRI(v)                                  (FLD_MWD(8, 10, v))
    #define  FLD_MRD_SDMA_PRI(v)                                  (FLD_MRD(8, 10, v))
    #define  SET_SDMA_PRI(v, idx)                                 OP_FLD_WR(REG_SDMA_ARB(idx), 8, 10, v)
    #define  GET_SDMA_PRI(idx)                                    OP_FLD_RD(REG_SDMA_ARB(idx), 8, 10)
    #define  RST_SDMA_PRI(idx)                                    OP_FLD_WR(REG_SDMA_ARB(idx), 8, 10, 0x0)

    //Field: SDMA_CH_ARB_FIX
    #define  FLD_LSB_SDMA_CH_ARB_FIX()                            (15)
    #define  FLD_MSB_SDMA_CH_ARB_FIX()                            (15)
    #define  FLD_MASK_SDMA_CH_ARB_FIX()                           (FLD_MASK(15, 15))
    #define  FLD_MWD_SDMA_CH_ARB_FIX(v)                           (FLD_MWD(15, 15, v))
    #define  FLD_MRD_SDMA_CH_ARB_FIX(v)                           (FLD_MRD(15, 15, v))
    #define  SET_SDMA_CH_ARB_FIX(v, idx)                          OP_FLD_WR(REG_SDMA_ARB(idx), 15, 15, v)
    #define  GET_SDMA_CH_ARB_FIX(idx)                             OP_FLD_RD(REG_SDMA_ARB(idx), 15, 15)
    #define  RST_SDMA_CH_ARB_FIX(idx)                             OP_FLD_WR(REG_SDMA_ARB(idx), 15, 15, 0x1)

    //Write-Register Using Field-Name
    #define  WRF_SDMA_ARB(BLK_ARB,CH_ARB,PRI,CH_ARB_FIX,idx) \
                (WR_SDMA_ARB( \
                  (FLD_MWD_SDMA_BLK_ARB(BLK_ARB))                                      | \
                  (FLD_MWD_SDMA_CH_ARB(CH_ARB))                                        | \
                  (FLD_MWD_SDMA_PRI(PRI))                                              | \
                  (FLD_MWD_SDMA_CH_ARB_FIX(CH_ARB_FIX))                                  \
                 ,idx \
                ))


#define  REG_SDMA_TO(idx)                                         (REG_BASE_SDMA(idx) + 0x064)
    //Read/Write-Register Using Address
    #define  RD_SDMA_TO(idx)                                      (REG32(REG_SDMA_TO(idx)))
    #define  WR_SDMA_TO(v, idx)                                   (REG32(REG_SDMA_TO(idx)) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_SDMA_TO()                                  (0xFFFFFFFF)  
    #define  REG_WMASK_SDMA_TO()                                  (0xFFFFFFFF)

    //Field: SDMA_TIMEOUT
    #define  FLD_LSB_SDMA_TIMEOUT()                               (0)
    #define  FLD_MSB_SDMA_TIMEOUT()                               (31)
    #define  FLD_MASK_SDMA_TIMEOUT()                              (FLD_MASK(0, 31))
    #define  FLD_MWD_SDMA_TIMEOUT(v)                              (FLD_MWD(0, 31, v))
    #define  FLD_MRD_SDMA_TIMEOUT(v)                              (FLD_MRD(0, 31, v))
    #define  SET_SDMA_TIMEOUT(v, idx)                             OP_FLD_WR_EXC(REG_SDMA_TO(idx), 0, 31, v)
    #define  GET_SDMA_TIMEOUT(idx)                                OP_FLD_RD(REG_SDMA_TO(idx), 0, 31)
    #define  RST_SDMA_TIMEOUT(idx)                                OP_FLD_WR_EXC(REG_SDMA_TO(idx), 0, 31, 0x100000)

    //Write-Register Using Field-Name
    #define  WRF_SDMA_TO(TIMEOUT,idx) \
                (WR_SDMA_TO( \
                  (FLD_MWD_SDMA_TIMEOUT(TIMEOUT))                                        \
                 ,idx \
                ))


#define  REG_SDMA_BUF(idx)                                        (REG_BASE_SDMA(idx) + 0x068)
    //Read/Write-Register Using Address
    #define  RD_SDMA_BUF(idx)                                     (REG32(REG_SDMA_BUF(idx)))
    #define  WR_SDMA_BUF(v, idx)                                  (REG32(REG_SDMA_BUF(idx)) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_SDMA_BUF()                                 (0xF0F0F)  
    #define  REG_WMASK_SDMA_BUF()                                 (0xF0F0F)

    //Field: SDMA_BLK_SIZE
    #define  FLD_LSB_SDMA_BLK_SIZE()                              (0)
    #define  FLD_MSB_SDMA_BLK_SIZE()                              (3)
    #define  FLD_MASK_SDMA_BLK_SIZE()                             (FLD_MASK(0, 3))
    #define  FLD_MWD_SDMA_BLK_SIZE(v)                             (FLD_MWD(0, 3, v))
    #define  FLD_MRD_SDMA_BLK_SIZE(v)                             (FLD_MRD(0, 3, v))
    #define  SET_SDMA_BLK_SIZE(v, idx)                            OP_FLD_WR(REG_SDMA_BUF(idx), 0, 3, v)
    #define  GET_SDMA_BLK_SIZE(idx)                               OP_FLD_RD(REG_SDMA_BUF(idx), 0, 3)
    #define  RST_SDMA_BLK_SIZE(idx)                               OP_FLD_WR(REG_SDMA_BUF(idx), 0, 3, 0x5)

    //Field: SDMA_RD_WM
    #define  FLD_LSB_SDMA_RD_WM()                                 (8)
    #define  FLD_MSB_SDMA_RD_WM()                                 (11)
    #define  FLD_MASK_SDMA_RD_WM()                                (FLD_MASK(8, 11))
    #define  FLD_MWD_SDMA_RD_WM(v)                                (FLD_MWD(8, 11, v))
    #define  FLD_MRD_SDMA_RD_WM(v)                                (FLD_MRD(8, 11, v))
    #define  SET_SDMA_RD_WM(v, idx)                               OP_FLD_WR(REG_SDMA_BUF(idx), 8, 11, v)
    #define  GET_SDMA_RD_WM(idx)                                  OP_FLD_RD(REG_SDMA_BUF(idx), 8, 11)
    #define  RST_SDMA_RD_WM(idx)                                  OP_FLD_WR(REG_SDMA_BUF(idx), 8, 11, 0x4)

    //Field: SDMA_WT_WM
    #define  FLD_LSB_SDMA_WT_WM()                                 (16)
    #define  FLD_MSB_SDMA_WT_WM()                                 (19)
    #define  FLD_MASK_SDMA_WT_WM()                                (FLD_MASK(16, 19))
    #define  FLD_MWD_SDMA_WT_WM(v)                                (FLD_MWD(16, 19, v))
    #define  FLD_MRD_SDMA_WT_WM(v)                                (FLD_MRD(16, 19, v))
    #define  SET_SDMA_WT_WM(v, idx)                               OP_FLD_WR(REG_SDMA_BUF(idx), 16, 19, v)
    #define  GET_SDMA_WT_WM(idx)                                  OP_FLD_RD(REG_SDMA_BUF(idx), 16, 19)
    #define  RST_SDMA_WT_WM(idx)                                  OP_FLD_WR(REG_SDMA_BUF(idx), 16, 19, 0x4)

    //Write-Register Using Field-Name
    #define  WRF_SDMA_BUF(BLK_SIZE,RD_WM,WT_WM,idx) \
                (WR_SDMA_BUF( \
                  (FLD_MWD_SDMA_BLK_SIZE(BLK_SIZE))                                    | \
                  (FLD_MWD_SDMA_RD_WM(RD_WM))                                          | \
                  (FLD_MWD_SDMA_WT_WM(WT_WM))                                            \
                 ,idx \
                ))



#endif /*__LIGHTELF_SDMA_REG_H__*/
// vim:ft=c:nowrap:noma
