/*
 * Copyright (c) 2006-2015 Triductor Technology, Inc.
 *           All Rights Reserved Worldwide
 *
 * Filename: lightelf_gpio_reg.h
 * Author  : $Author: Pmeng $
 * Date    : Jun/01/2015
 * Version : $Revision: 2722 $
 * Purpose : Describe all the available registers for GPIO of LIGHTELF.
             This file is automatically generated by Register Parser.
 */

#ifndef __LIGHTELF_GPIO_REG_H__
#define __LIGHTELF_GPIO_REG_H__

#ifndef REG32
    #define REG32(x)                    (*(volatile unsigned int *)(x))
#endif

#ifndef _REG_FLD_OP_
    #define _REG_FLD_OP_

    // Register Field Mask
    #define FLD_MASK(s,e)              ((0xffffffff >> (31-(e)+(s))) << (s))

    // Register Field Mask Write-Data
    // s -- Start of Bit  e -- End   of Bit
    // v -- Value
    #define FLD_MWD(s,e,v)              (((v) << (s)) & FLD_MASK((s),(e)))

    // Register Field Mask Read-Data
    // s -- Start of Bit  e -- End   of Bit
    // v -- Value
    #define FLD_MRD(s,e,v)              (((v) & FLD_MASK((s),(e))) >> (s))

    // Register Field Write operation
    // a -- Address   s -- Start of Bit
    // v -- Value     e -- End   of Bit
    #define OP_FLD_WR(a,s,e,v)          (REG32((a)) = (((v) << (s)) & FLD_MASK((s),(e))) | (REG32((a)) & ~FLD_MASK((s),(e))))
    #define OP_FLD_WR_EXC(a,s,e,v)      (REG32((a)) = (((v) << (s)) & FLD_MASK((s),(e))))

    // Register Field Read operation
    #define OP_FLD_RD(a,s,e)            ((REG32((a)) & FLD_MASK((s),(e))) >> (s))

#endif

//Address Offset for multi-instance mode only
#ifndef  REG_OFFSET_GPIO
    #define  REG_OFFSET_GPIO  (0x0)
#endif

// Base address
#ifndef REG_BASE_GPIO
    #define  REG_BASE_GPIO    (0xf2100000)
#endif



//------------------------------------
// GPIO I/O Registers
//------------------------------------
#define  REG_GPIO_GPIO_DIN                                        (REG_BASE_GPIO + 0x00)
    //Read/Write-Register Using Address
    #define  RD_GPIO_GPIO_DIN()                                   (REG32(REG_GPIO_GPIO_DIN))
    #define  WR_GPIO_GPIO_DIN(v)                                  (REG32(REG_GPIO_GPIO_DIN) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_GPIO_GPIO_DIN()                            (0xFFFFFFFF)  
    #define  REG_WMASK_GPIO_GPIO_DIN()                            (0x0)

    //Field: GPIO_GPIO_DIN
    #define  FLD_LSB_GPIO_GPIO_DIN()                              (0)
    #define  FLD_MSB_GPIO_GPIO_DIN()                              (31)
    #define  FLD_MASK_GPIO_GPIO_DIN()                             (FLD_MASK(0, 31))
    #define  FLD_MWD_GPIO_GPIO_DIN(v)                             (FLD_MWD(0, 31, v))
    #define  FLD_MRD_GPIO_GPIO_DIN(v)                             (FLD_MRD(0, 31, v))
    #define  GET_GPIO_GPIO_DIN()                                  OP_FLD_RD(REG_GPIO_GPIO_DIN, 0, 31)

    //Write-Register Using Field-Name
    #define  WRF_GPIO_GPIO_DIN(GPIO_DIN) \
                (WR_GPIO_GPIO_DIN( \
   \
                ))


#define  REG_GPIO_GPIO_DOUT                                       (REG_BASE_GPIO + 0x04)
    //Read/Write-Register Using Address
    #define  RD_GPIO_GPIO_DOUT()                                  (REG32(REG_GPIO_GPIO_DOUT))
    #define  WR_GPIO_GPIO_DOUT(v)                                 (REG32(REG_GPIO_GPIO_DOUT) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_GPIO_GPIO_DOUT()                           (0xFFFFFFFF)  
    #define  REG_WMASK_GPIO_GPIO_DOUT()                           (0xFFFFFFFF)

    //Field: GPIO_GPIO_DOUT
    #define  FLD_LSB_GPIO_GPIO_DOUT()                             (0)
    #define  FLD_MSB_GPIO_GPIO_DOUT()                             (31)
    #define  FLD_MASK_GPIO_GPIO_DOUT()                            (FLD_MASK(0, 31))
    #define  FLD_MWD_GPIO_GPIO_DOUT(v)                            (FLD_MWD(0, 31, v))
    #define  FLD_MRD_GPIO_GPIO_DOUT(v)                            (FLD_MRD(0, 31, v))
    #define  SET_GPIO_GPIO_DOUT(v)                                OP_FLD_WR_EXC(REG_GPIO_GPIO_DOUT, 0, 31, v)
    #define  GET_GPIO_GPIO_DOUT()                                 OP_FLD_RD(REG_GPIO_GPIO_DOUT, 0, 31)
    #define  RST_GPIO_GPIO_DOUT()                                 OP_FLD_WR_EXC(REG_GPIO_GPIO_DOUT, 0, 31, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_GPIO_GPIO_DOUT(GPIO_DOUT) \
                (WR_GPIO_GPIO_DOUT( \
                  (FLD_MWD_GPIO_GPIO_DOUT(GPIO_DOUT))                                    \
                ))


#define  REG_GPIO_GPIO_CTRL                                       (REG_BASE_GPIO + 0x08)
    //Read/Write-Register Using Address
    #define  RD_GPIO_GPIO_CTRL()                                  (REG32(REG_GPIO_GPIO_CTRL))
    #define  WR_GPIO_GPIO_CTRL(v)                                 (REG32(REG_GPIO_GPIO_CTRL) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_GPIO_GPIO_CTRL()                           (0xFFFFFFFF)  
    #define  REG_WMASK_GPIO_GPIO_CTRL()                           (0xFFFFFFFF)

    //Field: GPIO_GPIO_CTRL
    #define  FLD_LSB_GPIO_GPIO_CTRL()                             (0)
    #define  FLD_MSB_GPIO_GPIO_CTRL()                             (31)
    #define  FLD_MASK_GPIO_GPIO_CTRL()                            (FLD_MASK(0, 31))
    #define  FLD_MWD_GPIO_GPIO_CTRL(v)                            (FLD_MWD(0, 31, v))
    #define  FLD_MRD_GPIO_GPIO_CTRL(v)                            (FLD_MRD(0, 31, v))
    #define  SET_GPIO_GPIO_CTRL(v)                                OP_FLD_WR_EXC(REG_GPIO_GPIO_CTRL, 0, 31, v)
    #define  GET_GPIO_GPIO_CTRL()                                 OP_FLD_RD(REG_GPIO_GPIO_CTRL, 0, 31)
    #define  RST_GPIO_GPIO_CTRL()                                 OP_FLD_WR_EXC(REG_GPIO_GPIO_CTRL, 0, 31, 0xffffffff)

    //Write-Register Using Field-Name
    #define  WRF_GPIO_GPIO_CTRL(GPIO_CTRL) \
                (WR_GPIO_GPIO_CTRL( \
                  (FLD_MWD_GPIO_GPIO_CTRL(GPIO_CTRL))                                    \
                ))


#define  REG_GPIO_REG_BUS_CLK_CFG                                 (REG_BASE_GPIO + 0x0c)
    //Read/Write-Register Using Address
    #define  RD_GPIO_REG_BUS_CLK_CFG()                            (REG32(REG_GPIO_REG_BUS_CLK_CFG))
    #define  WR_GPIO_REG_BUS_CLK_CFG(v)                           (REG32(REG_GPIO_REG_BUS_CLK_CFG) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_GPIO_REG_BUS_CLK_CFG()                     (0x1)  
    #define  REG_WMASK_GPIO_REG_BUS_CLK_CFG()                     (0x1)

    //Field: GPIO_REG_BUS_CLK_GATE_MODE
    #define  FLD_LSB_GPIO_REG_BUS_CLK_GATE_MODE()                 (0)
    #define  FLD_MSB_GPIO_REG_BUS_CLK_GATE_MODE()                 (0)
    #define  FLD_MASK_GPIO_REG_BUS_CLK_GATE_MODE()                (FLD_MASK(0, 0))
    #define  FLD_MWD_GPIO_REG_BUS_CLK_GATE_MODE(v)                (FLD_MWD(0, 0, v))
    #define  FLD_MRD_GPIO_REG_BUS_CLK_GATE_MODE(v)                (FLD_MRD(0, 0, v))
    #define  SET_GPIO_REG_BUS_CLK_GATE_MODE(v)                    OP_FLD_WR_EXC(REG_GPIO_REG_BUS_CLK_CFG, 0, 0, v)
    #define  GET_GPIO_REG_BUS_CLK_GATE_MODE()                     OP_FLD_RD(REG_GPIO_REG_BUS_CLK_CFG, 0, 0)
    #define  RST_GPIO_REG_BUS_CLK_GATE_MODE()                     OP_FLD_WR_EXC(REG_GPIO_REG_BUS_CLK_CFG, 0, 0, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_GPIO_REG_BUS_CLK_CFG(REG_BUS_CLK_GATE_MODE) \
                (WR_GPIO_REG_BUS_CLK_CFG( \
                  (FLD_MWD_GPIO_REG_BUS_CLK_GATE_MODE(REG_BUS_CLK_GATE_MODE))            \
                ))


//------------------------------------
// GPIO External Interrupt Registers
//------------------------------------
#define  REG_GPIO_EXT_INT_EN                                      (REG_BASE_GPIO + 0x10)
    //Read/Write-Register Using Address
    #define  RD_GPIO_EXT_INT_EN()                                 (REG32(REG_GPIO_EXT_INT_EN))
    #define  WR_GPIO_EXT_INT_EN(v)                                (REG32(REG_GPIO_EXT_INT_EN) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_GPIO_EXT_INT_EN()                          (0xFFFFFFFF)  
    #define  REG_WMASK_GPIO_EXT_INT_EN()                          (0xFFFFFFFF)

    //Field: GPIO_GPIO_EINT_EN
    #define  FLD_LSB_GPIO_GPIO_EINT_EN()                          (0)
    #define  FLD_MSB_GPIO_GPIO_EINT_EN()                          (31)
    #define  FLD_MASK_GPIO_GPIO_EINT_EN()                         (FLD_MASK(0, 31))
    #define  FLD_MWD_GPIO_GPIO_EINT_EN(v)                         (FLD_MWD(0, 31, v))
    #define  FLD_MRD_GPIO_GPIO_EINT_EN(v)                         (FLD_MRD(0, 31, v))
    #define  SET_GPIO_GPIO_EINT_EN(v)                             OP_FLD_WR_EXC(REG_GPIO_EXT_INT_EN, 0, 31, v)
    #define  GET_GPIO_GPIO_EINT_EN()                              OP_FLD_RD(REG_GPIO_EXT_INT_EN, 0, 31)
    #define  RST_GPIO_GPIO_EINT_EN()                              OP_FLD_WR_EXC(REG_GPIO_EXT_INT_EN, 0, 31, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_GPIO_EXT_INT_EN(GPIO_EINT_EN) \
                (WR_GPIO_EXT_INT_EN( \
                  (FLD_MWD_GPIO_GPIO_EINT_EN(GPIO_EINT_EN))                              \
                ))


#define  REG_GPIO_EXT_INT_NEG                                     (REG_BASE_GPIO + 0x14)
    //Read/Write-Register Using Address
    #define  RD_GPIO_EXT_INT_NEG()                                (REG32(REG_GPIO_EXT_INT_NEG))
    #define  WR_GPIO_EXT_INT_NEG(v)                               (REG32(REG_GPIO_EXT_INT_NEG) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_GPIO_EXT_INT_NEG()                         (0xFFFFFFFF)  
    #define  REG_WMASK_GPIO_EXT_INT_NEG()                         (0xFFFFFFFF)

    //Field: GPIO_GPIO_EINT_NEG
    #define  FLD_LSB_GPIO_GPIO_EINT_NEG()                         (0)
    #define  FLD_MSB_GPIO_GPIO_EINT_NEG()                         (31)
    #define  FLD_MASK_GPIO_GPIO_EINT_NEG()                        (FLD_MASK(0, 31))
    #define  FLD_MWD_GPIO_GPIO_EINT_NEG(v)                        (FLD_MWD(0, 31, v))
    #define  FLD_MRD_GPIO_GPIO_EINT_NEG(v)                        (FLD_MRD(0, 31, v))
    #define  SET_GPIO_GPIO_EINT_NEG(v)                            OP_FLD_WR_EXC(REG_GPIO_EXT_INT_NEG, 0, 31, v)
    #define  GET_GPIO_GPIO_EINT_NEG()                             OP_FLD_RD(REG_GPIO_EXT_INT_NEG, 0, 31)
    #define  RST_GPIO_GPIO_EINT_NEG()                             OP_FLD_WR_EXC(REG_GPIO_EXT_INT_NEG, 0, 31, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_GPIO_EXT_INT_NEG(GPIO_EINT_NEG) \
                (WR_GPIO_EXT_INT_NEG( \
                  (FLD_MWD_GPIO_GPIO_EINT_NEG(GPIO_EINT_NEG))                            \
                ))


#define  REG_GPIO_EXT_INT_EDGE                                    (REG_BASE_GPIO + 0x18)
    //Read/Write-Register Using Address
    #define  RD_GPIO_EXT_INT_EDGE()                               (REG32(REG_GPIO_EXT_INT_EDGE))
    #define  WR_GPIO_EXT_INT_EDGE(v)                              (REG32(REG_GPIO_EXT_INT_EDGE) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_GPIO_EXT_INT_EDGE()                        (0xFFFFFFFF)  
    #define  REG_WMASK_GPIO_EXT_INT_EDGE()                        (0xFFFFFFFF)

    //Field: GPIO_GPIO_EINT_EDGE
    #define  FLD_LSB_GPIO_GPIO_EINT_EDGE()                        (0)
    #define  FLD_MSB_GPIO_GPIO_EINT_EDGE()                        (31)
    #define  FLD_MASK_GPIO_GPIO_EINT_EDGE()                       (FLD_MASK(0, 31))
    #define  FLD_MWD_GPIO_GPIO_EINT_EDGE(v)                       (FLD_MWD(0, 31, v))
    #define  FLD_MRD_GPIO_GPIO_EINT_EDGE(v)                       (FLD_MRD(0, 31, v))
    #define  SET_GPIO_GPIO_EINT_EDGE(v)                           OP_FLD_WR_EXC(REG_GPIO_EXT_INT_EDGE, 0, 31, v)
    #define  GET_GPIO_GPIO_EINT_EDGE()                            OP_FLD_RD(REG_GPIO_EXT_INT_EDGE, 0, 31)
    #define  RST_GPIO_GPIO_EINT_EDGE()                            OP_FLD_WR_EXC(REG_GPIO_EXT_INT_EDGE, 0, 31, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_GPIO_EXT_INT_EDGE(GPIO_EINT_EDGE) \
                (WR_GPIO_EXT_INT_EDGE( \
                  (FLD_MWD_GPIO_GPIO_EINT_EDGE(GPIO_EINT_EDGE))                          \
                ))


#define  REG_GPIO_EXT_INT_STATUS                                  (REG_BASE_GPIO + 0x1c)
    //Read/Write-Register Using Address
    #define  RD_GPIO_EXT_INT_STATUS()                             (REG32(REG_GPIO_EXT_INT_STATUS))
    #define  WR_GPIO_EXT_INT_STATUS(v)                            (REG32(REG_GPIO_EXT_INT_STATUS) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_GPIO_EXT_INT_STATUS()                      (0xFFFFFFFF)  
    #define  REG_WMASK_GPIO_EXT_INT_STATUS()                      (0x0)

    //Field: GPIO_GPIO_EINT_STA
    #define  FLD_LSB_GPIO_GPIO_EINT_STA()                         (0)
    #define  FLD_MSB_GPIO_GPIO_EINT_STA()                         (31)
    #define  FLD_MASK_GPIO_GPIO_EINT_STA()                        (FLD_MASK(0, 31))
    #define  FLD_MWD_GPIO_GPIO_EINT_STA(v)                        (FLD_MWD(0, 31, v))
    #define  FLD_MRD_GPIO_GPIO_EINT_STA(v)                        (FLD_MRD(0, 31, v))
    #define  GET_GPIO_GPIO_EINT_STA()                             OP_FLD_RD(REG_GPIO_EXT_INT_STATUS, 0, 31)
    #define  RST_GPIO_GPIO_EINT_STA()                             OP_FLD_RD(REG_GPIO_EXT_INT_STATUS, 0, 31)

    //Write-Register Using Field-Name
    #define  WRF_GPIO_EXT_INT_STATUS(GPIO_EINT_STA) \
                (WR_GPIO_EXT_INT_STATUS( \
   \
                ))


//------------------------------------
// GPIO Share I/O Registers
//------------------------------------
#define  REG_GPIO_GPIO_SHARE_EN0                                  (REG_BASE_GPIO + 0x40)
    //Read/Write-Register Using Address
    #define  RD_GPIO_GPIO_SHARE_EN0()                             (REG32(REG_GPIO_GPIO_SHARE_EN0))
    #define  WR_GPIO_GPIO_SHARE_EN0(v)                            (REG32(REG_GPIO_GPIO_SHARE_EN0) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_GPIO_GPIO_SHARE_EN0()                      (0xFFFFFFFF)  
    #define  REG_WMASK_GPIO_GPIO_SHARE_EN0()                      (0xFFFFFFFF)

    //Field: GPIO_GPIO_SS0_EN
    #define  FLD_LSB_GPIO_GPIO_SS0_EN()                           (0)
    #define  FLD_MSB_GPIO_GPIO_SS0_EN()                           (0)
    #define  FLD_MASK_GPIO_GPIO_SS0_EN()                          (FLD_MASK(0, 0))
    #define  FLD_MWD_GPIO_GPIO_SS0_EN(v)                          (FLD_MWD(0, 0, v))
    #define  FLD_MRD_GPIO_GPIO_SS0_EN(v)                          (FLD_MRD(0, 0, v))
    #define  SET_GPIO_GPIO_SS0_EN(v)                              OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 0, 0, v)
    #define  GET_GPIO_GPIO_SS0_EN()                               OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 0, 0)
    #define  RST_GPIO_GPIO_SS0_EN()                               OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 0, 0, 0x1)

    //Field: GPIO_GPIO_SS1_EN
    #define  FLD_LSB_GPIO_GPIO_SS1_EN()                           (1)
    #define  FLD_MSB_GPIO_GPIO_SS1_EN()                           (1)
    #define  FLD_MASK_GPIO_GPIO_SS1_EN()                          (FLD_MASK(1, 1))
    #define  FLD_MWD_GPIO_GPIO_SS1_EN(v)                          (FLD_MWD(1, 1, v))
    #define  FLD_MRD_GPIO_GPIO_SS1_EN(v)                          (FLD_MRD(1, 1, v))
    #define  SET_GPIO_GPIO_SS1_EN(v)                              OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 1, 1, v)
    #define  GET_GPIO_GPIO_SS1_EN()                               OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 1, 1)
    #define  RST_GPIO_GPIO_SS1_EN()                               OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 1, 1, 0x0)

    //Field: GPIO_GPIO_SS2_EN
    #define  FLD_LSB_GPIO_GPIO_SS2_EN()                           (2)
    #define  FLD_MSB_GPIO_GPIO_SS2_EN()                           (2)
    #define  FLD_MASK_GPIO_GPIO_SS2_EN()                          (FLD_MASK(2, 2))
    #define  FLD_MWD_GPIO_GPIO_SS2_EN(v)                          (FLD_MWD(2, 2, v))
    #define  FLD_MRD_GPIO_GPIO_SS2_EN(v)                          (FLD_MRD(2, 2, v))
    #define  SET_GPIO_GPIO_SS2_EN(v)                              OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 2, 2, v)
    #define  GET_GPIO_GPIO_SS2_EN()                               OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 2, 2)
    #define  RST_GPIO_GPIO_SS2_EN()                               OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 2, 2, 0x0)

    //Field: GPIO_GPIO_SS3_EN
    #define  FLD_LSB_GPIO_GPIO_SS3_EN()                           (3)
    #define  FLD_MSB_GPIO_GPIO_SS3_EN()                           (3)
    #define  FLD_MASK_GPIO_GPIO_SS3_EN()                          (FLD_MASK(3, 3))
    #define  FLD_MWD_GPIO_GPIO_SS3_EN(v)                          (FLD_MWD(3, 3, v))
    #define  FLD_MRD_GPIO_GPIO_SS3_EN(v)                          (FLD_MRD(3, 3, v))
    #define  SET_GPIO_GPIO_SS3_EN(v)                              OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 3, 3, v)
    #define  GET_GPIO_GPIO_SS3_EN()                               OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 3, 3)
    #define  RST_GPIO_GPIO_SS3_EN()                               OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 3, 3, 0x0)

    //Field: GPIO_GPIO_UART0_EN
    #define  FLD_LSB_GPIO_GPIO_UART0_EN()                         (4)
    #define  FLD_MSB_GPIO_GPIO_UART0_EN()                         (4)
    #define  FLD_MASK_GPIO_GPIO_UART0_EN()                        (FLD_MASK(4, 4))
    #define  FLD_MWD_GPIO_GPIO_UART0_EN(v)                        (FLD_MWD(4, 4, v))
    #define  FLD_MRD_GPIO_GPIO_UART0_EN(v)                        (FLD_MRD(4, 4, v))
    #define  SET_GPIO_GPIO_UART0_EN(v)                            OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 4, 4, v)
    #define  GET_GPIO_GPIO_UART0_EN()                             OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 4, 4)
    #define  RST_GPIO_GPIO_UART0_EN()                             OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 4, 4, 0x1)

    //Field: GPIO_GPIO_UART1_EN
    #define  FLD_LSB_GPIO_GPIO_UART1_EN()                         (5)
    #define  FLD_MSB_GPIO_GPIO_UART1_EN()                         (5)
    #define  FLD_MASK_GPIO_GPIO_UART1_EN()                        (FLD_MASK(5, 5))
    #define  FLD_MWD_GPIO_GPIO_UART1_EN(v)                        (FLD_MWD(5, 5, v))
    #define  FLD_MRD_GPIO_GPIO_UART1_EN(v)                        (FLD_MRD(5, 5, v))
    #define  SET_GPIO_GPIO_UART1_EN(v)                            OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 5, 5, v)
    #define  GET_GPIO_GPIO_UART1_EN()                             OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 5, 5)
    #define  RST_GPIO_GPIO_UART1_EN()                             OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 5, 5, 0x0)

    //Field: GPIO_GPIO_UART2_EN
    #define  FLD_LSB_GPIO_GPIO_UART2_EN()                         (6)
    #define  FLD_MSB_GPIO_GPIO_UART2_EN()                         (6)
    #define  FLD_MASK_GPIO_GPIO_UART2_EN()                        (FLD_MASK(6, 6))
    #define  FLD_MWD_GPIO_GPIO_UART2_EN(v)                        (FLD_MWD(6, 6, v))
    #define  FLD_MRD_GPIO_GPIO_UART2_EN(v)                        (FLD_MRD(6, 6, v))
    #define  SET_GPIO_GPIO_UART2_EN(v)                            OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 6, 6, v)
    #define  GET_GPIO_GPIO_UART2_EN()                             OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 6, 6)
    #define  RST_GPIO_GPIO_UART2_EN()                             OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 6, 6, 0x0)

    //Field: GPIO_GPIO_I2C_EN
    #define  FLD_LSB_GPIO_GPIO_I2C_EN()                           (7)
    #define  FLD_MSB_GPIO_GPIO_I2C_EN()                           (7)
    #define  FLD_MASK_GPIO_GPIO_I2C_EN()                          (FLD_MASK(7, 7))
    #define  FLD_MWD_GPIO_GPIO_I2C_EN(v)                          (FLD_MWD(7, 7, v))
    #define  FLD_MRD_GPIO_GPIO_I2C_EN(v)                          (FLD_MRD(7, 7, v))
    #define  SET_GPIO_GPIO_I2C_EN(v)                              OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 7, 7, v)
    #define  GET_GPIO_GPIO_I2C_EN()                               OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 7, 7)
    #define  RST_GPIO_GPIO_I2C_EN()                               OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 7, 7, 0x0)

    //Field: GPIO_GPIO_LD0_EN
    #define  FLD_LSB_GPIO_GPIO_LD0_EN()                           (8)
    #define  FLD_MSB_GPIO_GPIO_LD0_EN()                           (8)
    #define  FLD_MASK_GPIO_GPIO_LD0_EN()                          (FLD_MASK(8, 8))
    #define  FLD_MWD_GPIO_GPIO_LD0_EN(v)                          (FLD_MWD(8, 8, v))
    #define  FLD_MRD_GPIO_GPIO_LD0_EN(v)                          (FLD_MRD(8, 8, v))
    #define  SET_GPIO_GPIO_LD0_EN(v)                              OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 8, 8, v)
    #define  GET_GPIO_GPIO_LD0_EN()                               OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 8, 8)
    #define  RST_GPIO_GPIO_LD0_EN()                               OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 8, 8, 0x0)

    //Field: GPIO_GPIO_LD1_EN
    #define  FLD_LSB_GPIO_GPIO_LD1_EN()                           (9)
    #define  FLD_MSB_GPIO_GPIO_LD1_EN()                           (9)
    #define  FLD_MASK_GPIO_GPIO_LD1_EN()                          (FLD_MASK(9, 9))
    #define  FLD_MWD_GPIO_GPIO_LD1_EN(v)                          (FLD_MWD(9, 9, v))
    #define  FLD_MRD_GPIO_GPIO_LD1_EN(v)                          (FLD_MRD(9, 9, v))
    #define  SET_GPIO_GPIO_LD1_EN(v)                              OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 9, 9, v)
    #define  GET_GPIO_GPIO_LD1_EN()                               OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 9, 9)
    #define  RST_GPIO_GPIO_LD1_EN()                               OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 9, 9, 0x0)

    //Field: GPIO_GPIO_LD2_EN
    #define  FLD_LSB_GPIO_GPIO_LD2_EN()                           (10)
    #define  FLD_MSB_GPIO_GPIO_LD2_EN()                           (10)
    #define  FLD_MASK_GPIO_GPIO_LD2_EN()                          (FLD_MASK(10, 10))
    #define  FLD_MWD_GPIO_GPIO_LD2_EN(v)                          (FLD_MWD(10, 10, v))
    #define  FLD_MRD_GPIO_GPIO_LD2_EN(v)                          (FLD_MRD(10, 10, v))
    #define  SET_GPIO_GPIO_LD2_EN(v)                              OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 10, 10, v)
    #define  GET_GPIO_GPIO_LD2_EN()                               OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 10, 10)
    #define  RST_GPIO_GPIO_LD2_EN()                               OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 10, 10, 0x0)

    //Field: GPIO_GPIO_LD3_EN
    #define  FLD_LSB_GPIO_GPIO_LD3_EN()                           (11)
    #define  FLD_MSB_GPIO_GPIO_LD3_EN()                           (11)
    #define  FLD_MASK_GPIO_GPIO_LD3_EN()                          (FLD_MASK(11, 11))
    #define  FLD_MWD_GPIO_GPIO_LD3_EN(v)                          (FLD_MWD(11, 11, v))
    #define  FLD_MRD_GPIO_GPIO_LD3_EN(v)                          (FLD_MRD(11, 11, v))
    #define  SET_GPIO_GPIO_LD3_EN(v)                              OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 11, 11, v)
    #define  GET_GPIO_GPIO_LD3_EN()                               OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 11, 11)
    #define  RST_GPIO_GPIO_LD3_EN()                               OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 11, 11, 0x0)

    //Field: GPIO_GPIO_TICK0_EN
    #define  FLD_LSB_GPIO_GPIO_TICK0_EN()                         (12)
    #define  FLD_MSB_GPIO_GPIO_TICK0_EN()                         (12)
    #define  FLD_MASK_GPIO_GPIO_TICK0_EN()                        (FLD_MASK(12, 12))
    #define  FLD_MWD_GPIO_GPIO_TICK0_EN(v)                        (FLD_MWD(12, 12, v))
    #define  FLD_MRD_GPIO_GPIO_TICK0_EN(v)                        (FLD_MRD(12, 12, v))
    #define  SET_GPIO_GPIO_TICK0_EN(v)                            OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 12, 12, v)
    #define  GET_GPIO_GPIO_TICK0_EN()                             OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 12, 12)
    #define  RST_GPIO_GPIO_TICK0_EN()                             OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 12, 12, 0x0)

    //Field: GPIO_GPIO_TICK1_EN
    #define  FLD_LSB_GPIO_GPIO_TICK1_EN()                         (13)
    #define  FLD_MSB_GPIO_GPIO_TICK1_EN()                         (13)
    #define  FLD_MASK_GPIO_GPIO_TICK1_EN()                        (FLD_MASK(13, 13))
    #define  FLD_MWD_GPIO_GPIO_TICK1_EN(v)                        (FLD_MWD(13, 13, v))
    #define  FLD_MRD_GPIO_GPIO_TICK1_EN(v)                        (FLD_MRD(13, 13, v))
    #define  SET_GPIO_GPIO_TICK1_EN(v)                            OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 13, 13, v)
    #define  GET_GPIO_GPIO_TICK1_EN()                             OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 13, 13)
    #define  RST_GPIO_GPIO_TICK1_EN()                             OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 13, 13, 0x0)

    //Field: GPIO_GPIO_TICK2_EN
    #define  FLD_LSB_GPIO_GPIO_TICK2_EN()                         (14)
    #define  FLD_MSB_GPIO_GPIO_TICK2_EN()                         (14)
    #define  FLD_MASK_GPIO_GPIO_TICK2_EN()                        (FLD_MASK(14, 14))
    #define  FLD_MWD_GPIO_GPIO_TICK2_EN(v)                        (FLD_MWD(14, 14, v))
    #define  FLD_MRD_GPIO_GPIO_TICK2_EN(v)                        (FLD_MRD(14, 14, v))
    #define  SET_GPIO_GPIO_TICK2_EN(v)                            OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 14, 14, v)
    #define  GET_GPIO_GPIO_TICK2_EN()                             OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 14, 14)
    #define  RST_GPIO_GPIO_TICK2_EN()                             OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 14, 14, 0x0)

    //Field: GPIO_GPIO_TICK3_EN
    #define  FLD_LSB_GPIO_GPIO_TICK3_EN()                         (15)
    #define  FLD_MSB_GPIO_GPIO_TICK3_EN()                         (15)
    #define  FLD_MASK_GPIO_GPIO_TICK3_EN()                        (FLD_MASK(15, 15))
    #define  FLD_MWD_GPIO_GPIO_TICK3_EN(v)                        (FLD_MWD(15, 15, v))
    #define  FLD_MRD_GPIO_GPIO_TICK3_EN(v)                        (FLD_MRD(15, 15, v))
    #define  SET_GPIO_GPIO_TICK3_EN(v)                            OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 15, 15, v)
    #define  GET_GPIO_GPIO_TICK3_EN()                             OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 15, 15)
    #define  RST_GPIO_GPIO_TICK3_EN()                             OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 15, 15, 0x0)

    //Field: GPIO_GPIO_GE_EN
    #define  FLD_LSB_GPIO_GPIO_GE_EN()                            (16)
    #define  FLD_MSB_GPIO_GPIO_GE_EN()                            (16)
    #define  FLD_MASK_GPIO_GPIO_GE_EN()                           (FLD_MASK(16, 16))
    #define  FLD_MWD_GPIO_GPIO_GE_EN(v)                           (FLD_MWD(16, 16, v))
    #define  FLD_MRD_GPIO_GPIO_GE_EN(v)                           (FLD_MRD(16, 16, v))
    #define  SET_GPIO_GPIO_GE_EN(v)                               OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 16, 16, v)
    #define  GET_GPIO_GPIO_GE_EN()                                OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 16, 16)
    #define  RST_GPIO_GPIO_GE_EN()                                OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 16, 16, 0x1)

    //Field: GPIO_GPIO_JTAG_EN
    #define  FLD_LSB_GPIO_GPIO_JTAG_EN()                          (17)
    #define  FLD_MSB_GPIO_GPIO_JTAG_EN()                          (17)
    #define  FLD_MASK_GPIO_GPIO_JTAG_EN()                         (FLD_MASK(17, 17))
    #define  FLD_MWD_GPIO_GPIO_JTAG_EN(v)                         (FLD_MWD(17, 17, v))
    #define  FLD_MRD_GPIO_GPIO_JTAG_EN(v)                         (FLD_MRD(17, 17, v))
    #define  SET_GPIO_GPIO_JTAG_EN(v)                             OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 17, 17, v)
    #define  GET_GPIO_GPIO_JTAG_EN()                              OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 17, 17)
    #define  RST_GPIO_GPIO_JTAG_EN()                              OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 17, 17, 0x1)

    //Field: GPIO_GPIO_MDIO_EN
    #define  FLD_LSB_GPIO_GPIO_MDIO_EN()                          (18)
    #define  FLD_MSB_GPIO_GPIO_MDIO_EN()                          (18)
    #define  FLD_MASK_GPIO_GPIO_MDIO_EN()                         (FLD_MASK(18, 18))
    #define  FLD_MWD_GPIO_GPIO_MDIO_EN(v)                         (FLD_MWD(18, 18, v))
    #define  FLD_MRD_GPIO_GPIO_MDIO_EN(v)                         (FLD_MRD(18, 18, v))
    #define  SET_GPIO_GPIO_MDIO_EN(v)                             OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 18, 18, v)
    #define  GET_GPIO_GPIO_MDIO_EN()                              OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 18, 18)
    #define  RST_GPIO_GPIO_MDIO_EN()                              OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 18, 18, 0x1)

    //Field: GPIO_GPIO_WDT_EN
    #define  FLD_LSB_GPIO_GPIO_WDT_EN()                           (19)
    #define  FLD_MSB_GPIO_GPIO_WDT_EN()                           (19)
    #define  FLD_MASK_GPIO_GPIO_WDT_EN()                          (FLD_MASK(19, 19))
    #define  FLD_MWD_GPIO_GPIO_WDT_EN(v)                          (FLD_MWD(19, 19, v))
    #define  FLD_MRD_GPIO_GPIO_WDT_EN(v)                          (FLD_MRD(19, 19, v))
    #define  SET_GPIO_GPIO_WDT_EN(v)                              OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 19, 19, v)
    #define  GET_GPIO_GPIO_WDT_EN()                               OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 19, 19)
    #define  RST_GPIO_GPIO_WDT_EN()                               OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 19, 19, 0x0)

    //Field: GPIO_GPIO_ZC0_EN
    #define  FLD_LSB_GPIO_GPIO_ZC0_EN()                           (20)
    #define  FLD_MSB_GPIO_GPIO_ZC0_EN()                           (20)
    #define  FLD_MASK_GPIO_GPIO_ZC0_EN()                          (FLD_MASK(20, 20))
    #define  FLD_MWD_GPIO_GPIO_ZC0_EN(v)                          (FLD_MWD(20, 20, v))
    #define  FLD_MRD_GPIO_GPIO_ZC0_EN(v)                          (FLD_MRD(20, 20, v))
    #define  SET_GPIO_GPIO_ZC0_EN(v)                              OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 20, 20, v)
    #define  GET_GPIO_GPIO_ZC0_EN()                               OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 20, 20)
    #define  RST_GPIO_GPIO_ZC0_EN()                               OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 20, 20, 0x0)

    //Field: GPIO_GPIO_ZC1_EN
    #define  FLD_LSB_GPIO_GPIO_ZC1_EN()                           (21)
    #define  FLD_MSB_GPIO_GPIO_ZC1_EN()                           (21)
    #define  FLD_MASK_GPIO_GPIO_ZC1_EN()                          (FLD_MASK(21, 21))
    #define  FLD_MWD_GPIO_GPIO_ZC1_EN(v)                          (FLD_MWD(21, 21, v))
    #define  FLD_MRD_GPIO_GPIO_ZC1_EN(v)                          (FLD_MRD(21, 21, v))
    #define  SET_GPIO_GPIO_ZC1_EN(v)                              OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 21, 21, v)
    #define  GET_GPIO_GPIO_ZC1_EN()                               OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 21, 21)
    #define  RST_GPIO_GPIO_ZC1_EN()                               OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 21, 21, 0x0)

    //Field: GPIO_GPIO_GE_RGMII_EN
    #define  FLD_LSB_GPIO_GPIO_GE_RGMII_EN()                      (22)
    #define  FLD_MSB_GPIO_GPIO_GE_RGMII_EN()                      (22)
    #define  FLD_MASK_GPIO_GPIO_GE_RGMII_EN()                     (FLD_MASK(22, 22))
    #define  FLD_MWD_GPIO_GPIO_GE_RGMII_EN(v)                     (FLD_MWD(22, 22, v))
    #define  FLD_MRD_GPIO_GPIO_GE_RGMII_EN(v)                     (FLD_MRD(22, 22, v))
    #define  SET_GPIO_GPIO_GE_RGMII_EN(v)                         OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 22, 22, v)
    #define  GET_GPIO_GPIO_GE_RGMII_EN()                          OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 22, 22)
    #define  RST_GPIO_GPIO_GE_RGMII_EN()                          OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 22, 22, 0x0)

    //Field: GPIO_GPIO_GE_MII_EN
    #define  FLD_LSB_GPIO_GPIO_GE_MII_EN()                        (23)
    #define  FLD_MSB_GPIO_GPIO_GE_MII_EN()                        (23)
    #define  FLD_MASK_GPIO_GPIO_GE_MII_EN()                       (FLD_MASK(23, 23))
    #define  FLD_MWD_GPIO_GPIO_GE_MII_EN(v)                       (FLD_MWD(23, 23, v))
    #define  FLD_MRD_GPIO_GPIO_GE_MII_EN(v)                       (FLD_MRD(23, 23, v))
    #define  SET_GPIO_GPIO_GE_MII_EN(v)                           OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 23, 23, v)
    #define  GET_GPIO_GPIO_GE_MII_EN()                            OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 23, 23)
    #define  RST_GPIO_GPIO_GE_MII_EN()                            OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 23, 23, 0x0)

    //Field: GPIO_GPIO_SPI_3W
    #define  FLD_LSB_GPIO_GPIO_SPI_3W()                           (24)
    #define  FLD_MSB_GPIO_GPIO_SPI_3W()                           (25)
    #define  FLD_MASK_GPIO_GPIO_SPI_3W()                          (FLD_MASK(24, 25))
    #define  FLD_MWD_GPIO_GPIO_SPI_3W(v)                          (FLD_MWD(24, 25, v))
    #define  FLD_MRD_GPIO_GPIO_SPI_3W(v)                          (FLD_MRD(24, 25, v))
    #define  SET_GPIO_GPIO_SPI_3W(v)                              OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 24, 25, v)
    #define  GET_GPIO_GPIO_SPI_3W()                               OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 24, 25)
    #define  RST_GPIO_GPIO_SPI_3W()                               OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 24, 25, 0x0)

    //Field: GPIO_GPIO_TCK_MC_SYN_EN
    #define  FLD_LSB_GPIO_GPIO_TCK_MC_SYN_EN()                    (26)
    #define  FLD_MSB_GPIO_GPIO_TCK_MC_SYN_EN()                    (26)
    #define  FLD_MASK_GPIO_GPIO_TCK_MC_SYN_EN()                   (FLD_MASK(26, 26))
    #define  FLD_MWD_GPIO_GPIO_TCK_MC_SYN_EN(v)                   (FLD_MWD(26, 26, v))
    #define  FLD_MRD_GPIO_GPIO_TCK_MC_SYN_EN(v)                   (FLD_MRD(26, 26, v))
    #define  SET_GPIO_GPIO_TCK_MC_SYN_EN(v)                       OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 26, 26, v)
    #define  GET_GPIO_GPIO_TCK_MC_SYN_EN()                        OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 26, 26)
    #define  RST_GPIO_GPIO_TCK_MC_SYN_EN()                        OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 26, 26, 0x0)

    //Field: GPIO_GPIO_TCK_OSC_EN
    #define  FLD_LSB_GPIO_GPIO_TCK_OSC_EN()                       (27)
    #define  FLD_MSB_GPIO_GPIO_TCK_OSC_EN()                       (27)
    #define  FLD_MASK_GPIO_GPIO_TCK_OSC_EN()                      (FLD_MASK(27, 27))
    #define  FLD_MWD_GPIO_GPIO_TCK_OSC_EN(v)                      (FLD_MWD(27, 27, v))
    #define  FLD_MRD_GPIO_GPIO_TCK_OSC_EN(v)                      (FLD_MRD(27, 27, v))
    #define  SET_GPIO_GPIO_TCK_OSC_EN(v)                          OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 27, 27, v)
    #define  GET_GPIO_GPIO_TCK_OSC_EN()                           OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 27, 27)
    #define  RST_GPIO_GPIO_TCK_OSC_EN()                           OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 27, 27, 0x1)

    //Field: GPIO_GPIO_TCK_SYS_EN
    #define  FLD_LSB_GPIO_GPIO_TCK_SYS_EN()                       (28)
    #define  FLD_MSB_GPIO_GPIO_TCK_SYS_EN()                       (28)
    #define  FLD_MASK_GPIO_GPIO_TCK_SYS_EN()                      (FLD_MASK(28, 28))
    #define  FLD_MWD_GPIO_GPIO_TCK_SYS_EN(v)                      (FLD_MWD(28, 28, v))
    #define  FLD_MRD_GPIO_GPIO_TCK_SYS_EN(v)                      (FLD_MRD(28, 28, v))
    #define  SET_GPIO_GPIO_TCK_SYS_EN(v)                          OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 28, 28, v)
    #define  GET_GPIO_GPIO_TCK_SYS_EN()                           OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 28, 28)
    #define  RST_GPIO_GPIO_TCK_SYS_EN()                           OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 28, 28, 0x0)

    //Field: GPIO_GPIO_TCK_ADC_EN
    #define  FLD_LSB_GPIO_GPIO_TCK_ADC_EN()                       (29)
    #define  FLD_MSB_GPIO_GPIO_TCK_ADC_EN()                       (29)
    #define  FLD_MASK_GPIO_GPIO_TCK_ADC_EN()                      (FLD_MASK(29, 29))
    #define  FLD_MWD_GPIO_GPIO_TCK_ADC_EN(v)                      (FLD_MWD(29, 29, v))
    #define  FLD_MRD_GPIO_GPIO_TCK_ADC_EN(v)                      (FLD_MRD(29, 29, v))
    #define  SET_GPIO_GPIO_TCK_ADC_EN(v)                          OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 29, 29, v)
    #define  GET_GPIO_GPIO_TCK_ADC_EN()                           OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 29, 29)
    #define  RST_GPIO_GPIO_TCK_ADC_EN()                           OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 29, 29, 0x0)

    //Field: GPIO_GPIO_TCK_DAC_EN
    #define  FLD_LSB_GPIO_GPIO_TCK_DAC_EN()                       (30)
    #define  FLD_MSB_GPIO_GPIO_TCK_DAC_EN()                       (30)
    #define  FLD_MASK_GPIO_GPIO_TCK_DAC_EN()                      (FLD_MASK(30, 30))
    #define  FLD_MWD_GPIO_GPIO_TCK_DAC_EN(v)                      (FLD_MWD(30, 30, v))
    #define  FLD_MRD_GPIO_GPIO_TCK_DAC_EN(v)                      (FLD_MRD(30, 30, v))
    #define  SET_GPIO_GPIO_TCK_DAC_EN(v)                          OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 30, 30, v)
    #define  GET_GPIO_GPIO_TCK_DAC_EN()                           OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 30, 30)
    #define  RST_GPIO_GPIO_TCK_DAC_EN()                           OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 30, 30, 0x0)

    //Field: GPIO_GPIO_TCK_AUX_EN
    #define  FLD_LSB_GPIO_GPIO_TCK_AUX_EN()                       (31)
    #define  FLD_MSB_GPIO_GPIO_TCK_AUX_EN()                       (31)
    #define  FLD_MASK_GPIO_GPIO_TCK_AUX_EN()                      (FLD_MASK(31, 31))
    #define  FLD_MWD_GPIO_GPIO_TCK_AUX_EN(v)                      (FLD_MWD(31, 31, v))
    #define  FLD_MRD_GPIO_GPIO_TCK_AUX_EN(v)                      (FLD_MRD(31, 31, v))
    #define  SET_GPIO_GPIO_TCK_AUX_EN(v)                          OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 31, 31, v)
    #define  GET_GPIO_GPIO_TCK_AUX_EN()                           OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN0, 31, 31)
    #define  RST_GPIO_GPIO_TCK_AUX_EN()                           OP_FLD_WR(REG_GPIO_GPIO_SHARE_EN0, 31, 31, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_GPIO_GPIO_SHARE_EN0(GPIO_SS0_EN,GPIO_SS1_EN,GPIO_SS2_EN,GPIO_SS3_EN,GPIO_UART0_EN,GPIO_UART1_EN,GPIO_UART2_EN,GPIO_I2C_EN,GPIO_LD0_EN,GPIO_LD1_EN,GPIO_LD2_EN,GPIO_LD3_EN,GPIO_TICK0_EN,GPIO_TICK1_EN,GPIO_TICK2_EN,GPIO_TICK3_EN,GPIO_GE_EN,GPIO_JTAG_EN,GPIO_MDIO_EN,GPIO_WDT_EN,GPIO_ZC0_EN,GPIO_ZC1_EN,GPIO_GE_RGMII_EN,GPIO_GE_MII_EN,GPIO_SPI_3W,GPIO_TCK_MC_SYN_EN,GPIO_TCK_OSC_EN,GPIO_TCK_SYS_EN,GPIO_TCK_ADC_EN,GPIO_TCK_DAC_EN,GPIO_TCK_AUX_EN) \
                (WR_GPIO_GPIO_SHARE_EN0( \
                  (FLD_MWD_GPIO_GPIO_SS0_EN(GPIO_SS0_EN))                              | \
                  (FLD_MWD_GPIO_GPIO_SS1_EN(GPIO_SS1_EN))                              | \
                  (FLD_MWD_GPIO_GPIO_SS2_EN(GPIO_SS2_EN))                              | \
                  (FLD_MWD_GPIO_GPIO_SS3_EN(GPIO_SS3_EN))                              | \
                  (FLD_MWD_GPIO_GPIO_UART0_EN(GPIO_UART0_EN))                          | \
                  (FLD_MWD_GPIO_GPIO_UART1_EN(GPIO_UART1_EN))                          | \
                  (FLD_MWD_GPIO_GPIO_UART2_EN(GPIO_UART2_EN))                          | \
                  (FLD_MWD_GPIO_GPIO_I2C_EN(GPIO_I2C_EN))                              | \
                  (FLD_MWD_GPIO_GPIO_LD0_EN(GPIO_LD0_EN))                              | \
                  (FLD_MWD_GPIO_GPIO_LD1_EN(GPIO_LD1_EN))                              | \
                  (FLD_MWD_GPIO_GPIO_LD2_EN(GPIO_LD2_EN))                              | \
                  (FLD_MWD_GPIO_GPIO_LD3_EN(GPIO_LD3_EN))                              | \
                  (FLD_MWD_GPIO_GPIO_TICK0_EN(GPIO_TICK0_EN))                          | \
                  (FLD_MWD_GPIO_GPIO_TICK1_EN(GPIO_TICK1_EN))                          | \
                  (FLD_MWD_GPIO_GPIO_TICK2_EN(GPIO_TICK2_EN))                          | \
                  (FLD_MWD_GPIO_GPIO_TICK3_EN(GPIO_TICK3_EN))                          | \
                  (FLD_MWD_GPIO_GPIO_GE_EN(GPIO_GE_EN))                                | \
                  (FLD_MWD_GPIO_GPIO_JTAG_EN(GPIO_JTAG_EN))                            | \
                  (FLD_MWD_GPIO_GPIO_MDIO_EN(GPIO_MDIO_EN))                            | \
                  (FLD_MWD_GPIO_GPIO_WDT_EN(GPIO_WDT_EN))                              | \
                  (FLD_MWD_GPIO_GPIO_ZC0_EN(GPIO_ZC0_EN))                              | \
                  (FLD_MWD_GPIO_GPIO_ZC1_EN(GPIO_ZC1_EN))                              | \
                  (FLD_MWD_GPIO_GPIO_GE_RGMII_EN(GPIO_GE_RGMII_EN))                    | \
                  (FLD_MWD_GPIO_GPIO_GE_MII_EN(GPIO_GE_MII_EN))                        | \
                  (FLD_MWD_GPIO_GPIO_SPI_3W(GPIO_SPI_3W))                              | \
                  (FLD_MWD_GPIO_GPIO_TCK_MC_SYN_EN(GPIO_TCK_MC_SYN_EN))                | \
                  (FLD_MWD_GPIO_GPIO_TCK_OSC_EN(GPIO_TCK_OSC_EN))                      | \
                  (FLD_MWD_GPIO_GPIO_TCK_SYS_EN(GPIO_TCK_SYS_EN))                      | \
                  (FLD_MWD_GPIO_GPIO_TCK_ADC_EN(GPIO_TCK_ADC_EN))                      | \
                  (FLD_MWD_GPIO_GPIO_TCK_DAC_EN(GPIO_TCK_DAC_EN))                      | \
                  (FLD_MWD_GPIO_GPIO_TCK_AUX_EN(GPIO_TCK_AUX_EN))                        \
                ))


#define  REG_GPIO_GPIO_SHARE_EN1                                  (REG_BASE_GPIO + 0x44)
    //Read/Write-Register Using Address
    #define  RD_GPIO_GPIO_SHARE_EN1()                             (REG32(REG_GPIO_GPIO_SHARE_EN1))
    #define  WR_GPIO_GPIO_SHARE_EN1(v)                            (REG32(REG_GPIO_GPIO_SHARE_EN1) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_GPIO_GPIO_SHARE_EN1()                      (0x1)  
    #define  REG_WMASK_GPIO_GPIO_SHARE_EN1()                      (0x1)

    //Field: GPIO_GPIO_EXT_PGA_EN
    #define  FLD_LSB_GPIO_GPIO_EXT_PGA_EN()                       (0)
    #define  FLD_MSB_GPIO_GPIO_EXT_PGA_EN()                       (0)
    #define  FLD_MASK_GPIO_GPIO_EXT_PGA_EN()                      (FLD_MASK(0, 0))
    #define  FLD_MWD_GPIO_GPIO_EXT_PGA_EN(v)                      (FLD_MWD(0, 0, v))
    #define  FLD_MRD_GPIO_GPIO_EXT_PGA_EN(v)                      (FLD_MRD(0, 0, v))
    #define  SET_GPIO_GPIO_EXT_PGA_EN(v)                          OP_FLD_WR_EXC(REG_GPIO_GPIO_SHARE_EN1, 0, 0, v)
    #define  GET_GPIO_GPIO_EXT_PGA_EN()                           OP_FLD_RD(REG_GPIO_GPIO_SHARE_EN1, 0, 0)
    #define  RST_GPIO_GPIO_EXT_PGA_EN()                           OP_FLD_WR_EXC(REG_GPIO_GPIO_SHARE_EN1, 0, 0, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_GPIO_GPIO_SHARE_EN1(GPIO_EXT_PGA_EN) \
                (WR_GPIO_GPIO_SHARE_EN1( \
                  (FLD_MWD_GPIO_GPIO_EXT_PGA_EN(GPIO_EXT_PGA_EN))                        \
                ))


#define  REG_GPIO_GPIO_SMAP_0                                     (REG_BASE_GPIO + 0x50)
    //Read/Write-Register Using Address
    #define  RD_GPIO_GPIO_SMAP_0()                                (REG32(REG_GPIO_GPIO_SMAP_0))
    #define  WR_GPIO_GPIO_SMAP_0(v)                               (REG32(REG_GPIO_GPIO_SMAP_0) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_GPIO_GPIO_SMAP_0()                         (0x1F1F1F1F)  
    #define  REG_WMASK_GPIO_GPIO_SMAP_0()                         (0x1F1F1F1F)

    //Field: GPIO_GPIO_WDT_MAP
    #define  FLD_LSB_GPIO_GPIO_WDT_MAP()                          (0)
    #define  FLD_MSB_GPIO_GPIO_WDT_MAP()                          (4)
    #define  FLD_MASK_GPIO_GPIO_WDT_MAP()                         (FLD_MASK(0, 4))
    #define  FLD_MWD_GPIO_GPIO_WDT_MAP(v)                         (FLD_MWD(0, 4, v))
    #define  FLD_MRD_GPIO_GPIO_WDT_MAP(v)                         (FLD_MRD(0, 4, v))
    #define  SET_GPIO_GPIO_WDT_MAP(v)                             OP_FLD_WR(REG_GPIO_GPIO_SMAP_0, 0, 4, v)
    #define  GET_GPIO_GPIO_WDT_MAP()                              OP_FLD_RD(REG_GPIO_GPIO_SMAP_0, 0, 4)
    #define  RST_GPIO_GPIO_WDT_MAP()                              OP_FLD_WR(REG_GPIO_GPIO_SMAP_0, 0, 4, 0xe)

    //Field: GPIO_GPIO_SS1_MAP
    #define  FLD_LSB_GPIO_GPIO_SS1_MAP()                          (8)
    #define  FLD_MSB_GPIO_GPIO_SS1_MAP()                          (12)
    #define  FLD_MASK_GPIO_GPIO_SS1_MAP()                         (FLD_MASK(8, 12))
    #define  FLD_MWD_GPIO_GPIO_SS1_MAP(v)                         (FLD_MWD(8, 12, v))
    #define  FLD_MRD_GPIO_GPIO_SS1_MAP(v)                         (FLD_MRD(8, 12, v))
    #define  SET_GPIO_GPIO_SS1_MAP(v)                             OP_FLD_WR(REG_GPIO_GPIO_SMAP_0, 8, 12, v)
    #define  GET_GPIO_GPIO_SS1_MAP()                              OP_FLD_RD(REG_GPIO_GPIO_SMAP_0, 8, 12)
    #define  RST_GPIO_GPIO_SS1_MAP()                              OP_FLD_WR(REG_GPIO_GPIO_SMAP_0, 8, 12, 0x19)

    //Field: GPIO_GPIO_SS2_MAP
    #define  FLD_LSB_GPIO_GPIO_SS2_MAP()                          (16)
    #define  FLD_MSB_GPIO_GPIO_SS2_MAP()                          (20)
    #define  FLD_MASK_GPIO_GPIO_SS2_MAP()                         (FLD_MASK(16, 20))
    #define  FLD_MWD_GPIO_GPIO_SS2_MAP(v)                         (FLD_MWD(16, 20, v))
    #define  FLD_MRD_GPIO_GPIO_SS2_MAP(v)                         (FLD_MRD(16, 20, v))
    #define  SET_GPIO_GPIO_SS2_MAP(v)                             OP_FLD_WR(REG_GPIO_GPIO_SMAP_0, 16, 20, v)
    #define  GET_GPIO_GPIO_SS2_MAP()                              OP_FLD_RD(REG_GPIO_GPIO_SMAP_0, 16, 20)
    #define  RST_GPIO_GPIO_SS2_MAP()                              OP_FLD_WR(REG_GPIO_GPIO_SMAP_0, 16, 20, 0x19)

    //Field: GPIO_GPIO_SS3_MAP
    #define  FLD_LSB_GPIO_GPIO_SS3_MAP()                          (24)
    #define  FLD_MSB_GPIO_GPIO_SS3_MAP()                          (28)
    #define  FLD_MASK_GPIO_GPIO_SS3_MAP()                         (FLD_MASK(24, 28))
    #define  FLD_MWD_GPIO_GPIO_SS3_MAP(v)                         (FLD_MWD(24, 28, v))
    #define  FLD_MRD_GPIO_GPIO_SS3_MAP(v)                         (FLD_MRD(24, 28, v))
    #define  SET_GPIO_GPIO_SS3_MAP(v)                             OP_FLD_WR(REG_GPIO_GPIO_SMAP_0, 24, 28, v)
    #define  GET_GPIO_GPIO_SS3_MAP()                              OP_FLD_RD(REG_GPIO_GPIO_SMAP_0, 24, 28)
    #define  RST_GPIO_GPIO_SS3_MAP()                              OP_FLD_WR(REG_GPIO_GPIO_SMAP_0, 24, 28, 0x19)

    //Write-Register Using Field-Name
    #define  WRF_GPIO_GPIO_SMAP_0(GPIO_WDT_MAP,GPIO_SS1_MAP,GPIO_SS2_MAP,GPIO_SS3_MAP) \
                (WR_GPIO_GPIO_SMAP_0( \
                  (FLD_MWD_GPIO_GPIO_WDT_MAP(GPIO_WDT_MAP))                            | \
                  (FLD_MWD_GPIO_GPIO_SS1_MAP(GPIO_SS1_MAP))                            | \
                  (FLD_MWD_GPIO_GPIO_SS2_MAP(GPIO_SS2_MAP))                            | \
                  (FLD_MWD_GPIO_GPIO_SS3_MAP(GPIO_SS3_MAP))                              \
                ))


#define  REG_GPIO_GPIO_SMAP_1                                     (REG_BASE_GPIO + 0x54)
    //Read/Write-Register Using Address
    #define  RD_GPIO_GPIO_SMAP_1()                                (REG32(REG_GPIO_GPIO_SMAP_1))
    #define  WR_GPIO_GPIO_SMAP_1(v)                               (REG32(REG_GPIO_GPIO_SMAP_1) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_GPIO_GPIO_SMAP_1()                         (0x1F1F1F1F)  
    #define  REG_WMASK_GPIO_GPIO_SMAP_1()                         (0x1F1F1F1F)

    //Field: GPIO_GPIO_UTX1_MAP
    #define  FLD_LSB_GPIO_GPIO_UTX1_MAP()                         (0)
    #define  FLD_MSB_GPIO_GPIO_UTX1_MAP()                         (4)
    #define  FLD_MASK_GPIO_GPIO_UTX1_MAP()                        (FLD_MASK(0, 4))
    #define  FLD_MWD_GPIO_GPIO_UTX1_MAP(v)                        (FLD_MWD(0, 4, v))
    #define  FLD_MRD_GPIO_GPIO_UTX1_MAP(v)                        (FLD_MRD(0, 4, v))
    #define  SET_GPIO_GPIO_UTX1_MAP(v)                            OP_FLD_WR(REG_GPIO_GPIO_SMAP_1, 0, 4, v)
    #define  GET_GPIO_GPIO_UTX1_MAP()                             OP_FLD_RD(REG_GPIO_GPIO_SMAP_1, 0, 4)
    #define  RST_GPIO_GPIO_UTX1_MAP()                             OP_FLD_WR(REG_GPIO_GPIO_SMAP_1, 0, 4, 0x14)

    //Field: GPIO_GPIO_URX1_MAP
    #define  FLD_LSB_GPIO_GPIO_URX1_MAP()                         (8)
    #define  FLD_MSB_GPIO_GPIO_URX1_MAP()                         (12)
    #define  FLD_MASK_GPIO_GPIO_URX1_MAP()                        (FLD_MASK(8, 12))
    #define  FLD_MWD_GPIO_GPIO_URX1_MAP(v)                        (FLD_MWD(8, 12, v))
    #define  FLD_MRD_GPIO_GPIO_URX1_MAP(v)                        (FLD_MRD(8, 12, v))
    #define  SET_GPIO_GPIO_URX1_MAP(v)                            OP_FLD_WR(REG_GPIO_GPIO_SMAP_1, 8, 12, v)
    #define  GET_GPIO_GPIO_URX1_MAP()                             OP_FLD_RD(REG_GPIO_GPIO_SMAP_1, 8, 12)
    #define  RST_GPIO_GPIO_URX1_MAP()                             OP_FLD_WR(REG_GPIO_GPIO_SMAP_1, 8, 12, 0x15)

    //Field: GPIO_GPIO_UTX2_MAP
    #define  FLD_LSB_GPIO_GPIO_UTX2_MAP()                         (16)
    #define  FLD_MSB_GPIO_GPIO_UTX2_MAP()                         (20)
    #define  FLD_MASK_GPIO_GPIO_UTX2_MAP()                        (FLD_MASK(16, 20))
    #define  FLD_MWD_GPIO_GPIO_UTX2_MAP(v)                        (FLD_MWD(16, 20, v))
    #define  FLD_MRD_GPIO_GPIO_UTX2_MAP(v)                        (FLD_MRD(16, 20, v))
    #define  SET_GPIO_GPIO_UTX2_MAP(v)                            OP_FLD_WR(REG_GPIO_GPIO_SMAP_1, 16, 20, v)
    #define  GET_GPIO_GPIO_UTX2_MAP()                             OP_FLD_RD(REG_GPIO_GPIO_SMAP_1, 16, 20)
    #define  RST_GPIO_GPIO_UTX2_MAP()                             OP_FLD_WR(REG_GPIO_GPIO_SMAP_1, 16, 20, 0x14)

    //Field: GPIO_GPIO_URX2_MAP
    #define  FLD_LSB_GPIO_GPIO_URX2_MAP()                         (24)
    #define  FLD_MSB_GPIO_GPIO_URX2_MAP()                         (28)
    #define  FLD_MASK_GPIO_GPIO_URX2_MAP()                        (FLD_MASK(24, 28))
    #define  FLD_MWD_GPIO_GPIO_URX2_MAP(v)                        (FLD_MWD(24, 28, v))
    #define  FLD_MRD_GPIO_GPIO_URX2_MAP(v)                        (FLD_MRD(24, 28, v))
    #define  SET_GPIO_GPIO_URX2_MAP(v)                            OP_FLD_WR(REG_GPIO_GPIO_SMAP_1, 24, 28, v)
    #define  GET_GPIO_GPIO_URX2_MAP()                             OP_FLD_RD(REG_GPIO_GPIO_SMAP_1, 24, 28)
    #define  RST_GPIO_GPIO_URX2_MAP()                             OP_FLD_WR(REG_GPIO_GPIO_SMAP_1, 24, 28, 0x15)

    //Write-Register Using Field-Name
    #define  WRF_GPIO_GPIO_SMAP_1(GPIO_UTX1_MAP,GPIO_URX1_MAP,GPIO_UTX2_MAP,GPIO_URX2_MAP) \
                (WR_GPIO_GPIO_SMAP_1( \
                  (FLD_MWD_GPIO_GPIO_UTX1_MAP(GPIO_UTX1_MAP))                          | \
                  (FLD_MWD_GPIO_GPIO_URX1_MAP(GPIO_URX1_MAP))                          | \
                  (FLD_MWD_GPIO_GPIO_UTX2_MAP(GPIO_UTX2_MAP))                          | \
                  (FLD_MWD_GPIO_GPIO_URX2_MAP(GPIO_URX2_MAP))                            \
                ))


#define  REG_GPIO_GPIO_SMAP_2                                     (REG_BASE_GPIO + 0x58)
    //Read/Write-Register Using Address
    #define  RD_GPIO_GPIO_SMAP_2()                                (REG32(REG_GPIO_GPIO_SMAP_2))
    #define  WR_GPIO_GPIO_SMAP_2(v)                               (REG32(REG_GPIO_GPIO_SMAP_2) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_GPIO_GPIO_SMAP_2()                         (0x1F1F1F1F)  
    #define  REG_WMASK_GPIO_GPIO_SMAP_2()                         (0x1F1F1F1F)

    //Field: GPIO_GPIO_ZC0_MAP
    #define  FLD_LSB_GPIO_GPIO_ZC0_MAP()                          (0)
    #define  FLD_MSB_GPIO_GPIO_ZC0_MAP()                          (4)
    #define  FLD_MASK_GPIO_GPIO_ZC0_MAP()                         (FLD_MASK(0, 4))
    #define  FLD_MWD_GPIO_GPIO_ZC0_MAP(v)                         (FLD_MWD(0, 4, v))
    #define  FLD_MRD_GPIO_GPIO_ZC0_MAP(v)                         (FLD_MRD(0, 4, v))
    #define  SET_GPIO_GPIO_ZC0_MAP(v)                             OP_FLD_WR(REG_GPIO_GPIO_SMAP_2, 0, 4, v)
    #define  GET_GPIO_GPIO_ZC0_MAP()                              OP_FLD_RD(REG_GPIO_GPIO_SMAP_2, 0, 4)
    #define  RST_GPIO_GPIO_ZC0_MAP()                              OP_FLD_WR(REG_GPIO_GPIO_SMAP_2, 0, 4, 0xc)

    //Field: GPIO_GPIO_ZC1_MAP
    #define  FLD_LSB_GPIO_GPIO_ZC1_MAP()                          (8)
    #define  FLD_MSB_GPIO_GPIO_ZC1_MAP()                          (12)
    #define  FLD_MASK_GPIO_GPIO_ZC1_MAP()                         (FLD_MASK(8, 12))
    #define  FLD_MWD_GPIO_GPIO_ZC1_MAP(v)                         (FLD_MWD(8, 12, v))
    #define  FLD_MRD_GPIO_GPIO_ZC1_MAP(v)                         (FLD_MRD(8, 12, v))
    #define  SET_GPIO_GPIO_ZC1_MAP(v)                             OP_FLD_WR(REG_GPIO_GPIO_SMAP_2, 8, 12, v)
    #define  GET_GPIO_GPIO_ZC1_MAP()                              OP_FLD_RD(REG_GPIO_GPIO_SMAP_2, 8, 12)
    #define  RST_GPIO_GPIO_ZC1_MAP()                              OP_FLD_WR(REG_GPIO_GPIO_SMAP_2, 8, 12, 0xc)

    //Field: GPIO_GPIO_SCL_MAP
    #define  FLD_LSB_GPIO_GPIO_SCL_MAP()                          (16)
    #define  FLD_MSB_GPIO_GPIO_SCL_MAP()                          (20)
    #define  FLD_MASK_GPIO_GPIO_SCL_MAP()                         (FLD_MASK(16, 20))
    #define  FLD_MWD_GPIO_GPIO_SCL_MAP(v)                         (FLD_MWD(16, 20, v))
    #define  FLD_MRD_GPIO_GPIO_SCL_MAP(v)                         (FLD_MRD(16, 20, v))
    #define  SET_GPIO_GPIO_SCL_MAP(v)                             OP_FLD_WR(REG_GPIO_GPIO_SMAP_2, 16, 20, v)
    #define  GET_GPIO_GPIO_SCL_MAP()                              OP_FLD_RD(REG_GPIO_GPIO_SMAP_2, 16, 20)
    #define  RST_GPIO_GPIO_SCL_MAP()                              OP_FLD_WR(REG_GPIO_GPIO_SMAP_2, 16, 20, 0xd)

    //Field: GPIO_GPIO_SDA_MAP
    #define  FLD_LSB_GPIO_GPIO_SDA_MAP()                          (24)
    #define  FLD_MSB_GPIO_GPIO_SDA_MAP()                          (28)
    #define  FLD_MASK_GPIO_GPIO_SDA_MAP()                         (FLD_MASK(24, 28))
    #define  FLD_MWD_GPIO_GPIO_SDA_MAP(v)                         (FLD_MWD(24, 28, v))
    #define  FLD_MRD_GPIO_GPIO_SDA_MAP(v)                         (FLD_MRD(24, 28, v))
    #define  SET_GPIO_GPIO_SDA_MAP(v)                             OP_FLD_WR(REG_GPIO_GPIO_SMAP_2, 24, 28, v)
    #define  GET_GPIO_GPIO_SDA_MAP()                              OP_FLD_RD(REG_GPIO_GPIO_SMAP_2, 24, 28)
    #define  RST_GPIO_GPIO_SDA_MAP()                              OP_FLD_WR(REG_GPIO_GPIO_SMAP_2, 24, 28, 0xd)

    //Write-Register Using Field-Name
    #define  WRF_GPIO_GPIO_SMAP_2(GPIO_ZC0_MAP,GPIO_ZC1_MAP,GPIO_SCL_MAP,GPIO_SDA_MAP) \
                (WR_GPIO_GPIO_SMAP_2( \
                  (FLD_MWD_GPIO_GPIO_ZC0_MAP(GPIO_ZC0_MAP))                            | \
                  (FLD_MWD_GPIO_GPIO_ZC1_MAP(GPIO_ZC1_MAP))                            | \
                  (FLD_MWD_GPIO_GPIO_SCL_MAP(GPIO_SCL_MAP))                            | \
                  (FLD_MWD_GPIO_GPIO_SDA_MAP(GPIO_SDA_MAP))                              \
                ))


#define  REG_GPIO_GPIO_SMAP_3                                     (REG_BASE_GPIO + 0x5c)
    //Read/Write-Register Using Address
    #define  RD_GPIO_GPIO_SMAP_3()                                (REG32(REG_GPIO_GPIO_SMAP_3))
    #define  WR_GPIO_GPIO_SMAP_3(v)                               (REG32(REG_GPIO_GPIO_SMAP_3) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_GPIO_GPIO_SMAP_3()                         (0x1F1F1F1F)  
    #define  REG_WMASK_GPIO_GPIO_SMAP_3()                         (0x1F1F1F1F)

    //Field: GPIO_GPIO_LD0_MAP
    #define  FLD_LSB_GPIO_GPIO_LD0_MAP()                          (0)
    #define  FLD_MSB_GPIO_GPIO_LD0_MAP()                          (4)
    #define  FLD_MASK_GPIO_GPIO_LD0_MAP()                         (FLD_MASK(0, 4))
    #define  FLD_MWD_GPIO_GPIO_LD0_MAP(v)                         (FLD_MWD(0, 4, v))
    #define  FLD_MRD_GPIO_GPIO_LD0_MAP(v)                         (FLD_MRD(0, 4, v))
    #define  SET_GPIO_GPIO_LD0_MAP(v)                             OP_FLD_WR(REG_GPIO_GPIO_SMAP_3, 0, 4, v)
    #define  GET_GPIO_GPIO_LD0_MAP()                              OP_FLD_RD(REG_GPIO_GPIO_SMAP_3, 0, 4)
    #define  RST_GPIO_GPIO_LD0_MAP()                              OP_FLD_WR(REG_GPIO_GPIO_SMAP_3, 0, 4, 0xa)

    //Field: GPIO_GPIO_LD1_MAP
    #define  FLD_LSB_GPIO_GPIO_LD1_MAP()                          (8)
    #define  FLD_MSB_GPIO_GPIO_LD1_MAP()                          (12)
    #define  FLD_MASK_GPIO_GPIO_LD1_MAP()                         (FLD_MASK(8, 12))
    #define  FLD_MWD_GPIO_GPIO_LD1_MAP(v)                         (FLD_MWD(8, 12, v))
    #define  FLD_MRD_GPIO_GPIO_LD1_MAP(v)                         (FLD_MRD(8, 12, v))
    #define  SET_GPIO_GPIO_LD1_MAP(v)                             OP_FLD_WR(REG_GPIO_GPIO_SMAP_3, 8, 12, v)
    #define  GET_GPIO_GPIO_LD1_MAP()                              OP_FLD_RD(REG_GPIO_GPIO_SMAP_3, 8, 12)
    #define  RST_GPIO_GPIO_LD1_MAP()                              OP_FLD_WR(REG_GPIO_GPIO_SMAP_3, 8, 12, 0xb)

    //Field: GPIO_GPIO_LD2_MAP
    #define  FLD_LSB_GPIO_GPIO_LD2_MAP()                          (16)
    #define  FLD_MSB_GPIO_GPIO_LD2_MAP()                          (20)
    #define  FLD_MASK_GPIO_GPIO_LD2_MAP()                         (FLD_MASK(16, 20))
    #define  FLD_MWD_GPIO_GPIO_LD2_MAP(v)                         (FLD_MWD(16, 20, v))
    #define  FLD_MRD_GPIO_GPIO_LD2_MAP(v)                         (FLD_MRD(16, 20, v))
    #define  SET_GPIO_GPIO_LD2_MAP(v)                             OP_FLD_WR(REG_GPIO_GPIO_SMAP_3, 16, 20, v)
    #define  GET_GPIO_GPIO_LD2_MAP()                              OP_FLD_RD(REG_GPIO_GPIO_SMAP_3, 16, 20)
    #define  RST_GPIO_GPIO_LD2_MAP()                              OP_FLD_WR(REG_GPIO_GPIO_SMAP_3, 16, 20, 0x1c)

    //Field: GPIO_GPIO_LD3_MAP
    #define  FLD_LSB_GPIO_GPIO_LD3_MAP()                          (24)
    #define  FLD_MSB_GPIO_GPIO_LD3_MAP()                          (28)
    #define  FLD_MASK_GPIO_GPIO_LD3_MAP()                         (FLD_MASK(24, 28))
    #define  FLD_MWD_GPIO_GPIO_LD3_MAP(v)                         (FLD_MWD(24, 28, v))
    #define  FLD_MRD_GPIO_GPIO_LD3_MAP(v)                         (FLD_MRD(24, 28, v))
    #define  SET_GPIO_GPIO_LD3_MAP(v)                             OP_FLD_WR(REG_GPIO_GPIO_SMAP_3, 24, 28, v)
    #define  GET_GPIO_GPIO_LD3_MAP()                              OP_FLD_RD(REG_GPIO_GPIO_SMAP_3, 24, 28)
    #define  RST_GPIO_GPIO_LD3_MAP()                              OP_FLD_WR(REG_GPIO_GPIO_SMAP_3, 24, 28, 0x1e)

    //Write-Register Using Field-Name
    #define  WRF_GPIO_GPIO_SMAP_3(GPIO_LD0_MAP,GPIO_LD1_MAP,GPIO_LD2_MAP,GPIO_LD3_MAP) \
                (WR_GPIO_GPIO_SMAP_3( \
                  (FLD_MWD_GPIO_GPIO_LD0_MAP(GPIO_LD0_MAP))                            | \
                  (FLD_MWD_GPIO_GPIO_LD1_MAP(GPIO_LD1_MAP))                            | \
                  (FLD_MWD_GPIO_GPIO_LD2_MAP(GPIO_LD2_MAP))                            | \
                  (FLD_MWD_GPIO_GPIO_LD3_MAP(GPIO_LD3_MAP))                              \
                ))


#define  REG_GPIO_GPIO_SMAP_4                                     (REG_BASE_GPIO + 0x60)
    //Read/Write-Register Using Address
    #define  RD_GPIO_GPIO_SMAP_4()                                (REG32(REG_GPIO_GPIO_SMAP_4))
    #define  WR_GPIO_GPIO_SMAP_4(v)                               (REG32(REG_GPIO_GPIO_SMAP_4) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_GPIO_GPIO_SMAP_4()                         (0x1F1F1F1F)  
    #define  REG_WMASK_GPIO_GPIO_SMAP_4()                         (0x1F1F1F1F)

    //Field: GPIO_GPIO_TICK0_MAP
    #define  FLD_LSB_GPIO_GPIO_TICK0_MAP()                        (0)
    #define  FLD_MSB_GPIO_GPIO_TICK0_MAP()                        (4)
    #define  FLD_MASK_GPIO_GPIO_TICK0_MAP()                       (FLD_MASK(0, 4))
    #define  FLD_MWD_GPIO_GPIO_TICK0_MAP(v)                       (FLD_MWD(0, 4, v))
    #define  FLD_MRD_GPIO_GPIO_TICK0_MAP(v)                       (FLD_MRD(0, 4, v))
    #define  SET_GPIO_GPIO_TICK0_MAP(v)                           OP_FLD_WR(REG_GPIO_GPIO_SMAP_4, 0, 4, v)
    #define  GET_GPIO_GPIO_TICK0_MAP()                            OP_FLD_RD(REG_GPIO_GPIO_SMAP_4, 0, 4)
    #define  RST_GPIO_GPIO_TICK0_MAP()                            OP_FLD_WR(REG_GPIO_GPIO_SMAP_4, 0, 4, 0x1f)

    //Field: GPIO_GPIO_TICK1_MAP
    #define  FLD_LSB_GPIO_GPIO_TICK1_MAP()                        (8)
    #define  FLD_MSB_GPIO_GPIO_TICK1_MAP()                        (12)
    #define  FLD_MASK_GPIO_GPIO_TICK1_MAP()                       (FLD_MASK(8, 12))
    #define  FLD_MWD_GPIO_GPIO_TICK1_MAP(v)                       (FLD_MWD(8, 12, v))
    #define  FLD_MRD_GPIO_GPIO_TICK1_MAP(v)                       (FLD_MRD(8, 12, v))
    #define  SET_GPIO_GPIO_TICK1_MAP(v)                           OP_FLD_WR(REG_GPIO_GPIO_SMAP_4, 8, 12, v)
    #define  GET_GPIO_GPIO_TICK1_MAP()                            OP_FLD_RD(REG_GPIO_GPIO_SMAP_4, 8, 12)
    #define  RST_GPIO_GPIO_TICK1_MAP()                            OP_FLD_WR(REG_GPIO_GPIO_SMAP_4, 8, 12, 0x1f)

    //Field: GPIO_GPIO_TICK2_MAP
    #define  FLD_LSB_GPIO_GPIO_TICK2_MAP()                        (16)
    #define  FLD_MSB_GPIO_GPIO_TICK2_MAP()                        (20)
    #define  FLD_MASK_GPIO_GPIO_TICK2_MAP()                       (FLD_MASK(16, 20))
    #define  FLD_MWD_GPIO_GPIO_TICK2_MAP(v)                       (FLD_MWD(16, 20, v))
    #define  FLD_MRD_GPIO_GPIO_TICK2_MAP(v)                       (FLD_MRD(16, 20, v))
    #define  SET_GPIO_GPIO_TICK2_MAP(v)                           OP_FLD_WR(REG_GPIO_GPIO_SMAP_4, 16, 20, v)
    #define  GET_GPIO_GPIO_TICK2_MAP()                            OP_FLD_RD(REG_GPIO_GPIO_SMAP_4, 16, 20)
    #define  RST_GPIO_GPIO_TICK2_MAP()                            OP_FLD_WR(REG_GPIO_GPIO_SMAP_4, 16, 20, 0x1f)

    //Field: GPIO_GPIO_TICK3_MAP
    #define  FLD_LSB_GPIO_GPIO_TICK3_MAP()                        (24)
    #define  FLD_MSB_GPIO_GPIO_TICK3_MAP()                        (28)
    #define  FLD_MASK_GPIO_GPIO_TICK3_MAP()                       (FLD_MASK(24, 28))
    #define  FLD_MWD_GPIO_GPIO_TICK3_MAP(v)                       (FLD_MWD(24, 28, v))
    #define  FLD_MRD_GPIO_GPIO_TICK3_MAP(v)                       (FLD_MRD(24, 28, v))
    #define  SET_GPIO_GPIO_TICK3_MAP(v)                           OP_FLD_WR(REG_GPIO_GPIO_SMAP_4, 24, 28, v)
    #define  GET_GPIO_GPIO_TICK3_MAP()                            OP_FLD_RD(REG_GPIO_GPIO_SMAP_4, 24, 28)
    #define  RST_GPIO_GPIO_TICK3_MAP()                            OP_FLD_WR(REG_GPIO_GPIO_SMAP_4, 24, 28, 0x1f)

    //Write-Register Using Field-Name
    #define  WRF_GPIO_GPIO_SMAP_4(GPIO_TICK0_MAP,GPIO_TICK1_MAP,GPIO_TICK2_MAP,GPIO_TICK3_MAP) \
                (WR_GPIO_GPIO_SMAP_4( \
                  (FLD_MWD_GPIO_GPIO_TICK0_MAP(GPIO_TICK0_MAP))                        | \
                  (FLD_MWD_GPIO_GPIO_TICK1_MAP(GPIO_TICK1_MAP))                        | \
                  (FLD_MWD_GPIO_GPIO_TICK2_MAP(GPIO_TICK2_MAP))                        | \
                  (FLD_MWD_GPIO_GPIO_TICK3_MAP(GPIO_TICK3_MAP))                          \
                ))


#define  REG_GPIO_GPIO_SMAP_5                                     (REG_BASE_GPIO + 0x64)
    //Read/Write-Register Using Address
    #define  RD_GPIO_GPIO_SMAP_5()                                (REG32(REG_GPIO_GPIO_SMAP_5))
    #define  WR_GPIO_GPIO_SMAP_5(v)                               (REG32(REG_GPIO_GPIO_SMAP_5) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_GPIO_GPIO_SMAP_5()                         (0x1F1F)  
    #define  REG_WMASK_GPIO_GPIO_SMAP_5()                         (0x1F1F)

    //Field: GPIO_GPIO_EXT_PGA_CLK_MAP
    #define  FLD_LSB_GPIO_GPIO_EXT_PGA_CLK_MAP()                  (0)
    #define  FLD_MSB_GPIO_GPIO_EXT_PGA_CLK_MAP()                  (4)
    #define  FLD_MASK_GPIO_GPIO_EXT_PGA_CLK_MAP()                 (FLD_MASK(0, 4))
    #define  FLD_MWD_GPIO_GPIO_EXT_PGA_CLK_MAP(v)                 (FLD_MWD(0, 4, v))
    #define  FLD_MRD_GPIO_GPIO_EXT_PGA_CLK_MAP(v)                 (FLD_MRD(0, 4, v))
    #define  SET_GPIO_GPIO_EXT_PGA_CLK_MAP(v)                     OP_FLD_WR(REG_GPIO_GPIO_SMAP_5, 0, 4, v)
    #define  GET_GPIO_GPIO_EXT_PGA_CLK_MAP()                      OP_FLD_RD(REG_GPIO_GPIO_SMAP_5, 0, 4)
    #define  RST_GPIO_GPIO_EXT_PGA_CLK_MAP()                      OP_FLD_WR(REG_GPIO_GPIO_SMAP_5, 0, 4, 0x1f)

    //Field: GPIO_GPIO_EXT_PGA_DAT_MAP
    #define  FLD_LSB_GPIO_GPIO_EXT_PGA_DAT_MAP()                  (8)
    #define  FLD_MSB_GPIO_GPIO_EXT_PGA_DAT_MAP()                  (12)
    #define  FLD_MASK_GPIO_GPIO_EXT_PGA_DAT_MAP()                 (FLD_MASK(8, 12))
    #define  FLD_MWD_GPIO_GPIO_EXT_PGA_DAT_MAP(v)                 (FLD_MWD(8, 12, v))
    #define  FLD_MRD_GPIO_GPIO_EXT_PGA_DAT_MAP(v)                 (FLD_MRD(8, 12, v))
    #define  SET_GPIO_GPIO_EXT_PGA_DAT_MAP(v)                     OP_FLD_WR(REG_GPIO_GPIO_SMAP_5, 8, 12, v)
    #define  GET_GPIO_GPIO_EXT_PGA_DAT_MAP()                      OP_FLD_RD(REG_GPIO_GPIO_SMAP_5, 8, 12)
    #define  RST_GPIO_GPIO_EXT_PGA_DAT_MAP()                      OP_FLD_WR(REG_GPIO_GPIO_SMAP_5, 8, 12, 0x1f)

    //Write-Register Using Field-Name
    #define  WRF_GPIO_GPIO_SMAP_5(GPIO_EXT_PGA_CLK_MAP,GPIO_EXT_PGA_DAT_MAP) \
                (WR_GPIO_GPIO_SMAP_5( \
                  (FLD_MWD_GPIO_GPIO_EXT_PGA_CLK_MAP(GPIO_EXT_PGA_CLK_MAP))            | \
                  (FLD_MWD_GPIO_GPIO_EXT_PGA_DAT_MAP(GPIO_EXT_PGA_DAT_MAP))              \
                ))



#endif /*__LIGHTELF_GPIO_REG_H__*/
// vim:ft=c:nowrap:noma
