/*
 * Copyright (c) 2006-2015 Triductor Technology, Inc.
 *           All Rights Reserved Worldwide
 *
 * Filename: lightelf_acu_reg.h
 * Author  : $Author: Ywang$
 * Date    : Jun/01/2015
 * Version : $Revision: 3115 $
 * Purpose : Describe all the available registers for ACU of LIGHTELF.
             This file is automatically generated by Register Parser.
 */

#ifndef __LIGHTELF_ACU_REG_H__
#define __LIGHTELF_ACU_REG_H__

#ifndef REG32
    #define REG32(x)                    (*(volatile unsigned int *)(x))
#endif

#ifndef _REG_FLD_OP_
    #define _REG_FLD_OP_

    // Register Field Mask
    #define FLD_MASK(s,e)              ((0xffffffff >> (31-(e)+(s))) << (s))

    // Register Field Mask Write-Data
    // s -- Start of Bit  e -- End   of Bit
    // v -- Value
    #define FLD_MWD(s,e,v)              (((v) << (s)) & FLD_MASK((s),(e)))

    // Register Field Mask Read-Data
    // s -- Start of Bit  e -- End   of Bit
    // v -- Value
    #define FLD_MRD(s,e,v)              (((v) & FLD_MASK((s),(e))) >> (s))

    // Register Field Write operation
    // a -- Address   s -- Start of Bit
    // v -- Value     e -- End   of Bit
    #define OP_FLD_WR(a,s,e,v)          (REG32((a)) = (((v) << (s)) & FLD_MASK((s),(e))) | (REG32((a)) & ~FLD_MASK((s),(e))))
    #define OP_FLD_WR_EXC(a,s,e,v)      (REG32((a)) = (((v) << (s)) & FLD_MASK((s),(e))))

    // Register Field Read operation
    #define OP_FLD_RD(a,s,e)            ((REG32((a)) & FLD_MASK((s),(e))) >> (s))

#endif

//Address Offset for multi-instance mode only
#ifndef  REG_OFFSET_ACU
    #define  REG_OFFSET_ACU  (0x100000)
#endif

// Base address
#ifndef REG_BASE_ACU
    #define  REG_BASE_ACU    (0xf0300000)
#endif



//------------------------------------
// Basic Registers
//------------------------------------
#define  REG_ACU_GLB_CFG                                          (REG_BASE_ACU + 0x000)
    //Read/Write-Register Using Address
    #define  RD_ACU_GLB_CFG()                                     (REG32(REG_ACU_GLB_CFG))
    #define  WR_ACU_GLB_CFG(v)                                    (REG32(REG_ACU_GLB_CFG) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_GLB_CFG()                              (0x111101FF)  
    #define  REG_WMASK_ACU_GLB_CFG()                              (0x111101FF)

    //Field: ACU_CRYPT_ALG
    #define  FLD_LSB_ACU_CRYPT_ALG()                              (0)
    #define  FLD_MSB_ACU_CRYPT_ALG()                              (3)
    #define  FLD_MASK_ACU_CRYPT_ALG()                             (FLD_MASK(0, 3))
    #define  FLD_MWD_ACU_CRYPT_ALG(v)                             (FLD_MWD(0, 3, v))
    #define  FLD_MRD_ACU_CRYPT_ALG(v)                             (FLD_MRD(0, 3, v))
    #define  SET_ACU_CRYPT_ALG(v)                                 OP_FLD_WR(REG_ACU_GLB_CFG, 0, 3, v)
    #define  SET_ACU_CRYPT_ALG_AES_()                             OP_FLD_WR(REG_ACU_GLB_CFG, 0, 3, 0x0)
    #define  KEY_ACU_CRYPT_ALG_AES_()                             (0x0)
    #define  SET_ACU_CRYPT_ALG_SMS4_()                            OP_FLD_WR(REG_ACU_GLB_CFG, 0, 3, 0x1)
    #define  KEY_ACU_CRYPT_ALG_SMS4_()                            (0x1)
    #define  GET_ACU_CRYPT_ALG()                                  OP_FLD_RD(REG_ACU_GLB_CFG, 0, 3)
    #define  RST_ACU_CRYPT_ALG()                                  OP_FLD_WR(REG_ACU_GLB_CFG, 0, 3, 0x0)

    //Field: ACU_CRYPT_MODE
    #define  FLD_LSB_ACU_CRYPT_MODE()                             (4)
    #define  FLD_MSB_ACU_CRYPT_MODE()                             (7)
    #define  FLD_MASK_ACU_CRYPT_MODE()                            (FLD_MASK(4, 7))
    #define  FLD_MWD_ACU_CRYPT_MODE(v)                            (FLD_MWD(4, 7, v))
    #define  FLD_MRD_ACU_CRYPT_MODE(v)                            (FLD_MRD(4, 7, v))
    #define  SET_ACU_CRYPT_MODE(v)                                OP_FLD_WR(REG_ACU_GLB_CFG, 4, 7, v)
    #define  SET_ACU_CRYPT_MODE_CBC_()                            OP_FLD_WR(REG_ACU_GLB_CFG, 4, 7, 0x1)
    #define  KEY_ACU_CRYPT_MODE_CBC_()                            (0x1)
    #define  SET_ACU_CRYPT_MODE_ECB_()                            OP_FLD_WR(REG_ACU_GLB_CFG, 4, 7, 0x0)
    #define  KEY_ACU_CRYPT_MODE_ECB_()                            (0x0)
    #define  GET_ACU_CRYPT_MODE()                                 OP_FLD_RD(REG_ACU_GLB_CFG, 4, 7)
    #define  RST_ACU_CRYPT_MODE()                                 OP_FLD_WR(REG_ACU_GLB_CFG, 4, 7, 0x0)

    //Field: ACU_ENC
    #define  FLD_LSB_ACU_ENC()                                    (8)
    #define  FLD_MSB_ACU_ENC()                                    (8)
    #define  FLD_MASK_ACU_ENC()                                   (FLD_MASK(8, 8))
    #define  FLD_MWD_ACU_ENC(v)                                   (FLD_MWD(8, 8, v))
    #define  FLD_MRD_ACU_ENC(v)                                   (FLD_MRD(8, 8, v))
    #define  SET_ACU_ENC(v)                                       OP_FLD_WR(REG_ACU_GLB_CFG, 8, 8, v)
    #define  GET_ACU_ENC()                                        OP_FLD_RD(REG_ACU_GLB_CFG, 8, 8)
    #define  RST_ACU_ENC()                                        OP_FLD_WR(REG_ACU_GLB_CFG, 8, 8, 0x1)

    //Field: ACU_ENC_EN
    #define  FLD_LSB_ACU_ENC_EN()                                 (16)
    #define  FLD_MSB_ACU_ENC_EN()                                 (16)
    #define  FLD_MASK_ACU_ENC_EN()                                (FLD_MASK(16, 16))
    #define  FLD_MWD_ACU_ENC_EN(v)                                (FLD_MWD(16, 16, v))
    #define  FLD_MRD_ACU_ENC_EN(v)                                (FLD_MRD(16, 16, v))
    #define  SET_ACU_ENC_EN(v)                                    OP_FLD_WR(REG_ACU_GLB_CFG, 16, 16, v)
    #define  GET_ACU_ENC_EN()                                     OP_FLD_RD(REG_ACU_GLB_CFG, 16, 16)
    #define  RST_ACU_ENC_EN()                                     OP_FLD_WR(REG_ACU_GLB_CFG, 16, 16, 0x1)

    //Field: ACU_DEC_EN
    #define  FLD_LSB_ACU_DEC_EN()                                 (20)
    #define  FLD_MSB_ACU_DEC_EN()                                 (20)
    #define  FLD_MASK_ACU_DEC_EN()                                (FLD_MASK(20, 20))
    #define  FLD_MWD_ACU_DEC_EN(v)                                (FLD_MWD(20, 20, v))
    #define  FLD_MRD_ACU_DEC_EN(v)                                (FLD_MRD(20, 20, v))
    #define  SET_ACU_DEC_EN(v)                                    OP_FLD_WR(REG_ACU_GLB_CFG, 20, 20, v)
    #define  GET_ACU_DEC_EN()                                     OP_FLD_RD(REG_ACU_GLB_CFG, 20, 20)
    #define  RST_ACU_DEC_EN()                                     OP_FLD_WR(REG_ACU_GLB_CFG, 20, 20, 0x1)

    //Field: ACU_CRC_EN
    #define  FLD_LSB_ACU_CRC_EN()                                 (24)
    #define  FLD_MSB_ACU_CRC_EN()                                 (24)
    #define  FLD_MASK_ACU_CRC_EN()                                (FLD_MASK(24, 24))
    #define  FLD_MWD_ACU_CRC_EN(v)                                (FLD_MWD(24, 24, v))
    #define  FLD_MRD_ACU_CRC_EN(v)                                (FLD_MRD(24, 24, v))
    #define  SET_ACU_CRC_EN(v)                                    OP_FLD_WR(REG_ACU_GLB_CFG, 24, 24, v)
    #define  GET_ACU_CRC_EN()                                     OP_FLD_RD(REG_ACU_GLB_CFG, 24, 24)
    #define  RST_ACU_CRC_EN()                                     OP_FLD_WR(REG_ACU_GLB_CFG, 24, 24, 0x1)

    //Field: ACU_KEY_COUNT_EN
    #define  FLD_LSB_ACU_KEY_COUNT_EN()                           (28)
    #define  FLD_MSB_ACU_KEY_COUNT_EN()                           (28)
    #define  FLD_MASK_ACU_KEY_COUNT_EN()                          (FLD_MASK(28, 28))
    #define  FLD_MWD_ACU_KEY_COUNT_EN(v)                          (FLD_MWD(28, 28, v))
    #define  FLD_MRD_ACU_KEY_COUNT_EN(v)                          (FLD_MRD(28, 28, v))
    #define  SET_ACU_KEY_COUNT_EN(v)                              OP_FLD_WR(REG_ACU_GLB_CFG, 28, 28, v)
    #define  GET_ACU_KEY_COUNT_EN()                               OP_FLD_RD(REG_ACU_GLB_CFG, 28, 28)
    #define  RST_ACU_KEY_COUNT_EN()                               OP_FLD_WR(REG_ACU_GLB_CFG, 28, 28, 0x1)

    //Write-Register Using Field-Name
    #define  WRF_ACU_GLB_CFG(CRYPT_ALG,CRYPT_MODE,ENC,ENC_EN,DEC_EN,CRC_EN,KEY_COUNT_EN) \
                (WR_ACU_GLB_CFG( \
                  (FLD_MWD_ACU_CRYPT_ALG(CRYPT_ALG))                                   | \
                  (FLD_MWD_ACU_CRYPT_MODE(CRYPT_MODE))                                 | \
                  (FLD_MWD_ACU_ENC(ENC))                                               | \
                  (FLD_MWD_ACU_ENC_EN(ENC_EN))                                         | \
                  (FLD_MWD_ACU_DEC_EN(DEC_EN))                                         | \
                  (FLD_MWD_ACU_CRC_EN(CRC_EN))                                         | \
                  (FLD_MWD_ACU_KEY_COUNT_EN(KEY_COUNT_EN))                               \
                ))


#define  REG_ACU_CTRL                                             (REG_BASE_ACU + 0x004)
    //Read/Write-Register Using Address
    #define  RD_ACU_CTRL()                                        (REG32(REG_ACU_CTRL))
    #define  WR_ACU_CTRL(v)                                       (REG32(REG_ACU_CTRL) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_CTRL()                                 (0xFFFF0000)  
    #define  REG_WMASK_ACU_CTRL()                                 (0xFFFF0001)

    //Field: ACU_READY
    #define  FLD_LSB_ACU_READY()                                  (0)
    #define  FLD_MSB_ACU_READY()                                  (0)
    #define  FLD_MASK_ACU_READY()                                 (FLD_MASK(0, 0))
    #define  FLD_MWD_ACU_READY(v)                                 (FLD_MWD(0, 0, v))
    #define  FLD_MRD_ACU_READY(v)                                 (FLD_MRD(0, 0, v))
    #define  SET_ACU_READY(v)                                     OP_FLD_WR(REG_ACU_CTRL, 0, 0, v)
    #define  RST_ACU_READY()                                      OP_FLD_WR(REG_ACU_CTRL, 0, 0, 0x0)

    //Field: ACU_DATA_LEN
    #define  FLD_LSB_ACU_DATA_LEN()                               (16)
    #define  FLD_MSB_ACU_DATA_LEN()                               (31)
    #define  FLD_MASK_ACU_DATA_LEN()                              (FLD_MASK(16, 31))
    #define  FLD_MWD_ACU_DATA_LEN(v)                              (FLD_MWD(16, 31, v))
    #define  FLD_MRD_ACU_DATA_LEN(v)                              (FLD_MRD(16, 31, v))
    #define  SET_ACU_DATA_LEN(v)                                  OP_FLD_WR(REG_ACU_CTRL, 16, 31, v)
    #define  GET_ACU_DATA_LEN()                                   OP_FLD_RD(REG_ACU_CTRL, 16, 31)
    #define  RST_ACU_DATA_LEN()                                   OP_FLD_WR(REG_ACU_CTRL, 16, 31, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_ACU_CTRL(READY,DATA_LEN) \
                (WR_ACU_CTRL( \
                  (FLD_MWD_ACU_READY(READY))                                           | \
                  (FLD_MWD_ACU_DATA_LEN(DATA_LEN))                                       \
                ))


#define  REG_ACU_DATA_ORDER                                       (REG_BASE_ACU + 0x008)
    //Read/Write-Register Using Address
    #define  RD_ACU_DATA_ORDER()                                  (REG32(REG_ACU_DATA_ORDER))
    #define  WR_ACU_DATA_ORDER(v)                                 (REG32(REG_ACU_DATA_ORDER) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_DATA_ORDER()                           (0x77)  
    #define  REG_WMASK_ACU_DATA_ORDER()                           (0x77)

    //Field: ACU_IN_ORDER
    #define  FLD_LSB_ACU_IN_ORDER()                               (0)
    #define  FLD_MSB_ACU_IN_ORDER()                               (2)
    #define  FLD_MASK_ACU_IN_ORDER()                              (FLD_MASK(0, 2))
    #define  FLD_MWD_ACU_IN_ORDER(v)                              (FLD_MWD(0, 2, v))
    #define  FLD_MRD_ACU_IN_ORDER(v)                              (FLD_MRD(0, 2, v))
    #define  SET_ACU_IN_ORDER(v)                                  OP_FLD_WR(REG_ACU_DATA_ORDER, 0, 2, v)
    #define  GET_ACU_IN_ORDER()                                   OP_FLD_RD(REG_ACU_DATA_ORDER, 0, 2)
    #define  RST_ACU_IN_ORDER()                                   OP_FLD_WR(REG_ACU_DATA_ORDER, 0, 2, 0x0)

    //Field: ACU_OUT_ORDER
    #define  FLD_LSB_ACU_OUT_ORDER()                              (4)
    #define  FLD_MSB_ACU_OUT_ORDER()                              (6)
    #define  FLD_MASK_ACU_OUT_ORDER()                             (FLD_MASK(4, 6))
    #define  FLD_MWD_ACU_OUT_ORDER(v)                             (FLD_MWD(4, 6, v))
    #define  FLD_MRD_ACU_OUT_ORDER(v)                             (FLD_MRD(4, 6, v))
    #define  SET_ACU_OUT_ORDER(v)                                 OP_FLD_WR(REG_ACU_DATA_ORDER, 4, 6, v)
    #define  GET_ACU_OUT_ORDER()                                  OP_FLD_RD(REG_ACU_DATA_ORDER, 4, 6)
    #define  RST_ACU_OUT_ORDER()                                  OP_FLD_WR(REG_ACU_DATA_ORDER, 4, 6, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_ACU_DATA_ORDER(IN_ORDER,OUT_ORDER) \
                (WR_ACU_DATA_ORDER( \
                  (FLD_MWD_ACU_IN_ORDER(IN_ORDER))                                     | \
                  (FLD_MWD_ACU_OUT_ORDER(OUT_ORDER))                                     \
                ))


#define  REG_ACU_INTR_THD                                         (REG_BASE_ACU + 0x00c)
    //Read/Write-Register Using Address
    #define  RD_ACU_INTR_THD()                                    (REG32(REG_ACU_INTR_THD))
    #define  WR_ACU_INTR_THD(v)                                   (REG32(REG_ACU_INTR_THD) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_INTR_THD()                             (0xFFFFFFFF)  
    #define  REG_WMASK_ACU_INTR_THD()                             (0xFFFFFFFF)

    //Field: ACU_TX_INTR_THD
    #define  FLD_LSB_ACU_TX_INTR_THD()                            (0)
    #define  FLD_MSB_ACU_TX_INTR_THD()                            (15)
    #define  FLD_MASK_ACU_TX_INTR_THD()                           (FLD_MASK(0, 15))
    #define  FLD_MWD_ACU_TX_INTR_THD(v)                           (FLD_MWD(0, 15, v))
    #define  FLD_MRD_ACU_TX_INTR_THD(v)                           (FLD_MRD(0, 15, v))
    #define  SET_ACU_TX_INTR_THD(v)                               OP_FLD_WR(REG_ACU_INTR_THD, 0, 15, v)
    #define  GET_ACU_TX_INTR_THD()                                OP_FLD_RD(REG_ACU_INTR_THD, 0, 15)
    #define  RST_ACU_TX_INTR_THD()                                OP_FLD_WR(REG_ACU_INTR_THD, 0, 15, 0x20)

    //Field: ACU_RX_INTR_THD
    #define  FLD_LSB_ACU_RX_INTR_THD()                            (16)
    #define  FLD_MSB_ACU_RX_INTR_THD()                            (31)
    #define  FLD_MASK_ACU_RX_INTR_THD()                           (FLD_MASK(16, 31))
    #define  FLD_MWD_ACU_RX_INTR_THD(v)                           (FLD_MWD(16, 31, v))
    #define  FLD_MRD_ACU_RX_INTR_THD(v)                           (FLD_MRD(16, 31, v))
    #define  SET_ACU_RX_INTR_THD(v)                               OP_FLD_WR(REG_ACU_INTR_THD, 16, 31, v)
    #define  GET_ACU_RX_INTR_THD()                                OP_FLD_RD(REG_ACU_INTR_THD, 16, 31)
    #define  RST_ACU_RX_INTR_THD()                                OP_FLD_WR(REG_ACU_INTR_THD, 16, 31, 0x20)

    //Write-Register Using Field-Name
    #define  WRF_ACU_INTR_THD(TX_INTR_THD,RX_INTR_THD) \
                (WR_ACU_INTR_THD( \
                  (FLD_MWD_ACU_TX_INTR_THD(TX_INTR_THD))                               | \
                  (FLD_MWD_ACU_RX_INTR_THD(RX_INTR_THD))                                 \
                ))


#define  REG_ACU_READY_THD                                        (REG_BASE_ACU + 0x010)
    //Read/Write-Register Using Address
    #define  RD_ACU_READY_THD()                                   (REG32(REG_ACU_READY_THD))
    #define  WR_ACU_READY_THD(v)                                  (REG32(REG_ACU_READY_THD) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_READY_THD()                            (0xFFFFFFFF)  
    #define  REG_WMASK_ACU_READY_THD()                            (0xFFFFFFFF)

    //Field: ACU_TX_BRDY_THD
    #define  FLD_LSB_ACU_TX_BRDY_THD()                            (0)
    #define  FLD_MSB_ACU_TX_BRDY_THD()                            (15)
    #define  FLD_MASK_ACU_TX_BRDY_THD()                           (FLD_MASK(0, 15))
    #define  FLD_MWD_ACU_TX_BRDY_THD(v)                           (FLD_MWD(0, 15, v))
    #define  FLD_MRD_ACU_TX_BRDY_THD(v)                           (FLD_MRD(0, 15, v))
    #define  SET_ACU_TX_BRDY_THD(v)                               OP_FLD_WR(REG_ACU_READY_THD, 0, 15, v)
    #define  GET_ACU_TX_BRDY_THD()                                OP_FLD_RD(REG_ACU_READY_THD, 0, 15)
    #define  RST_ACU_TX_BRDY_THD()                                OP_FLD_WR(REG_ACU_READY_THD, 0, 15, 0x20)

    //Field: ACU_RX_BRDY_THD
    #define  FLD_LSB_ACU_RX_BRDY_THD()                            (16)
    #define  FLD_MSB_ACU_RX_BRDY_THD()                            (31)
    #define  FLD_MASK_ACU_RX_BRDY_THD()                           (FLD_MASK(16, 31))
    #define  FLD_MWD_ACU_RX_BRDY_THD(v)                           (FLD_MWD(16, 31, v))
    #define  FLD_MRD_ACU_RX_BRDY_THD(v)                           (FLD_MRD(16, 31, v))
    #define  SET_ACU_RX_BRDY_THD(v)                               OP_FLD_WR(REG_ACU_READY_THD, 16, 31, v)
    #define  GET_ACU_RX_BRDY_THD()                                OP_FLD_RD(REG_ACU_READY_THD, 16, 31)
    #define  RST_ACU_RX_BRDY_THD()                                OP_FLD_WR(REG_ACU_READY_THD, 16, 31, 0x20)

    //Write-Register Using Field-Name
    #define  WRF_ACU_READY_THD(TX_BRDY_THD,RX_BRDY_THD) \
                (WR_ACU_READY_THD( \
                  (FLD_MWD_ACU_TX_BRDY_THD(TX_BRDY_THD))                               | \
                  (FLD_MWD_ACU_RX_BRDY_THD(RX_BRDY_THD))                                 \
                ))


#define  REG_ACU_KEY_INTR_THD                                     (REG_BASE_ACU + 0x014)
    //Read/Write-Register Using Address
    #define  RD_ACU_KEY_INTR_THD()                                (REG32(REG_ACU_KEY_INTR_THD))
    #define  WR_ACU_KEY_INTR_THD(v)                               (REG32(REG_ACU_KEY_INTR_THD) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_KEY_INTR_THD()                         (0xFFFFFFFF)  
    #define  REG_WMASK_ACU_KEY_INTR_THD()                         (0xFFFFFFFF)

    //Field: ACU_KEY_INTR_THD
    #define  FLD_LSB_ACU_KEY_INTR_THD()                           (0)
    #define  FLD_MSB_ACU_KEY_INTR_THD()                           (31)
    #define  FLD_MASK_ACU_KEY_INTR_THD()                          (FLD_MASK(0, 31))
    #define  FLD_MWD_ACU_KEY_INTR_THD(v)                          (FLD_MWD(0, 31, v))
    #define  FLD_MRD_ACU_KEY_INTR_THD(v)                          (FLD_MRD(0, 31, v))
    #define  SET_ACU_KEY_INTR_THD(v)                              OP_FLD_WR_EXC(REG_ACU_KEY_INTR_THD, 0, 31, v)
    #define  GET_ACU_KEY_INTR_THD()                               OP_FLD_RD(REG_ACU_KEY_INTR_THD, 0, 31)
    #define  RST_ACU_KEY_INTR_THD()                               OP_FLD_WR_EXC(REG_ACU_KEY_INTR_THD, 0, 31, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_ACU_KEY_INTR_THD(KEY_INTR_THD) \
                (WR_ACU_KEY_INTR_THD( \
                  (FLD_MWD_ACU_KEY_INTR_THD(KEY_INTR_THD))                               \
                ))


#define  REG_ACU_INTR_STA                                         (REG_BASE_ACU + 0x018)
    //Read/Write-Register Using Address
    #define  RD_ACU_INTR_STA()                                    (REG32(REG_ACU_INTR_STA))
    #define  WR_ACU_INTR_STA(v)                                   (REG32(REG_ACU_INTR_STA) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_INTR_STA()                             (0x113)  
    #define  REG_WMASK_ACU_INTR_STA()                             (0x113)

    //Field: ACU_RX_INTR
    #define  FLD_LSB_ACU_RX_INTR()                                (0)
    #define  FLD_MSB_ACU_RX_INTR()                                (0)
    #define  FLD_MASK_ACU_RX_INTR()                               (FLD_MASK(0, 0))
    #define  FLD_MWD_ACU_RX_INTR(v)                               (FLD_MWD(0, 0, v))
    #define  FLD_MRD_ACU_RX_INTR(v)                               (FLD_MRD(0, 0, v))
    #define  SET_ACU_RX_INTR(v)                                   OP_FLD_WR(REG_ACU_INTR_STA, 0, 0, v)
    #define  GET_ACU_RX_INTR()                                    OP_FLD_RD(REG_ACU_INTR_STA, 0, 0)
    #define  CLR_ACU_RX_INTR()                                    OP_FLD_WR(REG_ACU_INTR_STA, 0, 0, 1)
    #define  RST_ACU_RX_INTR()                                    OP_FLD_WR(REG_ACU_INTR_STA, 0, 0, 0x1)

    //Field: ACU_TX_INTR
    #define  FLD_LSB_ACU_TX_INTR()                                (1)
    #define  FLD_MSB_ACU_TX_INTR()                                (1)
    #define  FLD_MASK_ACU_TX_INTR()                               (FLD_MASK(1, 1))
    #define  FLD_MWD_ACU_TX_INTR(v)                               (FLD_MWD(1, 1, v))
    #define  FLD_MRD_ACU_TX_INTR(v)                               (FLD_MRD(1, 1, v))
    #define  SET_ACU_TX_INTR(v)                                   OP_FLD_WR(REG_ACU_INTR_STA, 1, 1, v)
    #define  GET_ACU_TX_INTR()                                    OP_FLD_RD(REG_ACU_INTR_STA, 1, 1)
    #define  CLR_ACU_TX_INTR()                                    OP_FLD_WR(REG_ACU_INTR_STA, 1, 1, 1)
    #define  RST_ACU_TX_INTR()                                    OP_FLD_WR(REG_ACU_INTR_STA, 1, 1, 0x1)

    //Field: ACU_CRC_INTR
    #define  FLD_LSB_ACU_CRC_INTR()                               (4)
    #define  FLD_MSB_ACU_CRC_INTR()                               (4)
    #define  FLD_MASK_ACU_CRC_INTR()                              (FLD_MASK(4, 4))
    #define  FLD_MWD_ACU_CRC_INTR(v)                              (FLD_MWD(4, 4, v))
    #define  FLD_MRD_ACU_CRC_INTR(v)                              (FLD_MRD(4, 4, v))
    #define  SET_ACU_CRC_INTR(v)                                  OP_FLD_WR(REG_ACU_INTR_STA, 4, 4, v)
    #define  GET_ACU_CRC_INTR()                                   OP_FLD_RD(REG_ACU_INTR_STA, 4, 4)
    #define  CLR_ACU_CRC_INTR()                                   OP_FLD_WR(REG_ACU_INTR_STA, 4, 4, 1)
    #define  RST_ACU_CRC_INTR()                                   OP_FLD_WR(REG_ACU_INTR_STA, 4, 4, 0x1)

    //Field: ACU_KEY_INTR
    #define  FLD_LSB_ACU_KEY_INTR()                               (8)
    #define  FLD_MSB_ACU_KEY_INTR()                               (8)
    #define  FLD_MASK_ACU_KEY_INTR()                              (FLD_MASK(8, 8))
    #define  FLD_MWD_ACU_KEY_INTR(v)                              (FLD_MWD(8, 8, v))
    #define  FLD_MRD_ACU_KEY_INTR(v)                              (FLD_MRD(8, 8, v))
    #define  SET_ACU_KEY_INTR(v)                                  OP_FLD_WR(REG_ACU_INTR_STA, 8, 8, v)
    #define  GET_ACU_KEY_INTR()                                   OP_FLD_RD(REG_ACU_INTR_STA, 8, 8)
    #define  CLR_ACU_KEY_INTR()                                   OP_FLD_WR(REG_ACU_INTR_STA, 8, 8, 1)
    #define  RST_ACU_KEY_INTR()                                   OP_FLD_WR(REG_ACU_INTR_STA, 8, 8, 0x1)

    //Write-Register Using Field-Name
    #define  WRF_ACU_INTR_STA(RX_INTR,TX_INTR,CRC_INTR,KEY_INTR) \
                (WR_ACU_INTR_STA( \
                  (FLD_MWD_ACU_RX_INTR(RX_INTR))                                       | \
                  (FLD_MWD_ACU_TX_INTR(TX_INTR))                                       | \
                  (FLD_MWD_ACU_CRC_INTR(CRC_INTR))                                     | \
                  (FLD_MWD_ACU_KEY_INTR(KEY_INTR))                                       \
                ))


#define  REG_ACU_INTR_EN                                          (REG_BASE_ACU + 0x01c)
    //Read/Write-Register Using Address
    #define  RD_ACU_INTR_EN()                                     (REG32(REG_ACU_INTR_EN))
    #define  WR_ACU_INTR_EN(v)                                    (REG32(REG_ACU_INTR_EN) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_INTR_EN()                              (0x113)  
    #define  REG_WMASK_ACU_INTR_EN()                              (0x113)

    //Field: ACU_RX_INTR_EN
    #define  FLD_LSB_ACU_RX_INTR_EN()                             (0)
    #define  FLD_MSB_ACU_RX_INTR_EN()                             (0)
    #define  FLD_MASK_ACU_RX_INTR_EN()                            (FLD_MASK(0, 0))
    #define  FLD_MWD_ACU_RX_INTR_EN(v)                            (FLD_MWD(0, 0, v))
    #define  FLD_MRD_ACU_RX_INTR_EN(v)                            (FLD_MRD(0, 0, v))
    #define  SET_ACU_RX_INTR_EN(v)                                OP_FLD_WR(REG_ACU_INTR_EN, 0, 0, v)
    #define  GET_ACU_RX_INTR_EN()                                 OP_FLD_RD(REG_ACU_INTR_EN, 0, 0)
    #define  RST_ACU_RX_INTR_EN()                                 OP_FLD_WR(REG_ACU_INTR_EN, 0, 0, 0x0)

    //Field: ACU_TX_INTR_EN
    #define  FLD_LSB_ACU_TX_INTR_EN()                             (1)
    #define  FLD_MSB_ACU_TX_INTR_EN()                             (1)
    #define  FLD_MASK_ACU_TX_INTR_EN()                            (FLD_MASK(1, 1))
    #define  FLD_MWD_ACU_TX_INTR_EN(v)                            (FLD_MWD(1, 1, v))
    #define  FLD_MRD_ACU_TX_INTR_EN(v)                            (FLD_MRD(1, 1, v))
    #define  SET_ACU_TX_INTR_EN(v)                                OP_FLD_WR(REG_ACU_INTR_EN, 1, 1, v)
    #define  GET_ACU_TX_INTR_EN()                                 OP_FLD_RD(REG_ACU_INTR_EN, 1, 1)
    #define  RST_ACU_TX_INTR_EN()                                 OP_FLD_WR(REG_ACU_INTR_EN, 1, 1, 0x0)

    //Field: ACU_CRC_INTR_EN
    #define  FLD_LSB_ACU_CRC_INTR_EN()                            (4)
    #define  FLD_MSB_ACU_CRC_INTR_EN()                            (4)
    #define  FLD_MASK_ACU_CRC_INTR_EN()                           (FLD_MASK(4, 4))
    #define  FLD_MWD_ACU_CRC_INTR_EN(v)                           (FLD_MWD(4, 4, v))
    #define  FLD_MRD_ACU_CRC_INTR_EN(v)                           (FLD_MRD(4, 4, v))
    #define  SET_ACU_CRC_INTR_EN(v)                               OP_FLD_WR(REG_ACU_INTR_EN, 4, 4, v)
    #define  GET_ACU_CRC_INTR_EN()                                OP_FLD_RD(REG_ACU_INTR_EN, 4, 4)
    #define  RST_ACU_CRC_INTR_EN()                                OP_FLD_WR(REG_ACU_INTR_EN, 4, 4, 0x0)

    //Field: ACU_KEY_INTR_EN
    #define  FLD_LSB_ACU_KEY_INTR_EN()                            (8)
    #define  FLD_MSB_ACU_KEY_INTR_EN()                            (8)
    #define  FLD_MASK_ACU_KEY_INTR_EN()                           (FLD_MASK(8, 8))
    #define  FLD_MWD_ACU_KEY_INTR_EN(v)                           (FLD_MWD(8, 8, v))
    #define  FLD_MRD_ACU_KEY_INTR_EN(v)                           (FLD_MRD(8, 8, v))
    #define  SET_ACU_KEY_INTR_EN(v)                               OP_FLD_WR(REG_ACU_INTR_EN, 8, 8, v)
    #define  GET_ACU_KEY_INTR_EN()                                OP_FLD_RD(REG_ACU_INTR_EN, 8, 8)
    #define  RST_ACU_KEY_INTR_EN()                                OP_FLD_WR(REG_ACU_INTR_EN, 8, 8, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_ACU_INTR_EN(RX_INTR_EN,TX_INTR_EN,CRC_INTR_EN,KEY_INTR_EN) \
                (WR_ACU_INTR_EN( \
                  (FLD_MWD_ACU_RX_INTR_EN(RX_INTR_EN))                                 | \
                  (FLD_MWD_ACU_TX_INTR_EN(TX_INTR_EN))                                 | \
                  (FLD_MWD_ACU_CRC_INTR_EN(CRC_INTR_EN))                               | \
                  (FLD_MWD_ACU_KEY_INTR_EN(KEY_INTR_EN))                                 \
                ))


#define  REG_ACU_REG_BUS_CLK_CFG                                  (REG_BASE_ACU + 0x020)
    //Read/Write-Register Using Address
    #define  RD_ACU_REG_BUS_CLK_CFG()                             (REG32(REG_ACU_REG_BUS_CLK_CFG))
    #define  WR_ACU_REG_BUS_CLK_CFG(v)                            (REG32(REG_ACU_REG_BUS_CLK_CFG) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_REG_BUS_CLK_CFG()                      (0x1)  
    #define  REG_WMASK_ACU_REG_BUS_CLK_CFG()                      (0x1)

    //Field: ACU_REG_BUS_CLK_GATE_MODE
    #define  FLD_LSB_ACU_REG_BUS_CLK_GATE_MODE()                  (0)
    #define  FLD_MSB_ACU_REG_BUS_CLK_GATE_MODE()                  (0)
    #define  FLD_MASK_ACU_REG_BUS_CLK_GATE_MODE()                 (FLD_MASK(0, 0))
    #define  FLD_MWD_ACU_REG_BUS_CLK_GATE_MODE(v)                 (FLD_MWD(0, 0, v))
    #define  FLD_MRD_ACU_REG_BUS_CLK_GATE_MODE(v)                 (FLD_MRD(0, 0, v))
    #define  SET_ACU_REG_BUS_CLK_GATE_MODE(v)                     OP_FLD_WR_EXC(REG_ACU_REG_BUS_CLK_CFG, 0, 0, v)
    #define  GET_ACU_REG_BUS_CLK_GATE_MODE()                      OP_FLD_RD(REG_ACU_REG_BUS_CLK_CFG, 0, 0)
    #define  RST_ACU_REG_BUS_CLK_GATE_MODE()                      OP_FLD_WR_EXC(REG_ACU_REG_BUS_CLK_CFG, 0, 0, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_ACU_REG_BUS_CLK_CFG(REG_BUS_CLK_GATE_MODE) \
                (WR_ACU_REG_BUS_CLK_CFG( \
                  (FLD_MWD_ACU_REG_BUS_CLK_GATE_MODE(REG_BUS_CLK_GATE_MODE))             \
                ))


//------------------------------------
// Key Registers
//------------------------------------
#define  REG_ACU_KEY_0_                                           (REG_BASE_ACU + 0x040)
    //Read/Write-Register Using Address
    #define  RD_ACU_KEY_0_()                                      (REG32(REG_ACU_KEY_0_))
    #define  WR_ACU_KEY_0_(v)                                     (REG32(REG_ACU_KEY_0_) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_KEY_0_()                               (0xFFFFFFFF)  
    #define  REG_WMASK_ACU_KEY_0_()                               (0xFFFFFFFF)

    //Field: ACU_KEY_0_
    #define  FLD_LSB_ACU_KEY_0_()                                 (0)
    #define  FLD_MSB_ACU_KEY_0_()                                 (31)
    #define  FLD_MASK_ACU_KEY_0_()                                (FLD_MASK(0, 31))
    #define  FLD_MWD_ACU_KEY_0_(v)                                (FLD_MWD(0, 31, v))
    #define  FLD_MRD_ACU_KEY_0_(v)                                (FLD_MRD(0, 31, v))
    #define  SET_ACU_KEY_0_(v)                                    OP_FLD_WR_EXC(REG_ACU_KEY_0_, 0, 31, v)
    #define  GET_ACU_KEY_0_()                                     OP_FLD_RD(REG_ACU_KEY_0_, 0, 31)
    #define  RST_ACU_KEY_0_()                                     OP_FLD_WR_EXC(REG_ACU_KEY_0_, 0, 31, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_ACU_KEY_0_(KEY_0_) \
                (WR_ACU_KEY_0_( \
                  (FLD_MWD_ACU_KEY_0_(KEY_0_))                                           \
                ))


#define  REG_ACU_KEY_1_                                           (REG_BASE_ACU + 0x044)
    //Read/Write-Register Using Address
    #define  RD_ACU_KEY_1_()                                      (REG32(REG_ACU_KEY_1_))
    #define  WR_ACU_KEY_1_(v)                                     (REG32(REG_ACU_KEY_1_) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_KEY_1_()                               (0xFFFFFFFF)  
    #define  REG_WMASK_ACU_KEY_1_()                               (0xFFFFFFFF)

    //Field: ACU_KEY_1_
    #define  FLD_LSB_ACU_KEY_1_()                                 (0)
    #define  FLD_MSB_ACU_KEY_1_()                                 (31)
    #define  FLD_MASK_ACU_KEY_1_()                                (FLD_MASK(0, 31))
    #define  FLD_MWD_ACU_KEY_1_(v)                                (FLD_MWD(0, 31, v))
    #define  FLD_MRD_ACU_KEY_1_(v)                                (FLD_MRD(0, 31, v))
    #define  SET_ACU_KEY_1_(v)                                    OP_FLD_WR_EXC(REG_ACU_KEY_1_, 0, 31, v)
    #define  GET_ACU_KEY_1_()                                     OP_FLD_RD(REG_ACU_KEY_1_, 0, 31)
    #define  RST_ACU_KEY_1_()                                     OP_FLD_WR_EXC(REG_ACU_KEY_1_, 0, 31, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_ACU_KEY_1_(KEY_1_) \
                (WR_ACU_KEY_1_( \
                  (FLD_MWD_ACU_KEY_1_(KEY_1_))                                           \
                ))


#define  REG_ACU_KEY_2_                                           (REG_BASE_ACU + 0x048)
    //Read/Write-Register Using Address
    #define  RD_ACU_KEY_2_()                                      (REG32(REG_ACU_KEY_2_))
    #define  WR_ACU_KEY_2_(v)                                     (REG32(REG_ACU_KEY_2_) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_KEY_2_()                               (0xFFFFFFFF)  
    #define  REG_WMASK_ACU_KEY_2_()                               (0xFFFFFFFF)

    //Field: ACU_KEY_2_
    #define  FLD_LSB_ACU_KEY_2_()                                 (0)
    #define  FLD_MSB_ACU_KEY_2_()                                 (31)
    #define  FLD_MASK_ACU_KEY_2_()                                (FLD_MASK(0, 31))
    #define  FLD_MWD_ACU_KEY_2_(v)                                (FLD_MWD(0, 31, v))
    #define  FLD_MRD_ACU_KEY_2_(v)                                (FLD_MRD(0, 31, v))
    #define  SET_ACU_KEY_2_(v)                                    OP_FLD_WR_EXC(REG_ACU_KEY_2_, 0, 31, v)
    #define  GET_ACU_KEY_2_()                                     OP_FLD_RD(REG_ACU_KEY_2_, 0, 31)
    #define  RST_ACU_KEY_2_()                                     OP_FLD_WR_EXC(REG_ACU_KEY_2_, 0, 31, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_ACU_KEY_2_(KEY_2_) \
                (WR_ACU_KEY_2_( \
                  (FLD_MWD_ACU_KEY_2_(KEY_2_))                                           \
                ))


#define  REG_ACU_KEY_3_                                           (REG_BASE_ACU + 0x04c)
    //Read/Write-Register Using Address
    #define  RD_ACU_KEY_3_()                                      (REG32(REG_ACU_KEY_3_))
    #define  WR_ACU_KEY_3_(v)                                     (REG32(REG_ACU_KEY_3_) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_KEY_3_()                               (0xFFFFFFFF)  
    #define  REG_WMASK_ACU_KEY_3_()                               (0xFFFFFFFF)

    //Field: ACU_KEY_3_
    #define  FLD_LSB_ACU_KEY_3_()                                 (0)
    #define  FLD_MSB_ACU_KEY_3_()                                 (31)
    #define  FLD_MASK_ACU_KEY_3_()                                (FLD_MASK(0, 31))
    #define  FLD_MWD_ACU_KEY_3_(v)                                (FLD_MWD(0, 31, v))
    #define  FLD_MRD_ACU_KEY_3_(v)                                (FLD_MRD(0, 31, v))
    #define  SET_ACU_KEY_3_(v)                                    OP_FLD_WR_EXC(REG_ACU_KEY_3_, 0, 31, v)
    #define  GET_ACU_KEY_3_()                                     OP_FLD_RD(REG_ACU_KEY_3_, 0, 31)
    #define  RST_ACU_KEY_3_()                                     OP_FLD_WR_EXC(REG_ACU_KEY_3_, 0, 31, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_ACU_KEY_3_(KEY_3_) \
                (WR_ACU_KEY_3_( \
                  (FLD_MWD_ACU_KEY_3_(KEY_3_))                                           \
                ))


//------------------------------------
// Key read out Registers
//------------------------------------
#define  REG_ACU_KEY_RD_0_                                        (REG_BASE_ACU + 0x050)
    //Read/Write-Register Using Address
    #define  RD_ACU_KEY_RD_0_()                                   (REG32(REG_ACU_KEY_RD_0_))
    #define  WR_ACU_KEY_RD_0_(v)                                  (REG32(REG_ACU_KEY_RD_0_) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_KEY_RD_0_()                            (0xFFFFFFFF)  
    #define  REG_WMASK_ACU_KEY_RD_0_()                            (0x0)

    //Field: ACU_KEY_RD_0_
    #define  FLD_LSB_ACU_KEY_RD_0_()                              (0)
    #define  FLD_MSB_ACU_KEY_RD_0_()                              (31)
    #define  FLD_MASK_ACU_KEY_RD_0_()                             (FLD_MASK(0, 31))
    #define  FLD_MWD_ACU_KEY_RD_0_(v)                             (FLD_MWD(0, 31, v))
    #define  FLD_MRD_ACU_KEY_RD_0_(v)                             (FLD_MRD(0, 31, v))
    #define  GET_ACU_KEY_RD_0_()                                  OP_FLD_RD(REG_ACU_KEY_RD_0_, 0, 31)

    //Write-Register Using Field-Name
    #define  WRF_ACU_KEY_RD_0_(KEY_RD_0_) \
                (WR_ACU_KEY_RD_0_( \
   \
                ))


#define  REG_ACU_KEY_RD_1_                                        (REG_BASE_ACU + 0x054)
    //Read/Write-Register Using Address
    #define  RD_ACU_KEY_RD_1_()                                   (REG32(REG_ACU_KEY_RD_1_))
    #define  WR_ACU_KEY_RD_1_(v)                                  (REG32(REG_ACU_KEY_RD_1_) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_KEY_RD_1_()                            (0xFFFFFFFF)  
    #define  REG_WMASK_ACU_KEY_RD_1_()                            (0x0)

    //Field: ACU_KEY_RD_1_
    #define  FLD_LSB_ACU_KEY_RD_1_()                              (0)
    #define  FLD_MSB_ACU_KEY_RD_1_()                              (31)
    #define  FLD_MASK_ACU_KEY_RD_1_()                             (FLD_MASK(0, 31))
    #define  FLD_MWD_ACU_KEY_RD_1_(v)                             (FLD_MWD(0, 31, v))
    #define  FLD_MRD_ACU_KEY_RD_1_(v)                             (FLD_MRD(0, 31, v))
    #define  GET_ACU_KEY_RD_1_()                                  OP_FLD_RD(REG_ACU_KEY_RD_1_, 0, 31)

    //Write-Register Using Field-Name
    #define  WRF_ACU_KEY_RD_1_(KEY_RD_1_) \
                (WR_ACU_KEY_RD_1_( \
   \
                ))


#define  REG_ACU_KEY_RD_2_                                        (REG_BASE_ACU + 0x058)
    //Read/Write-Register Using Address
    #define  RD_ACU_KEY_RD_2_()                                   (REG32(REG_ACU_KEY_RD_2_))
    #define  WR_ACU_KEY_RD_2_(v)                                  (REG32(REG_ACU_KEY_RD_2_) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_KEY_RD_2_()                            (0xFFFFFFFF)  
    #define  REG_WMASK_ACU_KEY_RD_2_()                            (0x0)

    //Field: ACU_KEY_RD_2_
    #define  FLD_LSB_ACU_KEY_RD_2_()                              (0)
    #define  FLD_MSB_ACU_KEY_RD_2_()                              (31)
    #define  FLD_MASK_ACU_KEY_RD_2_()                             (FLD_MASK(0, 31))
    #define  FLD_MWD_ACU_KEY_RD_2_(v)                             (FLD_MWD(0, 31, v))
    #define  FLD_MRD_ACU_KEY_RD_2_(v)                             (FLD_MRD(0, 31, v))
    #define  GET_ACU_KEY_RD_2_()                                  OP_FLD_RD(REG_ACU_KEY_RD_2_, 0, 31)

    //Write-Register Using Field-Name
    #define  WRF_ACU_KEY_RD_2_(KEY_RD_2_) \
                (WR_ACU_KEY_RD_2_( \
   \
                ))


#define  REG_ACU_KEY_RD_3_                                        (REG_BASE_ACU + 0x05c)
    //Read/Write-Register Using Address
    #define  RD_ACU_KEY_RD_3_()                                   (REG32(REG_ACU_KEY_RD_3_))
    #define  WR_ACU_KEY_RD_3_(v)                                  (REG32(REG_ACU_KEY_RD_3_) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_KEY_RD_3_()                            (0xFFFFFFFF)  
    #define  REG_WMASK_ACU_KEY_RD_3_()                            (0x0)

    //Field: ACU_KEY_RD_3_
    #define  FLD_LSB_ACU_KEY_RD_3_()                              (0)
    #define  FLD_MSB_ACU_KEY_RD_3_()                              (31)
    #define  FLD_MASK_ACU_KEY_RD_3_()                             (FLD_MASK(0, 31))
    #define  FLD_MWD_ACU_KEY_RD_3_(v)                             (FLD_MWD(0, 31, v))
    #define  FLD_MRD_ACU_KEY_RD_3_(v)                             (FLD_MRD(0, 31, v))
    #define  GET_ACU_KEY_RD_3_()                                  OP_FLD_RD(REG_ACU_KEY_RD_3_, 0, 31)

    //Write-Register Using Field-Name
    #define  WRF_ACU_KEY_RD_3_(KEY_RD_3_) \
                (WR_ACU_KEY_RD_3_( \
   \
                ))


//------------------------------------
// Initial Vector Registers
//------------------------------------
#define  REG_ACU_IV_0_                                            (REG_BASE_ACU + 0x060)
    //Read/Write-Register Using Address
    #define  RD_ACU_IV_0_()                                       (REG32(REG_ACU_IV_0_))
    #define  WR_ACU_IV_0_(v)                                      (REG32(REG_ACU_IV_0_) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_IV_0_()                                (0xFFFFFFFF)  
    #define  REG_WMASK_ACU_IV_0_()                                (0xFFFFFFFF)

    //Field: ACU_IV_0_
    #define  FLD_LSB_ACU_IV_0_()                                  (0)
    #define  FLD_MSB_ACU_IV_0_()                                  (31)
    #define  FLD_MASK_ACU_IV_0_()                                 (FLD_MASK(0, 31))
    #define  FLD_MWD_ACU_IV_0_(v)                                 (FLD_MWD(0, 31, v))
    #define  FLD_MRD_ACU_IV_0_(v)                                 (FLD_MRD(0, 31, v))
    #define  SET_ACU_IV_0_(v)                                     OP_FLD_WR_EXC(REG_ACU_IV_0_, 0, 31, v)
    #define  GET_ACU_IV_0_()                                      OP_FLD_RD(REG_ACU_IV_0_, 0, 31)
    #define  RST_ACU_IV_0_()                                      OP_FLD_WR_EXC(REG_ACU_IV_0_, 0, 31, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_ACU_IV_0_(IV_0_) \
                (WR_ACU_IV_0_( \
                  (FLD_MWD_ACU_IV_0_(IV_0_))                                             \
                ))


#define  REG_ACU_IV_1_                                            (REG_BASE_ACU + 0x064)
    //Read/Write-Register Using Address
    #define  RD_ACU_IV_1_()                                       (REG32(REG_ACU_IV_1_))
    #define  WR_ACU_IV_1_(v)                                      (REG32(REG_ACU_IV_1_) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_IV_1_()                                (0xFFFFFFFF)  
    #define  REG_WMASK_ACU_IV_1_()                                (0xFFFFFFFF)

    //Field: ACU_IV_1_
    #define  FLD_LSB_ACU_IV_1_()                                  (0)
    #define  FLD_MSB_ACU_IV_1_()                                  (31)
    #define  FLD_MASK_ACU_IV_1_()                                 (FLD_MASK(0, 31))
    #define  FLD_MWD_ACU_IV_1_(v)                                 (FLD_MWD(0, 31, v))
    #define  FLD_MRD_ACU_IV_1_(v)                                 (FLD_MRD(0, 31, v))
    #define  SET_ACU_IV_1_(v)                                     OP_FLD_WR_EXC(REG_ACU_IV_1_, 0, 31, v)
    #define  GET_ACU_IV_1_()                                      OP_FLD_RD(REG_ACU_IV_1_, 0, 31)
    #define  RST_ACU_IV_1_()                                      OP_FLD_WR_EXC(REG_ACU_IV_1_, 0, 31, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_ACU_IV_1_(IV_1_) \
                (WR_ACU_IV_1_( \
                  (FLD_MWD_ACU_IV_1_(IV_1_))                                             \
                ))


#define  REG_ACU_IV_2_                                            (REG_BASE_ACU + 0x068)
    //Read/Write-Register Using Address
    #define  RD_ACU_IV_2_()                                       (REG32(REG_ACU_IV_2_))
    #define  WR_ACU_IV_2_(v)                                      (REG32(REG_ACU_IV_2_) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_IV_2_()                                (0xFFFFFFFF)  
    #define  REG_WMASK_ACU_IV_2_()                                (0xFFFFFFFF)

    //Field: ACU_IV_2_
    #define  FLD_LSB_ACU_IV_2_()                                  (0)
    #define  FLD_MSB_ACU_IV_2_()                                  (31)
    #define  FLD_MASK_ACU_IV_2_()                                 (FLD_MASK(0, 31))
    #define  FLD_MWD_ACU_IV_2_(v)                                 (FLD_MWD(0, 31, v))
    #define  FLD_MRD_ACU_IV_2_(v)                                 (FLD_MRD(0, 31, v))
    #define  SET_ACU_IV_2_(v)                                     OP_FLD_WR_EXC(REG_ACU_IV_2_, 0, 31, v)
    #define  GET_ACU_IV_2_()                                      OP_FLD_RD(REG_ACU_IV_2_, 0, 31)
    #define  RST_ACU_IV_2_()                                      OP_FLD_WR_EXC(REG_ACU_IV_2_, 0, 31, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_ACU_IV_2_(IV_2_) \
                (WR_ACU_IV_2_( \
                  (FLD_MWD_ACU_IV_2_(IV_2_))                                             \
                ))


#define  REG_ACU_IV_3_                                            (REG_BASE_ACU + 0x06c)
    //Read/Write-Register Using Address
    #define  RD_ACU_IV_3_()                                       (REG32(REG_ACU_IV_3_))
    #define  WR_ACU_IV_3_(v)                                      (REG32(REG_ACU_IV_3_) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_IV_3_()                                (0xFFFFFFFF)  
    #define  REG_WMASK_ACU_IV_3_()                                (0xFFFFFFFF)

    //Field: ACU_IV_3_
    #define  FLD_LSB_ACU_IV_3_()                                  (0)
    #define  FLD_MSB_ACU_IV_3_()                                  (31)
    #define  FLD_MASK_ACU_IV_3_()                                 (FLD_MASK(0, 31))
    #define  FLD_MWD_ACU_IV_3_(v)                                 (FLD_MWD(0, 31, v))
    #define  FLD_MRD_ACU_IV_3_(v)                                 (FLD_MRD(0, 31, v))
    #define  SET_ACU_IV_3_(v)                                     OP_FLD_WR_EXC(REG_ACU_IV_3_, 0, 31, v)
    #define  GET_ACU_IV_3_()                                      OP_FLD_RD(REG_ACU_IV_3_, 0, 31)
    #define  RST_ACU_IV_3_()                                      OP_FLD_WR_EXC(REG_ACU_IV_3_, 0, 31, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_ACU_IV_3_(IV_3_) \
                (WR_ACU_IV_3_( \
                  (FLD_MWD_ACU_IV_3_(IV_3_))                                             \
                ))


//------------------------------------
// Others
//------------------------------------
#define  REG_ACU_KEY_COUNT                                        (REG_BASE_ACU + 0x070)
    //Read/Write-Register Using Address
    #define  RD_ACU_KEY_COUNT()                                   (REG32(REG_ACU_KEY_COUNT))
    #define  WR_ACU_KEY_COUNT(v)                                  (REG32(REG_ACU_KEY_COUNT) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_KEY_COUNT()                            (0xFFFFFFFF)  
    #define  REG_WMASK_ACU_KEY_COUNT()                            (0xFFFFFFFF)

    //Field: ACU_KEY_COUNT
    #define  FLD_LSB_ACU_KEY_COUNT()                              (0)
    #define  FLD_MSB_ACU_KEY_COUNT()                              (31)
    #define  FLD_MASK_ACU_KEY_COUNT()                             (FLD_MASK(0, 31))
    #define  FLD_MWD_ACU_KEY_COUNT(v)                             (FLD_MWD(0, 31, v))
    #define  FLD_MRD_ACU_KEY_COUNT(v)                             (FLD_MRD(0, 31, v))
    #define  SET_ACU_KEY_COUNT(v)                                 OP_FLD_WR_EXC(REG_ACU_KEY_COUNT, 0, 31, v)
    #define  GET_ACU_KEY_COUNT()                                  OP_FLD_RD(REG_ACU_KEY_COUNT, 0, 31)
    #define  RST_ACU_KEY_COUNT()                                  OP_FLD_WR_EXC(REG_ACU_KEY_COUNT, 0, 31, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_ACU_KEY_COUNT(KEY_COUNT) \
                (WR_ACU_KEY_COUNT( \
                  (FLD_MWD_ACU_KEY_COUNT(KEY_COUNT))                                     \
                ))


#define  REG_ACU_BUF_STATUS                                       (REG_BASE_ACU + 0x074)
    //Read/Write-Register Using Address
    #define  RD_ACU_BUF_STATUS()                                  (REG32(REG_ACU_BUF_STATUS))
    #define  WR_ACU_BUF_STATUS(v)                                 (REG32(REG_ACU_BUF_STATUS) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_BUF_STATUS()                           (0xFFFFFFFF)  
    #define  REG_WMASK_ACU_BUF_STATUS()                           (0x0)

    //Field: ACU_RX_BUF_COUNT
    #define  FLD_LSB_ACU_RX_BUF_COUNT()                           (0)
    #define  FLD_MSB_ACU_RX_BUF_COUNT()                           (15)
    #define  FLD_MASK_ACU_RX_BUF_COUNT()                          (FLD_MASK(0, 15))
    #define  FLD_MWD_ACU_RX_BUF_COUNT(v)                          (FLD_MWD(0, 15, v))
    #define  FLD_MRD_ACU_RX_BUF_COUNT(v)                          (FLD_MRD(0, 15, v))
    #define  GET_ACU_RX_BUF_COUNT()                               OP_FLD_RD(REG_ACU_BUF_STATUS, 0, 15)

    //Field: ACU_TX_BUF_COUNT
    #define  FLD_LSB_ACU_TX_BUF_COUNT()                           (16)
    #define  FLD_MSB_ACU_TX_BUF_COUNT()                           (31)
    #define  FLD_MASK_ACU_TX_BUF_COUNT()                          (FLD_MASK(16, 31))
    #define  FLD_MWD_ACU_TX_BUF_COUNT(v)                          (FLD_MWD(16, 31, v))
    #define  FLD_MRD_ACU_TX_BUF_COUNT(v)                          (FLD_MRD(16, 31, v))
    #define  GET_ACU_TX_BUF_COUNT()                               OP_FLD_RD(REG_ACU_BUF_STATUS, 16, 31)

    //Write-Register Using Field-Name
    #define  WRF_ACU_BUF_STATUS(RX_BUF_COUNT,TX_BUF_COUNT) \
                (WR_ACU_BUF_STATUS( \
   \
                ))


//------------------------------------
// UCRC Ctrl
//------------------------------------
#define  REG_ACU_CRC_OP                                           (REG_BASE_ACU + 0x090)
    //Read/Write-Register Using Address
    #define  RD_ACU_CRC_OP()                                      (REG32(REG_ACU_CRC_OP))
    #define  WR_ACU_CRC_OP(v)                                     (REG32(REG_ACU_CRC_OP) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_CRC_OP()                               (0x303F0000)  
    #define  REG_WMASK_ACU_CRC_OP()                               (0x101)

    //Field: ACU_CRC_START
    #define  FLD_LSB_ACU_CRC_START()                              (0)
    #define  FLD_MSB_ACU_CRC_START()                              (0)
    #define  FLD_MASK_ACU_CRC_START()                             (FLD_MASK(0, 0))
    #define  FLD_MWD_ACU_CRC_START(v)                             (FLD_MWD(0, 0, v))
    #define  FLD_MRD_ACU_CRC_START(v)                             (FLD_MRD(0, 0, v))
    #define  SET_ACU_CRC_START(v)                                 OP_FLD_WR(REG_ACU_CRC_OP, 0, 0, v)
    #define  RST_ACU_CRC_START()                                  OP_FLD_WR(REG_ACU_CRC_OP, 0, 0, 0x0)

    //Field: ACU_CRC_CLR
    #define  FLD_LSB_ACU_CRC_CLR()                                (8)
    #define  FLD_MSB_ACU_CRC_CLR()                                (8)
    #define  FLD_MASK_ACU_CRC_CLR()                               (FLD_MASK(8, 8))
    #define  FLD_MWD_ACU_CRC_CLR(v)                               (FLD_MWD(8, 8, v))
    #define  FLD_MRD_ACU_CRC_CLR(v)                               (FLD_MRD(8, 8, v))
    #define  SET_ACU_CRC_CLR(v)                                   OP_FLD_WR(REG_ACU_CRC_OP, 8, 8, v)
    #define  RST_ACU_CRC_CLR()                                    OP_FLD_WR(REG_ACU_CRC_OP, 8, 8, 0x0)

    //Field: ACU_CRC_STATUS
    #define  FLD_LSB_ACU_CRC_STATUS()                             (16)
    #define  FLD_MSB_ACU_CRC_STATUS()                             (21)
    #define  FLD_MASK_ACU_CRC_STATUS()                            (FLD_MASK(16, 21))
    #define  FLD_MWD_ACU_CRC_STATUS(v)                            (FLD_MWD(16, 21, v))
    #define  FLD_MRD_ACU_CRC_STATUS(v)                            (FLD_MRD(16, 21, v))
    #define  GET_ACU_CRC_STATUS()                                 OP_FLD_RD(REG_ACU_CRC_OP, 16, 21)

    //Field: ACU_CRC_FSM
    #define  FLD_LSB_ACU_CRC_FSM()                                (28)
    #define  FLD_MSB_ACU_CRC_FSM()                                (29)
    #define  FLD_MASK_ACU_CRC_FSM()                               (FLD_MASK(28, 29))
    #define  FLD_MWD_ACU_CRC_FSM(v)                               (FLD_MWD(28, 29, v))
    #define  FLD_MRD_ACU_CRC_FSM(v)                               (FLD_MRD(28, 29, v))
    #define  GET_ACU_CRC_FSM()                                    OP_FLD_RD(REG_ACU_CRC_OP, 28, 29)

    //Write-Register Using Field-Name
    #define  WRF_ACU_CRC_OP(CRC_START,CRC_CLR,CRC_STATUS,CRC_FSM) \
                (WR_ACU_CRC_OP( \
                  (FLD_MWD_ACU_CRC_START(CRC_START))                                   | \
                  (FLD_MWD_ACU_CRC_CLR(CRC_CLR))                                         \
                ))


#define  REG_ACU_CRC_BASE_CFG                                     (REG_BASE_ACU + 0x094)
    //Read/Write-Register Using Address
    #define  RD_ACU_CRC_BASE_CFG()                                (REG32(REG_ACU_CRC_BASE_CFG))
    #define  WR_ACU_CRC_BASE_CFG(v)                               (REG32(REG_ACU_CRC_BASE_CFG) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_CRC_BASE_CFG()                         (0x111)  
    #define  REG_WMASK_ACU_CRC_BASE_CFG()                         (0x111)

    //Field: ACU_CRC_MODE
    #define  FLD_LSB_ACU_CRC_MODE()                               (0)
    #define  FLD_MSB_ACU_CRC_MODE()                               (0)
    #define  FLD_MASK_ACU_CRC_MODE()                              (FLD_MASK(0, 0))
    #define  FLD_MWD_ACU_CRC_MODE(v)                              (FLD_MWD(0, 0, v))
    #define  FLD_MRD_ACU_CRC_MODE(v)                              (FLD_MRD(0, 0, v))
    #define  SET_ACU_CRC_MODE(v)                                  OP_FLD_WR(REG_ACU_CRC_BASE_CFG, 0, 0, v)
    #define  GET_ACU_CRC_MODE()                                   OP_FLD_RD(REG_ACU_CRC_BASE_CFG, 0, 0)
    #define  RST_ACU_CRC_MODE()                                   OP_FLD_WR(REG_ACU_CRC_BASE_CFG, 0, 0, 0x1)

    //Field: ACU_CRC_INIT_VALUE
    #define  FLD_LSB_ACU_CRC_INIT_VALUE()                         (4)
    #define  FLD_MSB_ACU_CRC_INIT_VALUE()                         (4)
    #define  FLD_MASK_ACU_CRC_INIT_VALUE()                        (FLD_MASK(4, 4))
    #define  FLD_MWD_ACU_CRC_INIT_VALUE(v)                        (FLD_MWD(4, 4, v))
    #define  FLD_MRD_ACU_CRC_INIT_VALUE(v)                        (FLD_MRD(4, 4, v))
    #define  SET_ACU_CRC_INIT_VALUE(v)                            OP_FLD_WR(REG_ACU_CRC_BASE_CFG, 4, 4, v)
    #define  GET_ACU_CRC_INIT_VALUE()                             OP_FLD_RD(REG_ACU_CRC_BASE_CFG, 4, 4)
    #define  RST_ACU_CRC_INIT_VALUE()                             OP_FLD_WR(REG_ACU_CRC_BASE_CFG, 4, 4, 0x1)

    //Field: ACU_CRC_XOROUT
    #define  FLD_LSB_ACU_CRC_XOROUT()                             (8)
    #define  FLD_MSB_ACU_CRC_XOROUT()                             (8)
    #define  FLD_MASK_ACU_CRC_XOROUT()                            (FLD_MASK(8, 8))
    #define  FLD_MWD_ACU_CRC_XOROUT(v)                            (FLD_MWD(8, 8, v))
    #define  FLD_MRD_ACU_CRC_XOROUT(v)                            (FLD_MRD(8, 8, v))
    #define  SET_ACU_CRC_XOROUT(v)                                OP_FLD_WR(REG_ACU_CRC_BASE_CFG, 8, 8, v)
    #define  GET_ACU_CRC_XOROUT()                                 OP_FLD_RD(REG_ACU_CRC_BASE_CFG, 8, 8)
    #define  RST_ACU_CRC_XOROUT()                                 OP_FLD_WR(REG_ACU_CRC_BASE_CFG, 8, 8, 0x1)

    //Write-Register Using Field-Name
    #define  WRF_ACU_CRC_BASE_CFG(CRC_MODE,CRC_INIT_VALUE,CRC_XOROUT) \
                (WR_ACU_CRC_BASE_CFG( \
                  (FLD_MWD_ACU_CRC_MODE(CRC_MODE))                                     | \
                  (FLD_MWD_ACU_CRC_INIT_VALUE(CRC_INIT_VALUE))                         | \
                  (FLD_MWD_ACU_CRC_XOROUT(CRC_XOROUT))                                   \
                ))


#define  REG_ACU_CRC_MISC_CFG                                     (REG_BASE_ACU + 0x098)
    //Read/Write-Register Using Address
    #define  RD_ACU_CRC_MISC_CFG()                                (REG32(REG_ACU_CRC_MISC_CFG))
    #define  WR_ACU_CRC_MISC_CFG(v)                               (REG32(REG_ACU_CRC_MISC_CFG) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_CRC_MISC_CFG()                         (0x80000011)  
    #define  REG_WMASK_ACU_CRC_MISC_CFG()                         (0x80000011)

    //Field: ACU_CRC_REFOUT
    #define  FLD_LSB_ACU_CRC_REFOUT()                             (0)
    #define  FLD_MSB_ACU_CRC_REFOUT()                             (0)
    #define  FLD_MASK_ACU_CRC_REFOUT()                            (FLD_MASK(0, 0))
    #define  FLD_MWD_ACU_CRC_REFOUT(v)                            (FLD_MWD(0, 0, v))
    #define  FLD_MRD_ACU_CRC_REFOUT(v)                            (FLD_MRD(0, 0, v))
    #define  SET_ACU_CRC_REFOUT(v)                                OP_FLD_WR(REG_ACU_CRC_MISC_CFG, 0, 0, v)
    #define  GET_ACU_CRC_REFOUT()                                 OP_FLD_RD(REG_ACU_CRC_MISC_CFG, 0, 0)
    #define  RST_ACU_CRC_REFOUT()                                 OP_FLD_WR(REG_ACU_CRC_MISC_CFG, 0, 0, 0x1)

    //Field: ACU_CRC_REFIN
    #define  FLD_LSB_ACU_CRC_REFIN()                              (4)
    #define  FLD_MSB_ACU_CRC_REFIN()                              (4)
    #define  FLD_MASK_ACU_CRC_REFIN()                             (FLD_MASK(4, 4))
    #define  FLD_MWD_ACU_CRC_REFIN(v)                             (FLD_MWD(4, 4, v))
    #define  FLD_MRD_ACU_CRC_REFIN(v)                             (FLD_MRD(4, 4, v))
    #define  SET_ACU_CRC_REFIN(v)                                 OP_FLD_WR(REG_ACU_CRC_MISC_CFG, 4, 4, v)
    #define  GET_ACU_CRC_REFIN()                                  OP_FLD_RD(REG_ACU_CRC_MISC_CFG, 4, 4)
    #define  RST_ACU_CRC_REFIN()                                  OP_FLD_WR(REG_ACU_CRC_MISC_CFG, 4, 4, 0x0)

    //Field: ACU_CRC_FIFO_ERR
    #define  FLD_LSB_ACU_CRC_FIFO_ERR()                           (31)
    #define  FLD_MSB_ACU_CRC_FIFO_ERR()                           (31)
    #define  FLD_MASK_ACU_CRC_FIFO_ERR()                          (FLD_MASK(31, 31))
    #define  FLD_MWD_ACU_CRC_FIFO_ERR(v)                          (FLD_MWD(31, 31, v))
    #define  FLD_MRD_ACU_CRC_FIFO_ERR(v)                          (FLD_MRD(31, 31, v))
    #define  SET_ACU_CRC_FIFO_ERR(v)                              OP_FLD_WR(REG_ACU_CRC_MISC_CFG, 31, 31, v)
    #define  GET_ACU_CRC_FIFO_ERR()                               OP_FLD_RD(REG_ACU_CRC_MISC_CFG, 31, 31)
    #define  CLR_ACU_CRC_FIFO_ERR()                               OP_FLD_WR(REG_ACU_CRC_MISC_CFG, 31, 31, 1)
    #define  RST_ACU_CRC_FIFO_ERR()                               OP_FLD_WR(REG_ACU_CRC_MISC_CFG, 31, 31, 0x1)

    //Write-Register Using Field-Name
    #define  WRF_ACU_CRC_MISC_CFG(CRC_REFOUT,CRC_REFIN,CRC_FIFO_ERR) \
                (WR_ACU_CRC_MISC_CFG( \
                  (FLD_MWD_ACU_CRC_REFOUT(CRC_REFOUT))                                 | \
                  (FLD_MWD_ACU_CRC_REFIN(CRC_REFIN))                                   | \
                  (FLD_MWD_ACU_CRC_FIFO_ERR(CRC_FIFO_ERR))                               \
                ))


#define  REG_ACU_CRC_DATA_CFG                                     (REG_BASE_ACU + 0x09c)
    //Read/Write-Register Using Address
    #define  RD_ACU_CRC_DATA_CFG()                                (REG32(REG_ACU_CRC_DATA_CFG))
    #define  WR_ACU_CRC_DATA_CFG(v)                               (REG32(REG_ACU_CRC_DATA_CFG) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_CRC_DATA_CFG()                         (0xFFFF)  
    #define  REG_WMASK_ACU_CRC_DATA_CFG()                         (0xFFFF)

    //Field: ACU_CRC_DATA_OFFSET
    #define  FLD_LSB_ACU_CRC_DATA_OFFSET()                        (0)
    #define  FLD_MSB_ACU_CRC_DATA_OFFSET()                        (15)
    #define  FLD_MASK_ACU_CRC_DATA_OFFSET()                       (FLD_MASK(0, 15))
    #define  FLD_MWD_ACU_CRC_DATA_OFFSET(v)                       (FLD_MWD(0, 15, v))
    #define  FLD_MRD_ACU_CRC_DATA_OFFSET(v)                       (FLD_MRD(0, 15, v))
    #define  SET_ACU_CRC_DATA_OFFSET(v)                           OP_FLD_WR_EXC(REG_ACU_CRC_DATA_CFG, 0, 15, v)
    #define  GET_ACU_CRC_DATA_OFFSET()                            OP_FLD_RD(REG_ACU_CRC_DATA_CFG, 0, 15)
    #define  RST_ACU_CRC_DATA_OFFSET()                            OP_FLD_WR_EXC(REG_ACU_CRC_DATA_CFG, 0, 15, 0x0)

    //Write-Register Using Field-Name
    #define  WRF_ACU_CRC_DATA_CFG(CRC_DATA_OFFSET) \
                (WR_ACU_CRC_DATA_CFG( \
                  (FLD_MWD_ACU_CRC_DATA_OFFSET(CRC_DATA_OFFSET))                         \
                ))


#define  REG_ACU_CRC                                              (REG_BASE_ACU + 0x0a0)
    //Read/Write-Register Using Address
    #define  RD_ACU_CRC()                                         (REG32(REG_ACU_CRC))
    #define  WR_ACU_CRC(v)                                        (REG32(REG_ACU_CRC) = v)

    //Register Read/Write-Mask
    #define  REG_RMASK_ACU_CRC()                                  (0xFFFFFFFF)  
    #define  REG_WMASK_ACU_CRC()                                  (0x0)

    //Field: ACU_CRC
    #define  FLD_LSB_ACU_CRC()                                    (0)
    #define  FLD_MSB_ACU_CRC()                                    (31)
    #define  FLD_MASK_ACU_CRC()                                   (FLD_MASK(0, 31))
    #define  FLD_MWD_ACU_CRC(v)                                   (FLD_MWD(0, 31, v))
    #define  FLD_MRD_ACU_CRC(v)                                   (FLD_MRD(0, 31, v))
    #define  GET_ACU_CRC()                                        OP_FLD_RD(REG_ACU_CRC, 0, 31)

    //Write-Register Using Field-Name
    #define  WRF_ACU_CRC(CRC) \
                (WR_ACU_CRC( \
   \
                ))



#endif /*__LIGHTELF_ACU_REG_H__*/
// vim:ft=c:nowrap:noma
